<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class NursingAssessmentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'schedule_id' => 'nullable|integer',
            'lastName' => 'nullable|string',
            'firstName' => 'nullable|string',
            'middleInitial' => 'nullable|string',
            'passportId' => 'nullable|string',
            'ssn' => 'nullable|integer',
            'contactPerson' => 'nullable|string',
            'contactPhone' => 'nullable|string',
            'lsDwelling' => 'nullable|string',
            'otherDwelling' => 'nullable|string',
            'Floor' => 'nullable|string',
            'Elevator' => 'nullable|string',
            'LivesAlone' => 'nullable|string',
            'individualsLiving' => 'nullable|string',
            'services' => 'nullable|string',
            'Hospital' => 'nullable|string',
            'hospitalAddress' => 'nullable|string',
            'hospitalizedFrom' => 'nullable|string',
            'hospitalizedTo' => 'nullable|string',
            'Diagnoses' => 'nullable|string',
            'hospitalContact' => 'nullable|string',
            'hospitalPhone' => 'nullable|string',
            'patientDirect' => 'nullable|string',
            'Relationship' => 'nullable|string',
            'patientHeight' => 'nullable|string',
            'patientWeight' => 'nullable|string',
            'patientWeightLoss' => 'nullable|string',
            'amountLost' => 'nullable|string',
            'Speech_1' => 'nullable|boolean',
            'Speech_2' => 'nullable|boolean',
            'Speech_3' => 'nullable|boolean',
            'Sight_1' => 'nullable|boolean',
            'Sight_2' => 'nullable|boolean',
            'Sight_3' => 'nullable|boolean',
            'Hearing_1' => 'nullable|boolean',
            'Hearing_2' => 'nullable|boolean',
            'Hearing_3' => 'nullable|boolean',
            'Hand_1' => 'nullable|boolean',
            'Hand_2' => 'nullable|boolean',
            'Hand_3' => 'nullable|boolean',
            'Upper_1' => 'nullable|boolean',
            'Upper_2' => 'nullable|boolean',
            'Upper_3' => 'nullable|boolean',
            'Lower_1' => 'nullable|boolean',
            'Lower_2' => 'nullable|boolean',
            'Lower_3' => 'nullable|boolean',
            'Respiratory_1' => 'nullable|boolean',
            'Respiratory_2' => 'nullable|boolean',
            'Respiratory_3' => 'nullable|boolean',
            'Cardiac_1' => 'nullable|boolean',
            'Cardiac_2' => 'nullable|boolean',
            'Cardiac_3' => 'nullable|boolean',
            'Circulatory_1' => 'nullable|boolean',
            'Circulatory_2' => 'nullable|boolean',
            'Circulatory_3' => 'nullable|boolean',
            'describeImpact' => 'nullable|string',
            'IsPatientAlert' => 'nullable|string',
            'HistoryOfTuberculosis' => 'nullable|string',
            'extraPulmonary' => 'nullable|string',
            'patientCompleteTherapy' => 'nullable|string',
            'patientTuberculosis' => 'nullable|string',
            'Pulmonary' => 'nullable|boolean',
            'extrapulmonary2' => 'nullable|boolean',
            'HxProphylaxis' => 'nullable|string',
            'result' => 'nullable|string',
            'available' => 'nullable|string',
            'afb' => 'nullable|string',
            'chestXray' => 'nullable|string',
            'Oriented_1' => 'nullable|boolean',
            'Oriented_2' => 'nullable|boolean',
            'Oriented_3' => 'nullable|boolean',
            'Anxiety_1' => 'nullable|boolean',
            'Anxiety_2' => 'nullable|boolean',
            'Anxiety_3' => 'nullable|boolean',
            'Agitated_1' => 'nullable|boolean',
            'Agitated_2' => 'nullable|boolean',
            'Agitated_3' => 'nullable|boolean',
            'Short_1' => 'nullable|boolean',
            'Short_2' => 'nullable|boolean',
            'Short_3' => 'nullable|boolean',
            'Wanders_1' => 'nullable|boolean',
            'Wanders_2' => 'nullable|boolean',
            'Wanders_3' => 'nullable|boolean',
            'Depression_1' => 'nullable|boolean',
            'Depression_2' => 'nullable|boolean',
            'Depression_3' => 'nullable|boolean',
            'Impaired_1' => 'nullable|boolean',
            'Impaired_2' => 'nullable|boolean',
            'Impaired_3' => 'nullable|boolean',
            'Danger_1' => 'nullable|boolean',
            'Danger_2' => 'nullable|boolean',
            'Danger_3' => 'nullable|boolean',
            'Articulates_1' => 'nullable|boolean',
            'Articulates_2' => 'nullable|boolean',
            'Articulates_3' => 'nullable|boolean',
            'disorder_1' => 'nullable|boolean',
            'disorder_2' => 'nullable|boolean',
            'disorder_3' => 'nullable|boolean',
            'Abusive_1' => 'nullable|boolean',
            'Abusive_2' => 'nullable|boolean',
            'Abusive_3' => 'nullable|boolean',
            'Mental_1' => 'nullable|boolean',
            'Mental_2' => 'nullable|boolean',
            'Mental_3' => 'nullable|boolean',
            'independent_1' => 'nullable|boolean',
            'independent_2' => 'nullable|boolean',
            'independent_3' => 'nullable|boolean',
            'reminding_1' => 'nullable|boolean',
            'reminding_2' => 'nullable|boolean',
            'reminding_3' => 'nullable|boolean',
            'compliant_1' => 'nullable|boolean',
            'compliant_2' => 'nullable|boolean',
            'compliant_3' => 'nullable|boolean',
            'preparing_1' => 'nullable|boolean',
            'preparing_2' => 'nullable|boolean',
            'preparing_3' => 'nullable|boolean',
            'administration_1' => 'nullable|boolean',
            'administration_2' => 'nullable|boolean',
            'administration_3' => 'nullable|boolean',
            'TaughtToAdminister' => 'nullable|string',
            'explain' => 'nullable|string',
            'centralLine' => 'nullable|string',
            'peripheralLine' => 'nullable|string',
            'requiresHome' => 'nullable|string',
            'Injections' => 'nullable|string',
            'bloodWork' => 'nullable|string',

            'Continent_1' => 'nullable|boolean',
            'Continent_2' => 'nullable|boolean',
            'occasionallyIncontinen_1' => 'nullable|boolean',
            'occasionallyIncontinen_2' => 'nullable|boolean',
            'Incontinent_1' => 'nullable|boolean',
            'Incontinent_2' => 'nullable|boolean',
            'Decubitus' => 'nullable|boolean',
            'Dressings' => 'nullable|boolean',
            'dressingsSterile' => 'nullable|boolean',
            'Enema' => 'nullable|boolean',
            'Catheter' => 'nullable|boolean',
            'Monitor' => 'nullable|boolean',
            'tubeFeeding' => 'nullable|boolean',
            'tubeIrrigation' => 'nullable|boolean',
            'Suctioning' => 'nullable|boolean',
            'Oxygen' => 'nullable|boolean',
            'bloodTests' => 'nullable|boolean',
            'Ambulation' => 'nullable|boolean',
            'rehabilitativeTherapy' => 'nullable|boolean',
            'physicalTherapy' => 'nullable|boolean',
            'ambulateInside_1' => 'nullable|boolean',
            'ambulateInside_2' => 'nullable|boolean',
            'ambulateInside_3' => 'nullable|boolean',
            'ambulateInside_4' => 'nullable|boolean',
            'ambulateInside_5' => 'nullable|boolean',
            'ambulateInside_6' => 'nullable|boolean',
            'ambulateOutside_1' => 'nullable|boolean',
            'ambulateOutside_2' => 'nullable|boolean',
            'ambulateOutside_3' => 'nullable|boolean',
            'ambulateOutside_4' => 'nullable|boolean',
            'ambulateOutside_5' => 'nullable|boolean',
            'ambulateOutside_6' => 'nullable|boolean',
            'seatedPosition_1' => 'nullable|boolean',
            'seatedPosition_2' => 'nullable|boolean',
            'seatedPosition_3' => 'nullable|boolean',
            'seatedPosition_4' => 'nullable|boolean',
            'seatedPosition_5' => 'nullable|boolean',
            'seatedPosition_6' => 'nullable|boolean',
            'fromBed_1' => 'nullable|boolean',
            'fromBed_2' => 'nullable|boolean',
            'fromBed_3' => 'nullable|boolean',
            'fromBed_4' => 'nullable|boolean',
            'fromBed_5' => 'nullable|boolean',
            'fromBed_6' => 'nullable|boolean',
            'Commode_1' => 'nullable|boolean',
            'Commode_2' => 'nullable|boolean',
            'Commode_3' => 'nullable|boolean',
            'Commode_4' => 'nullable|boolean',
            'Commode_5' => 'nullable|boolean',
            'Commode_6' => 'nullable|boolean',
            'Wheelchair_1' => 'nullable|boolean',
            'Wheelchair_2' => 'nullable|boolean',
            'Wheelchair_3' => 'nullable|boolean',
            'Wheelchair_4' => 'nullable|boolean',
            'Wheelchair_5' => 'nullable|boolean',
            'Wheelchair_6' => 'nullable|boolean',
            'Grooming_1' => 'nullable|boolean',
            'Grooming_2' => 'nullable|boolean',
            'Grooming_3' => 'nullable|boolean',
            'Dressing_1' => 'nullable|boolean',
            'Dressing_2' => 'nullable|boolean',
            'Dressing_3' => 'nullable|boolean',
            'Washing_1' => 'nullable|boolean',
            'Washing_2' => 'nullable|boolean',
            'Washing_3' => 'nullable|boolean',
            'Bathing_1' => 'nullable|boolean',
            'Bathing_2' => 'nullable|boolean',
            'Bathing_3' => 'nullable|boolean',
            'Feeding_1' => 'nullable|boolean',
            'Feeding_2' => 'nullable|boolean',
            'Feeding_3' => 'nullable|boolean',
            'mealPrep_1' => 'nullable|boolean',
            'mealPrep_2' => 'nullable|boolean',
            'mealPrep_3' => 'nullable|boolean',
            'reheatMeals_1' => 'nullable|boolean',
            'reheatMeals_2' => 'nullable|boolean',
            'reheatMeals_3' => 'nullable|boolean',
            'Bathroom_1' => 'nullable|boolean',
            'Bathroom_2' => 'nullable|boolean',
            'Bathroom_3' => 'nullable|boolean',
            'bedpan_1' => 'nullable|boolean',
            'bedpan_2' => 'nullable|boolean',
            'bedpan_3' => 'nullable|boolean',
            'Commode_11' => 'nullable|boolean',
            'Commode_12' => 'nullable|boolean',
            'Commode_13' => 'nullable|boolean',
            'Catheter_1' => 'nullable|boolean',
            'Catheter_2' => 'nullable|boolean',
            'Catheter_3' => 'nullable|boolean',
            'Laundry_1' => 'nullable|boolean',
            'Laundry_2' => 'nullable|boolean',
            'Laundry_3' => 'nullable|boolean',
            'Shopping_1' => 'nullable|boolean',
            'Shopping_2' => 'nullable|boolean',
            'Shopping_3' => 'nullable|boolean',
            'Housecleaning_1' => 'nullable|boolean',
            'Housecleaning_2' => 'nullable|boolean',
            'Housecleaning_3' => 'nullable|boolean',
            'observationOfPatient' => 'nullable|string',
            'relayed' => 'nullable|string',
            'Prepared' => 'nullable|string',
            'preparedPhone' => 'nullable|string',
            'Affiliation' => 'nullable|string',
            'fax' => 'nullable|string',
            'Signature' => 'nullable|string',
            'signatureDate' => 'nullable|string',
            'agencyServicesToPatient' => 'nullable|string',
            'agencyName' => 'nullable|string',
            'Services2' => 'nullable|string',
            'insuranceBenefits' => 'nullable|string',
            'appliedToMedicaid' => 'nullable|string',
            'Doctor' => 'nullable|boolean',
            'socialWorker' => 'nullable|boolean',
            'dischargePlanner' => 'nullable|boolean',
            'Location' => 'nullable|string',
            'otherlocation' => 'nullable|string',
            'pleaseExplain' => 'nullable|string',
        ];
    }
}
