<!DOCTYPE html>
<html style="box-sizing: border-box;">
<head style="box-sizing: border-box;">
    <meta charset="utf-8" style="box-sizing: border-box;">
    <meta name="viewport" content="width=device-width, initial-scale=1" style="box-sizing: border-box;">
    <meta charset="UTF-8" style="box-sizing: border-box;">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" style="box-sizing: border-box;">
    <title style="box-sizing: border-box;">Bladder and Bowel</title>
    
    

</head>
<body class="container" style="box-sizing: border-box;margin: 0;font-family: var(--bs-body-font-family);font-size: var(--bs-body-font-size);font-weight: var(--bs-body-font-weight);line-height: var(--bs-body-line-height);color: var(--bs-body-color);text-align: var(--bs-body-text-align);background-color: var(--bs-body-bg);-webkit-text-size-adjust: 100%;-webkit-tap-highlight-color: transparent;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-right: auto;margin-left: auto;">
<table class="table table-bordered align-middle" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-black py-2 px-3" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;--bs-bg-opacity: 1;padding-right: 1rem!important;padding-left: 1rem!important;padding-top: .5rem!important;padding-bottom: .5rem!important;background-color: rgba(var(--bs-black-rgb),var(--bs-bg-opacity))!important;">
            <h3 class="text-center m-0 text-white" style="box-sizing: border-box;margin-top: 0;margin-bottom: .5rem;font-weight: 500;line-height: 1.2;color: rgba(var(--bs-white-rgb),var(--bs-text-opacity))!important;font-size: calc(1.3rem + .6vw);--bs-text-opacity: 1;padding: .5rem .5rem;background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);margin: 0!important;text-align: center!important;"><span class="border-md-end-1" style="box-sizing: border-box;">Section H</span> <span style="box-sizing: border-box;">Bladder and Bowel</span>
            </h3>
        </td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1600</b>. Has this patient been treated for a <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Urinary Tract Infection</b> in the past 14 days?
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">No</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Yes</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> NA <b style="box-sizing: border-box;font-weight: bolder;">Patient on prophylactic treatment</b></label>
            </div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> UK <b style="box-sizing: border-box;font-weight: bolder;">Unknown</b> [Omit “UK” option on DC]</label>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1610. Urinary Incontinence or Urinary Catheter Presence</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;">
                    0. <b style="box-sizing: border-box;font-weight: bolder;">No incontinence or catheter</b> (includes anuria or ostomy for urinary drainage)</label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Patient is incontinent</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">Patient requires a urinary catheter</b>
                    (specifically: external, indwelling, intermittent, or suprapubic)</label></div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1620. Bowel Incontinence Frequency</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">Very rarely or never has bowel incontinence</b></label>
            </div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Less than once weekly</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">One to three times weekly</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 3. <b style="box-sizing: border-box;font-weight: bolder;">Four to six times weekly</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 4. <b style="box-sizing: border-box;font-weight: bolder;">On a daily basis</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 5. <b style="box-sizing: border-box;font-weight: bolder;">More often than once daily</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> NA. <b style="box-sizing: border-box;font-weight: bolder;">Patient has ostomy for bowel
                        elimination</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> UK. <b style="box-sizing: border-box;font-weight: bolder;">Unknown</b> [Omit “UK” option on DC]</label>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1630. Ostomy for Bowel Elimination</b>
            <p style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Does this patient have an ostomy for bowel elimination that (within the last 14 days): a) was related to
                an inpatient facility stay; <u style="box-sizing: border-box;">or</u> b) necessitated a change in medical or treatment regimen?</p>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">Patient does <u style="box-sizing: border-box;">not</u> have an ostomy for bowel
                        elimination.</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Patient's ostomy was not related to an inpatient
                        stay and did <u style="box-sizing: border-box;">not</u> necessitate change in medical or treatment regimen.</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">The ostomy <u style="box-sizing: border-box;">was</u> related to an inpatient
                        stay or <u style="box-sizing: border-box;">did</u> necessitate change in medical or treatment regimen.</b></label></div>
        </td>
    </tr>
</table>
</body>
</html>
