<!DOCTYPE html>
<html style="box-sizing: border-box;">
<head style="box-sizing: border-box;">
    <meta charset="utf-8" style="box-sizing: border-box;">
    <meta name="viewport" content="width=device-width, initial-scale=1" style="box-sizing: border-box;">
    <meta charset="UTF-8" style="box-sizing: border-box;">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" style="box-sizing: border-box;">
    <title style="box-sizing: border-box;">Skin Conditions</title>
     
 

</head>
<body class="container" style="box-sizing: border-box;margin: 0;font-family: var(--bs-body-font-family);font-size: var(--bs-body-font-size);font-weight: var(--bs-body-font-weight);line-height: var(--bs-body-line-height);color: var(--bs-body-color);text-align: var(--bs-body-text-align);background-color: var(--bs-body-bg);-webkit-text-size-adjust: 100%;-webkit-tap-highlight-color: transparent;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-right: auto;margin-left: auto;">
<table class="table table-bordered align-middle" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-black py-2 px-3" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;--bs-bg-opacity: 1;padding-right: 1rem!important;padding-left: 1rem!important;padding-top: .5rem!important;padding-bottom: .5rem!important;background-color: rgba(var(--bs-black-rgb),var(--bs-bg-opacity))!important;">
            <h3 class="text-center m-0 text-white" style="box-sizing: border-box;margin-top: 0;margin-bottom: .5rem;font-weight: 500;line-height: 1.2;color: rgba(var(--bs-white-rgb),var(--bs-text-opacity))!important;font-size: calc(1.3rem + .6vw);--bs-text-opacity: 1;padding: .5rem .5rem;background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);margin: 0!important;text-align: center!important;">Skin Conditions</h3>
        </td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1306.</b> Does this patient have at least one <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Unhealed Pressure Ulcer/Injury at Stage 2 or Higher</b>
            or designated as Unstageable? (Excludes Stage 1 pressure injuries and all healed pressure ulcers/injuries)
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">No ➔</b> Skip to M1322, Current Number of Stage
                    1 Pressure Injuries at SOC/ROC; Skip to M1324, Stage of Most ProblematicUnhealed Pressure
                    Ulcer/Injury that is Stageable at DC</label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Yes</b></label></div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1307. The Oldest Stage 2 Pressure Ulcer</b> that is present at discharge: (Excludes healed Stage 2
            pressure ulcers)
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Was present at the most recent SOC/ROC
                        assessment</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;">
                <label class="form-check-label" style="box-sizing: border-box;display: inline-block;">2. <b style="box-sizing: border-box;font-weight: bolder;">Developed since the most recent SOC/ROC assessment.</b> Record
                    date pressure ulcer first identified:</label>
                <div class="row row-flex align-items-center gx-3 gy-2 mt-0" style="box-sizing: border-box;--bs-gutter-x: 1rem;--bs-gutter-y: 0.5rem;display: flex;flex-wrap: wrap;margin-top: 0!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));align-items: center!important;">
                    <div class="col-auto" style="box-sizing: border-box;flex-shrink: 0;width: auto;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                        <div class="input-group" style="box-sizing: border-box;position: relative;display: flex;flex-wrap: wrap;align-items: stretch;width: 100%;">
                            <label class="input-group-text" style="box-sizing: border-box;display: flex;align-items: center;padding: .375rem .75rem;font-size: 1rem;font-weight: 400;line-height: 1.5;color: var(--bs-body-color);text-align: center;white-space: nowrap;background-color: var(--bs-tertiary-bg);border: var(--bs-border-width) solid var(--bs-border-color);border-radius: var(--bs-border-radius);">Month</label>
                            < value here >
                        </div>
                    </div>
                    <div class="col-auto" style="box-sizing: border-box;flex-shrink: 0;width: auto;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                        <div class="input-group" style="box-sizing: border-box;position: relative;display: flex;flex-wrap: wrap;align-items: stretch;width: 100%;">
                            <label class="input-group-text" style="box-sizing: border-box;display: flex;align-items: center;padding: .375rem .75rem;font-size: 1rem;font-weight: 400;line-height: 1.5;color: var(--bs-body-color);text-align: center;white-space: nowrap;background-color: var(--bs-tertiary-bg);border: var(--bs-border-width) solid var(--bs-border-color);border-radius: var(--bs-border-radius);">Day</label>
                            < value here >
                        </div>
                    </div>
                    <div class="col-auto" style="box-sizing: border-box;flex-shrink: 0;width: auto;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                        <div class="input-group" style="box-sizing: border-box;position: relative;display: flex;flex-wrap: wrap;align-items: stretch;width: 100%;">
                            <label class="input-group-text" style="box-sizing: border-box;display: flex;align-items: center;padding: .375rem .75rem;font-size: 1rem;font-weight: 400;line-height: 1.5;color: var(--bs-body-color);text-align: center;white-space: nowrap;background-color: var(--bs-tertiary-bg);border: var(--bs-border-width) solid var(--bs-border-color);border-radius: var(--bs-border-radius);">Year</label>
                            < value here >
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> NA <b style="box-sizing: border-box;font-weight: bolder;">No Stage 2 pressure ulcers are present at
                        discharge</b></label></div>
        </td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">SOC/ROC</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1311. Current Number of Unhealed Pressure Ulcers/Injuries at Each Stage</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">A1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 2:</b> Partial thickness loss of dermis presenting as a shallow open ulcer with a
                red or pink wound bed, without slough. May also present as an intact or open/ruptured blister.<br style="box-sizing: border-box;"><b style="box-sizing: border-box;font-weight: bolder;">Number
                    of Stage 2 pressure ulcers</b></label></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">B1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 3:</b> Full thickness tissue loss. Subcutaneous fat may be visible but bone,
                tendon, or muscle is not exposed. Slough may be present but does not obscure the depth of tissue loss.
                May include undermining and tunneling.<br style="box-sizing: border-box;"><b style="box-sizing: border-box;font-weight: bolder;">Number of Stage 3 pressure ulcers</b></label></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">C1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 4:</b> Full thickness tissue loss with exposed bone, tendon, or muscle. Slough or
                eschar may be present on some parts of the wound bed. Often includes undermining and tunneling.<br style="box-sizing: border-box;"><b style="box-sizing: border-box;font-weight: bolder;">Number
                    of Stage 4 pressure ulcers</b></label></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">D1. <b style="box-sizing: border-box;font-weight: bolder;">Unstageable: Non-removable dressing/device:</b> Known but not stageable due to
                non-removable dressing/device<br style="box-sizing: border-box;"><b style="box-sizing: border-box;font-weight: bolder;">Number of unstageable pressure ulcers/injuries due to non-removable
                    dressing/device</b></label></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">E1. <b style="box-sizing: border-box;font-weight: bolder;">Unstageable: Slough and/or eschar:</b> Known but not stageable due to coverage of wound
                bed by slough and/or eschar<br style="box-sizing: border-box;"><b style="box-sizing: border-box;font-weight: bolder;">Number of unstageable pressure ulcers due to coverage of wound bed by
                    slough and/or eschar</b></label></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">F1. <b style="box-sizing: border-box;font-weight: bolder;">Unstageable: Deep tissue injury:</b><br style="box-sizing: border-box;"><b style="box-sizing: border-box;font-weight: bolder;">Number of unstageable pressure injuries
                    presenting as deep tissue injury</b></label></td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Discharge</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1311. Current Number of Unhealed Pressure Ulcers/Injuries at Each Stage</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="row row-flex align-items-center" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: calc(-1 * var(--bs-gutter-y));margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">A1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 2:</b> Partial thickness loss of dermis presenting as a shallow open
                        ulcer with a red or pink wound bed, without slough. May also present as an intact or
                        open/ruptured blister.<br style="box-sizing: border-box;">
                        <b style="box-sizing: border-box;font-weight: bolder;">Number of Stage 2 pressure ulcers</b> – If 0 ➔ <i style="box-sizing: border-box;">Skip to M1311B1, Stage 3</i></label>
                </div>
            </div>
            <div class="row row-flex align-items-center mt-3" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: 1rem!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">A2. <b style="box-sizing: border-box;font-weight: bolder;">Number of <u style="box-sizing: border-box;">these</u> Stage 2 pressure ulcers that were present at most recent
                            SOC/ROC</b><br style="box-sizing: border-box;"> – enter how many were noted at the time of most recent SOC/ROC</label>
                </div>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="row row-flex align-items-center" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: calc(-1 * var(--bs-gutter-y));margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">B1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 3:</b> Full thickness tissue loss. Subcutaneous fat may be visible but
                        bone, tendon, or muscle is not exposed. Slough may be present but does not obscure the depth of
                        tissue loss. May include undermining and tunneling.<br style="box-sizing: border-box;">
                        <b style="box-sizing: border-box;font-weight: bolder;">Number of Stage 3 pressure ulcers</b> – If 0 ➔ <i style="box-sizing: border-box;">Skip to M1311C1, Stage 4</i></label>
                </div>
            </div>
            <div class="row row-flex align-items-center mt-3" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: 1rem!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">B2. <b style="box-sizing: border-box;font-weight: bolder;">Number of <u style="box-sizing: border-box;">these</u> Stage 3 pressure ulcers that were present at most recent
                            SOC/ROC</b><br style="box-sizing: border-box;"> – enter how many were noted at the time of most recent SOC/ROC</label>
                </div>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="row row-flex align-items-center" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: calc(-1 * var(--bs-gutter-y));margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">C1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 4:</b> Full thickness tissue loss with exposed bone, tendon, or muscle.
                        Slough or eschar may be present on some parts of the wound bed. Often includes undermining and
                        tunneling.<br style="box-sizing: border-box;">
                        <b style="box-sizing: border-box;font-weight: bolder;">Number of Stage 4 pressure ulcers</b> – If 0 ➔ <i style="box-sizing: border-box;">Skip to M1311D1, Unstageable: Non-removable
                            dressing/device</i></label>
                </div>
            </div>
            <div class="row row-flex align-items-center mt-3" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: 1rem!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">C2. <b style="box-sizing: border-box;font-weight: bolder;">Number of <u style="box-sizing: border-box;">these</u> Stage 4 pressure ulcers that were present at most recent
                            SOC/ROC</b><br style="box-sizing: border-box;"> – enter how many were noted at the time of most recent SOC/ROC</label>
                </div>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="row row-flex align-items-center" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: calc(-1 * var(--bs-gutter-y));margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">D1. <b style="box-sizing: border-box;font-weight: bolder;">Unstageable: Non-removable dressing/device:</b> Known but not stageable due to
                        non-removable dressing/device<br style="box-sizing: border-box;">
                        <b style="box-sizing: border-box;font-weight: bolder;">Number of unstageable pressure ulcers/injuries due to non-removable dressing/device</b> – If
                        0 ➔ <i style="box-sizing: border-box;">Skip to M1311E1,Unstageable: Slough and/or eschar</i></label>
                </div>
            </div>
            <div class="row row-flex align-items-center mt-3" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: 1rem!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">D2. <b style="box-sizing: border-box;font-weight: bolder;">Number of <u style="box-sizing: border-box;">these</u> unstageable pressure ulcers/injuries that were present
                            at most recent SOC/ROC</b><br style="box-sizing: border-box;"> – enter how many were noted at the time of most recent
                        SOC/ROC</label>
                </div>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="row row-flex align-items-center" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: calc(-1 * var(--bs-gutter-y));margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">E1. <b style="box-sizing: border-box;font-weight: bolder;">Unstageable: Slough and/or eschar:</b> Known but not stageable due to coverage
                        of wound bed by slough and/or eschar<br style="box-sizing: border-box;">
                        <b style="box-sizing: border-box;font-weight: bolder;">Number of unstageable pressure ulcers due to coverage of wound bed by slough and/or
                            eschar</b> – If 0 ➔ <i style="box-sizing: border-box;">Skip to M1311F1,Unstageable: Deep tissue injury</i></label>
                </div>
            </div>
            <div class="row row-flex align-items-center mt-3" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: 1rem!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">E2. <b style="box-sizing: border-box;font-weight: bolder;">Number of <u style="box-sizing: border-box;">these</u> unstageable pressure ulcers that were present at most
                            recent SOC/ROC</b><br style="box-sizing: border-box;"> – enter how many were noted at the time of most recent
                        SOC/ROC</label>
                </div>
            </div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="row row-flex align-items-center" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: calc(-1 * var(--bs-gutter-y));margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">F1. <b style="box-sizing: border-box;font-weight: bolder;">Unstageable: Deep tissue injury</b><br style="box-sizing: border-box;">
                        <b style="box-sizing: border-box;font-weight: bolder;">Number of unstageable pressure injuries presenting as deep tissue injury</b> – If 0 ➔ <i style="box-sizing: border-box;">Skip
                            to M1324, Stage of MostProblematic Unhealed Pressure Ulcer/Injury that is
                            Stageable</i></label>
                </div>
            </div>
            <div class="row row-flex align-items-center mt-3" style="box-sizing: border-box;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;display: flex;flex-wrap: wrap;margin-top: 1rem!important;margin-right: calc(-.5 * var(--bs-gutter-x));margin-left: calc(-.5 * var(--bs-gutter-x));padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);align-items: center!important;">
                <div class="col-sm-2 col-3" style="box-sizing: border-box;flex-shrink: 0;width: 16.66666667%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">< value here ></div>
                <div class="col-sm-10 col-9" style="box-sizing: border-box;flex-shrink: 0;width: 83.33333333%;max-width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-top: var(--bs-gutter-y);flex: 0 0 auto;">
                    <label for="" style="box-sizing: border-box;display: inline-block;">F2. <b style="box-sizing: border-box;font-weight: bolder;">Number of <u style="box-sizing: border-box;">these</u> unstageable pressure injuries that were present at most
                            recent SOC/ROC</b><br style="box-sizing: border-box;"> – enter how many were noted at the time of most recent
                        SOC/ROC</label>
                </div>
            </div>
        </td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1322. Current Number of Stage 1 Pressure Injuries</b>
            <p style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Intact skin with non-blanchable redness of a localized area usually over a bony prominence. Darkly
                pigmented skin may not have a visible blanching; in dark skin tones only, it may appear with persistent
                blue or purple hues.</p>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="width: 120px;box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td class="labels-group" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);"><b style="box-sizing: border-box;font-weight: bolder;">0</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);"><b style="box-sizing: border-box;font-weight: bolder;">1</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);"><b style="box-sizing: border-box;font-weight: bolder;">2</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);"><b style="box-sizing: border-box;font-weight: bolder;">3</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);"><b style="box-sizing: border-box;font-weight: bolder;">4 or more</b></label>
        </td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive mt-4" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);margin-top: 1.5rem!important;">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1324. Stage of Most Problematic Unhealed Pressure Ulcer/Injury that is Stageable</b>
            <p style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Excludes pressure ulcer/injury that cannot be staged due to a non-removable dressing/device, coverage of
                wound bed by slough and/or eschar, or deep tissue injury.</p>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Stage 1</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">Stage 2</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 3. <b style="box-sizing: border-box;font-weight: bolder;">Stage 3</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 4. <b style="box-sizing: border-box;font-weight: bolder;">Stage 4</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> NA <b style="box-sizing: border-box;font-weight: bolder;">Patient has no pressure ulcers/injuries or no
                        stageable pressure ulcers/injuries</b></label></div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1330</b>. Does this patient have a <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Stasis Ulcer</b>?
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">No ➔</b> <i style="box-sizing: border-box;">Skip to M1340, Surgical
                        Wound</i></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Yes, patient has BOTH observable and
                        unobservable stasis ulcers</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">Yes, patient has observable stasis ulcers
                        ONLY</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 3. <b style="box-sizing: border-box;font-weight: bolder;">Yes, patient has unobservable stasis ulcers
                        ONLY</b> (known but not observable due to non-removable dressing/device) ➔ <i style="box-sizing: border-box;">Skip to M1340,
                        Surgical Wound</i></label></div>
        </td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive mt-4" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);margin-top: 1.5rem!important;">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1332. Current Number of Stasis Ulcer(s) that are Observable</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="width: 120px;box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ></td>
        <td class="labels-group" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">1. <b style="box-sizing: border-box;font-weight: bolder;">One</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">2. <b style="box-sizing: border-box;font-weight: bolder;">Two</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">3. <b style="box-sizing: border-box;font-weight: bolder;">Three</b></label><br style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">
            <label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">4. <b style="box-sizing: border-box;font-weight: bolder;">Four or more</b></label>
        </td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive mt-4" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);margin-top: 1.5rem!important;">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1334. Status of Most Problematic Stasis Ulcer that is Observable</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Fully granulating</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">Early/partial granulation</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 3. <b style="box-sizing: border-box;font-weight: bolder;">Not healing</b></label></div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1340.</b> Does this patient have a <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Surgical Wound</b>?
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">No ➔</b> <i style="box-sizing: border-box;">Skip to N0415, High-Risk Drug
                        Classes: Use and Indication</i></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Yes, patient has at least one observable
                        surgical wound</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">Surgical wound known but not observable due to
                        non-removable dressing/device ➔</b> <i style="box-sizing: border-box;">Skip to N0415, High-Risk DrugClasses: Use and
                        Indication</i></label></div>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="border-0" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;border: 0!important;"></td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1342. Status of Most Problematic Surgical Wound that is Observable</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">Newly epithelialized</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Fully granulating</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;">Early/partial granulation</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 3. <b style="box-sizing: border-box;font-weight: bolder;">Not healing</b></label></div>
        </td>
    </tr>
</table>
</body>
</html>
