<!DOCTYPE html>
<html style="box-sizing: border-box;">
<head style="box-sizing: border-box;">
    <meta charset="utf-8" style="box-sizing: border-box;">
    <meta name="viewport" content="width=device-width, initial-scale=1" style="box-sizing: border-box;">
    <meta charset="UTF-8" style="box-sizing: border-box;">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" style="box-sizing: border-box;">
    <title style="box-sizing: border-box;">Swallowing Nutritional</title>
     
 

</head>
<body class="container" style="box-sizing: border-box;margin: 0;font-family: var(--bs-body-font-family);font-size: var(--bs-body-font-size);font-weight: var(--bs-body-font-weight);line-height: var(--bs-body-line-height);color: var(--bs-body-color);text-align: var(--bs-body-text-align);background-color: var(--bs-body-bg);-webkit-text-size-adjust: 100%;-webkit-tap-highlight-color: transparent;--bs-gutter-x: 1.5rem;--bs-gutter-y: 0;width: 100%;padding-right: calc(var(--bs-gutter-x) * .5);padding-left: calc(var(--bs-gutter-x) * .5);margin-right: auto;margin-left: auto;">
<table class="table table-bordered align-middle not-responsive" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-black py-2 px-3" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;--bs-bg-opacity: 1;padding-right: 1rem!important;padding-left: 1rem!important;padding-top: .5rem!important;padding-bottom: .5rem!important;background-color: rgba(var(--bs-black-rgb),var(--bs-bg-opacity))!important;">
            <h3 class="text-center m-0 text-white" style="box-sizing: border-box;margin-top: 0;margin-bottom: .5rem;font-weight: 500;line-height: 1.2;color: rgba(var(--bs-white-rgb),var(--bs-text-opacity))!important;font-size: calc(1.3rem + .6vw);--bs-text-opacity: 1;padding: .5rem .5rem;background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);margin: 0!important;text-align: center!important;">Swallowing/Nutritional Status</h3>
        </td>
    </tr>

    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1060. Height and Weight –</b> While measuring, if the number is X.1-X.4 round down; X.5 or greater round
            up.
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ><b class="d-block text-center" style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;text-align: center!important;">inches</b></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">A. <b style="box-sizing: border-box;font-weight: bolder;">Height</b> (in inches). Record most recent height measure since the most recent SOC/ROC</label>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">< value here ><b class="d-block text-center" style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;text-align: center!important;">pounds</b></td>
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;"><label for="" style="box-sizing: border-box;display: inline-block;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">A. <b style="box-sizing: border-box;font-weight: bolder;">Weight</b> (in pounds). Base weight on most recent measure in last 30 days; measure
                weight consistently, according tostandard agency practice (for example, in a.m. after voiding, before
                meal, with shoes off, etc.)</label></td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive default-td" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">SOC/ROC</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">K0520. Nutritional Approaches</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td rowspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">1. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">On Admission</b>
            <span class="ms-3 d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;margin-left: 1rem!important;">Check all of the nutritional approaches that apply on admission</span></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"><b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">1.<br style="box-sizing: border-box;">On Admission</b></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="text-center" style="max-width: 120px;box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;"><b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Check all that apply ↓</b></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">A. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Parenteral/IV feeding</b></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">B. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Feeding tube</b> (e.g., nasogastric or abdominal (PEG))</td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">C. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Mechanically altered diet</b> – require change in texture of food or liquids(e.g., pureed food,
            thickened liquids)
        </td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">D. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Therapeutic diet</b> (e.g., low salt, diabetic, low cholesterol)</td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">Z. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">None of the above</b></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"></td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive default-td" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="3" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Discharge</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="3" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">K0520. Nutritional Approaches</b>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td rowspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <p style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">4. <b style="box-sizing: border-box;font-weight: bolder;">Last 7 days</b>
                <span class="ms-3 d-block" style="box-sizing: border-box;display: block!important;margin-left: 1rem!important;">Check all of the nutritional approaches that were received in the last 7 days</span>
            </p>
            <p style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">5. <b style="box-sizing: border-box;font-weight: bolder;">At discharge</b>
                <span class="ms-3 d-block" style="box-sizing: border-box;display: block!important;margin-left: 1rem!important;">Check all of the nutritional approaches that were being received at discharge</span>
            </p>
        </td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"><b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">4.<br style="box-sizing: border-box;">Last 7 days</b></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;"><b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">5.<br style="box-sizing: border-box;">At discharge</b></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="text-center" style="max-width: 120px;box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;" colspan="2"><b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">↓ Check all that apply ↓</b></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">A. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Parenteral/IV feeding</b></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">B. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Feeding tube</b> (e.g., nasogastric or abdominal (PEG))</td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">C. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Mechanically altered diet</b> – require change in texture of food or liquids(e.g., pureed food,
            thickened liquids)
        </td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">D. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Therapeutic diet</b> (e.g., low salt, diabetic, low cholesterol)</td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">Z. <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">None of the above</b></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
        <td class="bg-secondary-subtle text-center" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;text-align: center!important;background-color: var(--bs-secondary-bg-subtle)!important;">< value here ></td>
    </tr>
</table>

<table class="table table-bordered align-middle not-responsive" style="box-sizing: border-box;caption-side: bottom;border-collapse: collapse;--bs-table-color-type: initial;--bs-table-bg-type: initial;--bs-table-color-state: initial;--bs-table-bg-state: initial;--bs-table-color: var(--bs-body-color);--bs-table-bg: var(--bs-body-bg);--bs-table-border-color: var(--bs-border-color);--bs-table-accent-bg: transparent;--bs-table-striped-color: var(--bs-body-color);--bs-table-striped-bg: rgba(0, 0, 0, 0.05);--bs-table-active-color: var(--bs-body-color);--bs-table-active-bg: rgba(0, 0, 0, 0.1);--bs-table-hover-color: var(--bs-body-color);--bs-table-hover-bg: rgba(0, 0, 0, 0.075);width: 100%;margin-bottom: 1rem;vertical-align: middle!important;border-color: var(--bs-table-border-color);">
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td class="bg-secondary-subtle" colspan="2" style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;background-color: var(--bs-secondary-bg-subtle)!important;">
            <b style="box-sizing: border-box;font-weight: bolder;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">M1870. Feeding or Eating</b>
            <p style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);">Current ability to feed self meals and snacks safely. Note: This refers only to the process of
                <u style="box-sizing: border-box;">eating</u>, <u style="box-sizing: border-box;">chewing</u>, and <u style="box-sizing: border-box;">swallowing</u>, <u style="box-sizing: border-box;">not</u> <u style="box-sizing: border-box;">preparing</u> the food to be eaten.
            </p>
        </td>
    </tr>
    <tr style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: 0;">
        <td style="box-sizing: border-box;border-color: inherit;border-style: solid;border-width: var(--bs-border-width) 0;">
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 0. <b style="box-sizing: border-box;font-weight: bolder;">Able to independently feed self.</b></label>
            </div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 1. <b style="box-sizing: border-box;font-weight: bolder;">Able to feed self independently but
                        requires:</b>
                    </label><p class="ms-4" style="box-sizing: border-box;margin-top: 0;margin-bottom: 1rem;margin-left: 1.5rem!important;">
                        a. <b style="box-sizing: border-box;font-weight: bolder;">meal set-up; <u style="box-sizing: border-box;">OR</u></b><br style="box-sizing: border-box;">
                        b. <b style="box-sizing: border-box;font-weight: bolder;">intermittent assistance or supervision from another person; <u style="box-sizing: border-box;">OR</u></b><br style="box-sizing: border-box;">
                        c. <b style="box-sizing: border-box;font-weight: bolder;">a liquid, pureed, or ground meat diet.</b>
                    </p>
                </div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 2. <b style="box-sizing: border-box;font-weight: bolder;"><u style="box-sizing: border-box;">Unable</u> to feed self and must be assisted
                        or supervised throughout the meal/snack.</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 3. <b style="box-sizing: border-box;font-weight: bolder;">Able to take in nutrients orally and receives
                        supplemental nutrients through a nasogastric tube or gastrostomy.</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 4. <b style="box-sizing: border-box;font-weight: bolder;"><u style="box-sizing: border-box;">Unable</u> to take in nutrients orally and is
                        fed nutrients through a nasogastric tube or gastrostomy.</b></label></div>
            <div class="d-block" style="box-sizing: border-box;padding: .5rem .5rem;color: var(--bs-table-color-state,var(--bs-table-color-type,var(--bs-table-color)));background-color: var(--bs-table-bg);border-bottom-width: var(--bs-border-width);box-shadow: inset 0 0 0 9999px var(--bs-table-bg-state,var(--bs-table-bg-type,var(--bs-table-accent-bg)));border-width: 0 var(--bs-border-width);display: block!important;"><label class="form-check-label" style="box-sizing: border-box;display: inline-block;"> 5. <b style="box-sizing: border-box;font-weight: bolder;">Unable to take in nutrients orally or by tube
                        feeding.</b></label></div>
        </td>
    </tr>
</table>

</body>
</html>
