<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('oasis_e_recertifications', function (Blueprint $table) {
            $table->id();

            // Section A: Administrative Information
            $table->string('dopca', 30)->nullable();
            $table->string('monthAssessment', 55)->nullable();
            $table->string('dayAssessment', 55)->nullable();
            $table->string('yearAssessment', 55)->nullable();
            $table->string('TypeOfVisit', 55)->nullable();
            $table->string('OtherTypeOfVisit', 55)->nullable();
            $table->boolean('Recertification')->nullable();
            $table->boolean('Other_follow-up')->nullable();
            $table->text('M0100_explain')->nullable();
            $table->string('EpisodeTiming', 30)->nullable();

            // PATIENT CONTACTS/CAREGIVERS
            $table->boolean('Patient')->nullable();
            $table->boolean('Caregiver')->nullable();
            $table->boolean('Family_member')->nullable();
            $table->boolean('Representative')->nullable();
            $table->boolean('familyCaregiver')->nullable();
            $table->boolean('caregiver_other')->nullable();
            $table->string('caregiver_other_1', 55)->nullable();
            $table->string('patientRepresentative', 20)->nullable();
            $table->string('representativePerson', 30)->nullable();
            $table->string('representativePerson_1', 55)->nullable();
            $table->string('relationship', 30)->nullable();
            $table->string('relationship_1', 55)->nullable();
            $table->string('address')->nullable();
            $table->string('city', 30)->nullable();
            $table->string('state', 30)->nullable();
            $table->string('zip', 30)->nullable();
            $table->string('phone', 30)->nullable();
            $table->string('email', 55)->nullable();
            $table->string('patient_1', 55)->nullable();
            $table->string('patientrepresentative', 55)->nullable();
            $table->string('caregiverName', 55)->nullable();
            $table->string('relationship', 30)->nullable();
            $table->string('caregiverName_1', 55)->nullable();
            $table->text('address_1')->nullable();
            $table->string('city_1', 30)->nullable();
            $table->string('state_1', 30)->nullable();
            $table->string('zip_1', 30)->nullable();
            $table->string('phone_1', 30)->nullable();
            $table->string('email_1', 55)->nullable();
            $table->string('PaidService', 10)->nullable();
            $table->string('companyName', 55)->nullable();
            $table->string('phoneNumber', 20)->nullable();
            $table->string('contactName', 55)->nullable();
            $table->string('PRIORITY', 55)->nullable();
            $table->string('EmergencyContact', 30)->nullable();
            $table->string('EmergencyContact_1', 55)->nullable();
            $table->string('relationship', 20)->nullable();
            $table->string('relationship_1', 55)->nullable();
            $table->text('address_2')->nullable();
            $table->string('city_2', 30)->nullable();
            $table->string('state_2', 30)->nullable();
            $table->string('zip_2', 30)->nullable();
            $table->string('phone_2', 30)->nullable();
            $table->string('email_2', 55)->nullable();
            $table->string('caregiver_2', 55)->nullable();
            $table->string('relationship', 20)->nullable();
            $table->string('relationship_1', 55)->nullable();
            $table->text('address_3')->nullable();
            $table->string('city_3', 30)->nullable();
            $table->string('state_3', 30)->nullable();
            $table->string('zip_3', 30)->nullable();
            $table->string('phone_3', 30)->nullable();
            $table->string('email_3', 30)->nullable();
            $table->string('criticalSituation', 10)->nullable();
            $table->string('name_4', 55)->nullable();
            $table->string('phoneNumber_4', 20)->nullable();
            $table->string('patientLast', 30)->nullable();
            $table->string('patientFirst', 30)->nullable();
            $table->string('patientInitial', 30)->nullable();
            $table->string('pid', 30)->nullable();
            $table->string('patientName_5', 55)->nullable();
            $table->string('patientID', 30)->nullable();

            // SUPPORTIVE ASSISTANCE/CARE PREFERENCES SUMMARY
            $table->boolean('OASISassessment')->nullable();
            $table->string('IADLs', 10)->nullable();
            $table->string('IADLsIfYes', 55)->nullable();
            $table->boolean('No_assistance')->nullable();
            $table->boolean('Meals')->nullable();
            $table->boolean('ADLs_ADLs')->nullable();
            $table->boolean('Transportation')->nullable();
            $table->boolean('SupervisionSupport')->nullable();
            $table->boolean('Medications')->nullable();
            $table->boolean('Home_maintenance')->nullable();
            $table->boolean('OtherAssistance')->nullable();
            $table->string('Home_maintenance_1', 55)->nullable();
            $table->string('WillingToAssist', 15)->nullable();
            $table->text('unknowntextarea')->nullable();
            $table->string('AssistThePatient', 15)->nullable();
            $table->text('unknowntextarea_1')->nullable();
            $table->boolean('noAssistance')->nullable();
            $table->string('sundayAm', 15)->nullable();
            $table->string('mondayAm', 15)->nullable();
            $table->string('tuesdayAM', 15)->nullable();
            $table->string('wednesdayAM', 15)->nullable();
            $table->string('thursdayAM', 15)->nullable();
            $table->string('fridayAM', 15)->nullable();
            $table->string('saturdayAM', 15)->nullable();
            $table->string('sundayPm', 15)->nullable();
            $table->string('mondayPm', 15)->nullable();
            $table->string('tuesdayPm', 15)->nullable();
            $table->string('wednesdayPm', 15)->nullable();
            $table->string('thursdayPm', 15)->nullable();
            $table->string('fridayPm', 15)->nullable();
            $table->string('saturdayPm', 15)->nullable();
            $table->string('sundayNights', 15)->nullable();
            $table->string('mondayNights', 15)->nullable();
            $table->string('tuesdayNights', 15)->nullable();
            $table->string('wednesdayNights', 15)->nullable();
            $table->string('thursdayNights', 15)->nullable();
            $table->string('fridayNights', 15)->nullable();
            $table->string('saturdayNights', 15)->nullable();

            // ADVANCE DIRECTIVES
            $table->string('DirectivesOrder', 15)->nullable();
            $table->integer('OASISassessment_2', 15)->nullable();
            $table->boolean('advanceDirectives')->nullable();
            $table->boolean('livingWill')->nullable();
            $table->boolean('doCardiopulmonary')->nullable();
            $table->boolean('donotResuscitate')->nullable();
            $table->boolean('donotIntubate')->nullable();
            $table->boolean('noArtificial')->nullable();
            $table->boolean('powerofAttorney')->nullable();
            $table->string('powerofAttorney_1', 55)->nullable();
            $table->string('powerPhone', 20)->nullable();
            $table->boolean('FinancialPower')->nullable();
            $table->string('financialPowerName', 55)->nullable();
            $table->string('phonefinancialPower', 20)->nullable();
            $table->boolean('stateSpecificform')->nullable();
            $table->string('stateSpecificform_1', 55)->nullable();
            $table->boolean('copiesonFile')->nullable();
            $table->boolean('pcp')->nullable();
            $table->boolean('copiesonFile_other')->nullable();
            $table->string('copiesonFile_other_1', 55)->nullable();
            $table->text('Comments')->nullable();

            // SENSORY STATUS
            $table->boolean('patientWears')->nullable();
            $table->boolean('Contacts')->nullable();
            $table->boolean('Contacts_1')->nullable();
            $table->boolean('prosthesis_R')->nullable();
            $table->boolean('prosthesis_L')->nullable();
            $table->boolean('hearingaid_R')->nullable();
            $table->boolean('hearingaid_L')->nullable();
            $table->text('hearingaid_Other', 55)->nullable();
            $table->boolean('Eyes')->nullable();
            $table->boolean('Ears')->nullable();
            $table->boolean('Nose')->nullable();
            $table->boolean('Mouth')->nullable();
            $table->boolean('Throat')->nullable();
            $table->boolean('Sight')->nullable();
            $table->boolean('Hearing')->nullable();
            $table->boolean('Smell')->nullable();
            $table->boolean('Taste')->nullable();
            $table->boolean('Throat')->nullable();
            $table->text('activityLimitation')->nullable();
            $table->text('therapist')->nullable();

            // NEUROLOGICAL STATUS
            $table->boolean('Problem')->nullable();
            $table->text('neurologicalSystem')->nullable();
            $table->boolean('traumaticBrain')->nullable();
            $table->date('dateofInjury')->nullable();
            $table->string('type', 30)->nullable();
            $table->boolean('headaches')->nullable();
            $table->date('Lastheadaches')->nullable();
            $table->string('lastHeadachestype', 30)->nullable();
            $table->boolean('seizures')->nullable();
            $table->date('lastSeizure')->nullable();
            $table->string('lastSeizuretype', 30)->nullable();
            $table->boolean('Aphasic')->nullable();
            $table->boolean('Receptive')->nullable();
            $table->boolean('Expressive')->nullable();
            $table->boolean('Tremors')->nullable();
            $table->boolean('atRest')->nullable();
            $table->boolean('voluntaryMovement')->nullable();
            $table->boolean('Continuous')->nullable();
            $table->boolean('Spasms')->nullable();
            $table->string('Spasm', 55)->nullable();
            $table->string('dominant_side', 10)->nullable();
            $table->boolean('sideHemiplegia')->nullable();
            $table->string('Hemiplegia', 10)->nullable();
            $table->boolean('Paraplegia')->nullable();
            $table->boolean('Quadriplegia')->nullable();
            $table->string('pcafa', 10)->nullable();
            $table->text('conditionAffect')->nullable();

            // COGNITIVE STATUS
            $table->string('PatientCognitive', 25)->nullable();
            $table->string('PatientConfused', 25)->nullable();
            $table->string('PatienAnxious', 25)->nullable();
            $table->string('PatientHas', 20)->nullable();
            $table->string('psychiatricNursing', 10)->nullable();

            // PSYCHOSOCIAL
            $table->string('patientCommunicate', 10)->nullable();
            $table->string('ifnoExplain', 55)->nullable();
            $table->string('signLanguage', 55)->nullable();
            $table->text('improveCommunication')->nullable();
            $table->string('supportPatient', 10)->nullable();
            $table->text('relationship')->nullable();
            $table->string('spiritualResource', 55)->nullable();
            $table->string('phoneResource', 20)->nullable();
            $table->boolean('change')->nullable();
            $table->boolean('changeSince')->nullable();
            $table->boolean('Angry')->nullable();
            $table->boolean('Fear')->nullable();
            $table->boolean('Sadness')->nullable();
            $table->boolean('Discouraged')->nullable();
            $table->boolean('Lonely')->nullable();
            $table->boolean('Depressed')->nullable();
            $table->boolean('Helpless')->nullable();
            $table->boolean('Content')->nullable();
            $table->boolean('Happy')->nullable();
            $table->boolean('Hopeful')->nullable();
            $table->boolean('Motivated')->nullable();
            $table->boolean('contentOther')->nullable();
            $table->string('contentOther_1', 55)->nullable();
            $table->boolean('nothingReported')->nullable();
            $table->string('Sleep', 20)->nullable();
            $table->string('Rest', 20)->nullable();
            $table->string('frequencyNap', 55)->nullable();
            $table->string('hoursSlept', 10)->nullable();
            $table->string('sleptExplain', 55)->nullable();
            $table->boolean('Caregiver')->nullable();
            $table->boolean('Clinician')->nullable();
            $table->boolean('Representative')->nullable();
            $table->boolean('behaviorstoward_Others')->nullable();
            $table->string('behaviorstoward_Others_1', 55)->nullable();
            $table->string('Rest', 15)->nullable();
            $table->text('describeInappropriate')->nullable();
            $table->boolean('lackofMotivation')->nullable();
            $table->boolean('inabilitytoRecognize')->nullable();
            $table->boolean('Unrealistic')->nullable();
            $table->boolean('Denial')->nullable();
            $table->boolean('Abuse')->nullable();
            $table->boolean('Neglect')->nullable();
            $table->boolean('Exploitation')->nullable();
            $table->boolean('Verbal')->nullable();
            $table->boolean('Emotional')->nullable();
            $table->boolean('Physical')->nullable();
            $table->boolean('Financial')->nullable();
            $table->string('PotentialActual', 15)->nullable();
            $table->string('MSWreferral', 10)->nullable();
            $table->text('Otherintervention')->nullable();
            $table->string('affectFunctionalAbility', 10)->nullable();
            $table->text('psychosocialExplain')->nullable();

            // CARE PREFERENCES/PATIENT’S PERSONAL GOALS
            $table->boolean('patient')->nullable();
            $table->boolean('representative')->nullable();
            $table->string('didOther', 55)->nullable();
            $table->string('ccptihhsp', 10)->nullable();
            $table->text('preferences')->nullable();
            $table->boolean('communicationPatient')->nullable();
            $table->boolean('communicationRepresentative')->nullable();
            $table->boolean('communicationOther', 55)->nullable();
            $table->string('communicationStatus', 10)->nullable();
            $table->boolean('thePatient')->nullable();
            $table->boolean('theRepresentative')->nullable();
            $table->string('otherRepresentative', 55)->nullable();
            $table->boolean('personalGoal')->nullable();
            $table->boolean('workingOn')->nullable();
            $table->string('otherWorking', 55)->nullable();
            $table->boolean('personalGoalPatient')->nullable();
            $table->boolean('personalGoalRepresentative')->nullable();
            $table->string('otherDiscussed_1', 55)->nullable();
            $table->string('agreementStatus', 20)->nullable();
            $table->boolean('The')->nullable();
            $table->boolean('ThePatient')->nullable();
            $table->boolean('Representative')->nullable();
            $table->string('otherGoalWritten', 55)->nullable();
            $table->boolean('thestakeholders')->nullable();
            $table->boolean('patientstakeholders')->nullable();
            $table->boolean('representativestakeholders')->nullable();
            $table->string('otherGoalAgreement', 55)->nullable();
            $table->text('documentGoals')->nullable();

            // STRENGTHS/LIMITATIONS
            $table->text('involvedFamily')->nullable();
            $table->text('structuralImpairment')->nullable();
            $table->text('functionalImpairment')->nullable();
            $table->text('patientActivities')->nullable();
            $table->string('nurseSkill', 10)->nullable();
            $table->text('specificStructural')->nullable();
            $table->string('changes', 10)->nullable();
            $table->text('limitations')->nullable();

            // SAFETY MEASURES
            $table->boolean('Bleeding')->nullable();
            $table->boolean('siderailsUp')->nullable();
            $table->boolean('infectionControl')->nullable();
            $table->boolean('precautions')->nullable();
            $table->boolean('elevateHead')->nullable();
            $table->boolean('walker')->nullable();
            $table->boolean('seizurePrecautions')->nullable();
            $table->boolean('supervision')->nullable();
            $table->boolean('fallPrecautions')->nullable();
            $table->boolean('clearpathways')->nullable();
            $table->boolean('Aspiration')->nullable();
            $table->boolean('transfers')->nullable();
            $table->string('transfersOther', 55)->nullable();
            $table->string('changesPreparedness', 10)->nullable();
            $table->text('preparednessExplain')->nullable();

            // Primary Diagnosis & Other Diagnoses
            $table->string('primaryDiagnosis', 55)->nullable();
            $table->string('notAllowed', 55)->nullable();
            $table->string('otherDiagnoses', 55)->nullable();
            $table->string('allowedDiagnoses', 55)->nullable();
            $table->string('allowedDiagnoses_b', 55)->nullable();
            $table->string('allowedDiagnoses_c', 55)->nullable();
            $table->string('allowedDiagnoses_d', 55)->nullable();
            $table->string('allowedDiagnosesd', 55)->nullable();
            $table->string('allowedDiagnoses_e', 55)->nullable();
            $table->string('allowedDiagnoses_ee', 55)->nullable();
            $table->string('allowedDiagnoses_f', 55)->nullable();
            $table->string('allowedDiagnoses_ff', 55)->nullable();
            $table->string('Complete', 55)->nullable();
            $table->string('Complete_g', 55)->nullable();
            $table->string('Completeh', 55)->nullable();
            $table->string('Complete_h', 55)->nullable();
            $table->string('Completei', 55)->nullable();
            $table->string('Complete_i', 55)->nullable();
            $table->string('Completej', 55)->nullable();
            $table->string('Complete_j', 55)->nullable();
            $table->string('Completek', 55)->nullable();
            $table->string('Complete_k', 55)->nullable();
            $table->string('Completei', 55)->nullable();
            $table->string('Complete_i', 55)->nullable();
            $table->string('Completem', 55)->nullable();
            $table->string('Complete_m', 55)->nullable();
            $table->string('Completen', 55)->nullable();
            $table->string('Complete_n', 55)->nullable();
            $table->string('Completeo', 55)->nullable();
            $table->string('Complete_o', 55)->nullable();
            $table->string('Completep', 55)->nullable();
            $table->string('Complete_p', 55)->nullable();
            $table->string('Completeq', 55)->nullable();
            $table->string('Complete_q', 55)->nullable();
            $table->string('Completer', 55)->nullable();
            $table->string('Complete_r', 55)->nullable();
            $table->string('Completes', 55)->nullable();
            $table->string('Complete_s', 55)->nullable();
            $table->string('Completet', 55)->nullable();
            $table->string('Complete_t', 55)->nullable();
            $table->string('Completeu', 55)->nullable();
            $table->string('Complete_u', 55)->nullable();
            $table->string('Completv', 55)->nullable();
            $table->string('Complete_vhm', 55)->nullable();

            // Section G: Functional Status
            $table->integer('Grooming')->nullable();
            $table->integer('catdub')->nullable();
            $table->integer('Groom')->nullable();
            $table->integer('Bathing')->nullable();
            $table->integer('ToiletTransferring')->nullable();
            $table->integer('Transferring')->nullable();
            $table->integer('Ambulation')->nullable();
            $table->string('ifhha', 15)->nullable();
            $table->text('reasonforNeed')->nullable();
            $table->string('OccupationalTherapy', 15)->nullable();
            $table->string('OccupationalTherapyO', 5)->nullable();
            $table->text('Indications')->nullable();

            // ACTIVITIES PERMITTED
            $table->boolean('No_Restrictions')->nullable();
            $table->boolean('Complete_bedrest')->nullable();
            $table->boolean('Bathroomprivileges')->nullable();
            $table->boolean('tolerated')->nullable();
            $table->boolean('transfer_bedchair')->nullable();
            $table->boolean('exercisespPprescribed')->nullable();
            $table->boolean('partialWeight')->nullable();
            $table->boolean('Independent')->nullable();
            $table->boolean('Crutches')->nullable();
            $table->boolean('Cane')->nullable();
            $table->boolean('Wheelchair')->nullable();
            $table->boolean('Walker')->nullable();
            $table->text('activities_1')->nullable();
            $table->text('activities_2')->nullable();
            $table->text('commentsRegarding')->nullable();

            // FUNCTIONAL LIMITATIONS
            $table->boolean('Amputation')->nullable();
            $table->boolean('Paralysis')->nullable();
            $table->boolean('legallyBlind')->nullable();
            $table->boolean('Bowel')->nullable();
            $table->boolean('Endurance')->nullable();
            $table->boolean('Dyspnea')->nullable();
            $table->boolean('Contracture')->nullable();
            $table->boolean('Ambulation')->nullable();
            $table->string('limitationOther', 55)->nullable();
            $table->boolean('Hearing')->nullable();
            $table->boolean('Speech')->nullable();
            $table->string('hearingOther', 55)->nullable();

            // Section GG: Functional Abilities and Goals
            $table->integer('SelfCare')->nullable();
            $table->integer('code_reason')->nullable();
            $table->boolean('Eating')->nullable();
            $table->boolean('oralHygiene')->nullable();
            $table->boolean('toiletingHygiene')->nullable();

            // ADDITIONAL COMMENTS
            $table->text('additionalComment')->nullable();
            $table->integer('Mobility')->nullable();
            $table->integer('Mobility_CS')->nullable();
            $table->boolean('rollLeft')->nullable();
            $table->boolean('sitLying')->nullable();
            $table->boolean('Lying')->nullable();
            $table->boolean('Sit')->nullable();
            $table->boolean('Chair')->nullable();
            $table->boolean('Toilet')->nullable();
            $table->boolean('Walk')->nullable();
            $table->boolean('WalkFeet')->nullable();
            $table->boolean('WalkOnce')->nullable();
            $table->boolean('WalkUneven')->nullable();
            $table->boolean('Walkstep')->nullable();
            $table->boolean('WalkAbility')->nullable();
            $table->string('dpuws', 10)->nullable();
            $table->boolean('wheelTurns')->nullable();

            // MUSCULOSKELETAL
            $table->boolean('musculoskeletal_np')->nullable();
            $table->text('musculoskeletalSystem')->nullable();
            $table->boolean('FractureLocation')->nullable();
            $table->string('Fracture', 55)->nullable();
            $table->boolean('spj')->nullable();
            $table->string('Swollen', 55)->nullable();
            $table->string('Contracture', 55)->nullable();
            $table->string('contractureLocation', 55)->nullable();
            $table->string('Hand_grips', 15)->nullable();
            $table->boolean('strongL')->nullable();
            $table->boolean('strongR')->nullable();
            $table->boolean('weakR')->nullable();
            $table->boolean('weakL')->nullable();
            $table->boolean('motorChanges')->nullable();
            $table->boolean('Fine')->nullable();
            $table->boolean('Gross')->nullable();
            $table->string('Gross_1', 55)->nullable();
            $table->boolean('Weakness')->nullable();
            $table->boolean('UE')->nullable();
            $table->boolean('LE')->nullable();
            $table->string('WeaknessOther', 55)->nullable();
            $table->boolean('AtrophyYes')->nullable();
            $table->string('Atrophy', 55)->nullable();
            $table->boolean('DecreasedYes')->nullable();
            $table->string('decreasedROM', 55)->nullable();
            $table->boolean('Shuffling')->nullable();
            $table->boolean('Widebased')->nullable();
            $table->boolean('Amputations')->nullable();
            $table->boolean('BK')->nullable();
            $table->boolean('AK')->nullable();
            $table->boolean('UE')->nullable();
            $table->boolean('R')->nullable();
            $table->boolean('L')->nullable();
            $table->string('shufflingOther', 55)->nullable();
            $table->boolean('shufflingOther_yes')->nullable();
            $table->string('shufflingOther_1', 55)->nullable();
            $table->string('PatientFunctionalAbility', 10)->nullable();
            $table->text('PatientFunctionalAbilityExplain')->nullable();

            // FALL RISK ASSESSMENT
            $table->string('fallsReported', 10)->nullable();
            $table->text('describeFall')->nullable();
            $table->string('fallsReported', 10)->nullable();
            $table->text('describeFactors')->nullable();
            $table->integer('age')->nullable();
            $table->integer('diagnosisMore')->nullable();
            $table->integer('priorHistory')->nullable();
            $table->integer('Incontinence')->nullable();
            $table->integer('visualImpairment')->nullable();
            $table->integer('impairedFunctional')->nullable();
            $table->integer('Environmental')->nullable();
            $table->integer('polyPharmacy')->nullable();
            $table->integer('polyAffecting')->nullable();
            $table->integer('cognitiveImpairment')->nullable();
            $table->integer('missouriAlliance')->nullable();
            $table->text('commentsFallrisk')->nullable();

            // URINARY ELIMINATION
            $table->boolean('noUEProblem')->nullable();
            $table->text('diagnosedDisorder')->nullable();
            $table->boolean('Observed')->nullable();
            $table->boolean('Reported')->nullable();
            $table->boolean('Urgency')->nullable();
            $table->boolean('Frequency')->nullable();
            $table->boolean('Burning')->nullable();
            $table->boolean('Hesitancy')->nullable();
            $table->boolean('increasedUrination')->nullable();
            $table->boolean('decreasedUrination')->nullable();
            $table->string('UColor', 15)->nullable();
            $table->string('colorOther', 20)->nullable();
            $table->boolean('Clear')->nullable();
            $table->boolean('Cloudy')->nullable();
            $table->boolean('Sediment')->nullable();
            $table->boolean('Mucous')->nullable();
            $table->string('UOdor', 10)->nullable();
            $table->string('phiwuio', 15)->nullable();
            $table->text('otherIncontinence')->nullable();
            $table->boolean('urinaryCatheter')->nullable();
            $table->string('urinaryCatheterType', 30)->nullable();
            $table->date('dateLastChanged')->nullable();
            $table->boolean('indwellingCatheter')->nullable();
            $table->string('indwellingChange_size', 20)->nullable();
            $table->boolean('indwellingCatheter_1')->nullable();
            $table->string('indwellingInserted_size', 20)->nullable();
            $table->string('balloon', 15)->nullable();
            $table->boolean('balloonInflated')->nullable();
            $table->string('singleAnchor_ml', 20)->nullable();
            $table->boolean('balloon')->nullable();
            $table->string('secondTip_ml', 20)->nullable();
            $table->string('difficulty', 15)->nullable();
            $table->text('withdifficultyExplain')->nullable();
            $table->string('irrigationSolution', 30)->nullable();
            $table->string('Amount_ml', 30)->nullable();
            $table->string('irrigationFrequency', 30)->nullable();
            $table->string('returnsFrequency', 30)->nullable();
            $table->string('ptpw', 5)->nullable();
            $table->boolean('suprapubic')->nullable();
            $table->boolean('Urostomy')->nullable();
            $table->text('urostomyDescribe')->nullable();
            $table->boolean('OstomyPatient')->nullable();
            $table->boolean('OstomyCaregiver')->nullable();
            $table->boolean('OstomyFamily')->nullable();
            $table->boolean('OstomyNurse')->nullable();

            // BOWEL ELIMINATION
            $table->boolean('bowelElimination')->nullable();
            $table->text('GIsystem')->nullable();
            $table->boolean('Constipation')->nullable();
            $table->boolean('Diarrhea')->nullable();
            $table->boolean('Hemorrhoids')->nullable();
            $table->boolean('lasBM')->nullable();
            $table->string('lasBM_1', 30)->nullable();
            $table->boolean('bowelSounds')->nullable();
            $table->string('active', 30)->nullable();
            $table->string('absent', 30)->nullable();
            $table->string('hypoactive', 30)->nullable();
            $table->string('hyperactive', 30)->nullable();
            $table->boolean('noProblem')->nullable();
            $table->boolean('Tenderness')->nullable();
            $table->boolean('Pain')->nullable();
            $table->boolean('Distention')->nullable();
            $table->string('HardSoft', 10)->nullable();
            $table->boolean('abdominalGirth')->nullable();
            $table->string('abdominalGirth_1', 30)->nullable();
            $table->boolean('abdominalOther')->nullable();
            $table->string('abdominalOther_1', 30)->nullable();
            $table->boolean('girthOther')->nullable();
            $table->text('bowelRregimen')->nullable();
            $table->boolean('Laxative')->nullable();
            $table->boolean('Enema')->nullable();
            $table->string('enemauseFrequency', 30)->nullable();
            $table->boolean('ifInvoluntaryIncontinence')->nullable();
            $table->text('involuntaryIncontinence')->nullable();
            $table->boolean('ifIncontinenceProducts')->nullable();
            $table->text('incontinenceProducts')->nullable();
            $table->boolean('Ileostomy')->nullable();
            $table->boolean('colostomySite')->nullable();
            $table->text('Colostomy_site')->nullable();
            $table->boolean('managedPatient')->nullable();
            $table->boolean('managedCaregiver')->nullable();
            $table->boolean('managedFamily')->nullable();
            $table->boolean('managedNurse')->nullable();
            $table->boolean('ifOstomy_other')->nullable();
            $table->string('Ostomy_other', 55)->nullable();
            $table->boolean('bowelElimination_3')->nullable();
            $table->boolean('bladderElimination_4')->nullable();
            $table->string('eliminationNoYes', 5)->nullable();
            $table->text('theElimination')->nullable();

            // GENITALIA
            $table->boolean('genitalia')->nullable();
            $table->boolean('notAssessed')->nullable();
            $table->boolean('dischargeDrainage')->nullable();
            $table->string('Otherdischargedrainage', 55)->nullable();
            $table->boolean('Lesions')->nullable();
            $table->boolean('Blisters')->nullable();
            $table->boolean('Masses')->nullable();
            $table->boolean('Cysts')->nullable();
            $table->boolean('Inflammation')->nullable();
            $table->boolean('surgicalAlteration')->nullable();
            $table->string('MaleFemale', 10)->nullable();
            $table->boolean('surgicalalterationOther')->nullable();
            $table->string('surgicalalterationOther_1', 55)->nullable();
            $table->boolean('prostateProblem')->nullable();
            $table->boolean('BPH')->nullable();
            $table->boolean('TURP')->nullable();
            $table->boolean('TURP_1')->nullable();
            $table->date('prostateProblem_date')->nullable();
            $table->boolean('SelfTesticular')->nullable();
            $table->string('selftesticularFrequency', 55)->nullable();
            $table->date('lastExam')->nullable();
            $table->boolean('Menopause')->nullable();
            $table->boolean('Hysterectomy')->nullable();
            $table->date('HysterectomyDate')->nullable();
            $table->date('datelastPAP')->nullable();
            $table->string('Result', 55)->nullable();
            $table->boolean('BreastselfExam')->nullable();
            $table->string('BreastselfExam_Frequency', 55)->nullable();
            $table->date('BreastselfExam_date')->nullable();
            $table->boolean('nippleDischarge')->nullable();
            $table->boolean('nippleDischarge_R')->nullable();
            $table->date('nippleDischarge_R_date')->nullable();
            $table->boolean('nippleDischarge_L')->nullable();
            $table->date('nippleDischarge_L_date')->nullable();

            // ENDOCRINE
            $table->boolean('endocrineNoproblem')->nullable();
            $table->boolean('endocrineDiabetes')->nullable();
            $table->string('DiabetesType', 20)->nullable();
            $table->string('Otherdiabetes', 55)->nullable();
            $table->string('dateOnset', 55)->nullable();
            $table->boolean('diabeticDiet')->nullable();
            $table->boolean('oralMedication')->nullable();
            $table->boolean('injectableMedication')->nullable();
            $table->string('diabeticMedicatio', 5)->nullable();
            $table->string('diabeticMedication', 30)->nullable();
            $table->boolean('patientAdministered')->nullable();
            $table->boolean('caregiverAdministered')->nullable();
            $table->boolean('nurseAdministered')->nullable();
            $table->boolean('familyAdministered')->nullable();
            $table->boolean('Otheradministered')->nullable();
            $table->string('OtheradministeredBy', 55)->nullable();
            $table->string('ReportsSymptoms', 20)->nullable();
            $table->boolean('increasedUrination')->nullable();
            $table->boolean('increasedThirst')->nullable();
            $table->string('ReportsSymptoms', 15)->nullable();
            $table->boolean('Sweats')->nullable();
            $table->boolean('increasedHunger')->nullable();
            $table->boolean('Weak')->nullable();
            $table->boolean('Faint')->nullable();
            $table->boolean('Stupor')->nullable();
            $table->string('A1C', 55)->nullable();
            $table->boolean('patientReported')->nullable();
            $table->boolean('labSlip')->nullable();
            $table->date('labSlip_date')->nullable();
            $table->string('BS', 55)->nullable();
            $table->date('BS_date')->nullable();
            $table->string('BS_time', 15)->nullable();
            $table->boolean('FBS')->nullable();
            $table->boolean('beforeMeal')->nullable();
            $table->boolean('afterMeal')->nullable();
            $table->boolean('Random')->nullable();
            $table->boolean('HS')->nullable();
            $table->boolean('bloodSugar')->nullable();
            $table->string('bloodsugarRanges', 55)->nullable();
            $table->boolean('Patient_reported')->nullable();
            $table->boolean('Caregiver_reported')->nullable();
            $table->boolean('Family_reported')->nullable();
            $table->boolean('patientMonitor')->nullable();
            $table->boolean('caregiverMonitor')->nullable();
            $table->boolean('familyMonitor')->nullable();
            $table->boolean('nurseMonitor')->nullable();
            $table->boolean('othernurseMonitor')->nullable();
            $table->string('otherMonitor', 55)->nullable();
            $table->boolean('frequencyofMmonitoring')->nullable();
            $table->string('frequencyofMmonitoring_1', 55)->nullable();
            $table->boolean('Competency')->nullable();
            $table->string('competencyGlucometer', 55)->nullable();
            $table->boolean('diseaseManagement')->nullable();
            $table->text('diseaseManagementExplain')->nullable();
            $table->boolean('diseaseEndocrine')->nullable();
            $table->text('diseaseHematology')->nullable();

            // Section J: Health Conditions
            $table->boolean('historyof_falls')->nullable();
            $table->boolean('Unintentional')->nullable();
            $table->boolean('Multiple')->nullable();
            $table->boolean('multipleEmergency')->nullable();
            $table->boolean('declineMental')->nullable();
            $table->boolean('observedHistory')->nullable();
            $table->boolean('currentlyTaking')->nullable();
            $table->boolean('reportsExhaustion')->nullable();
            $table->boolean('currentlyReports')->nullable();
            $table->boolean('noneAbove')->nullable();

            // RISK FACTORS/HOSPITAL ADMISSION/EMERGENCY ROOM
            $table->boolean('visits')->nullable();
            $table->boolean('Discussion')->nullable();
            $table->boolean('Education')->nullable();
            $table->boolean('Training')->nullable();
            $table->boolean('literaturePatient')->nullable();
            $table->boolean('literatureRepresentative')->nullable();
            $table->boolean('literatureCaregiver')->nullable();
            $table->boolean('literaturefamilyMember')->nullable();
            $table->boolean('literatureOther')->nullable();
            $table->string('literatureOther_1', 55)->nullable();
            $table->text('factorsUnplanned')->nullable();

            // PAIN
            $table->string('patient_experiencing', 10)->nullable();
            $table->boolean('Diaphoresis')->nullable();
            $table->boolean('Grimacing')->nullable();
            $table->boolean('Guarding')->nullable();
            $table->boolean('Moaning')->nullable();
            $table->boolean('Crying')->nullable();
            $table->boolean('Irritability')->nullable();
            $table->boolean('Anger')->nullable();
            $table->boolean('Tense')->nullable();
            $table->boolean('Restlessness')->nullable();
            $table->boolean('changeSigns')->nullable();
            $table->boolean('demonstratedOther')->nullable();
            $table->string('demonstratedOther_1', 55)->nullable();
            $table->boolean('self_assessment')->nullable();
            $table->boolean('implications')->nullable();
            $table->string('implicationsOther', 55)->nullable();
            $table->string('pplicableScore', 55)->nullable();
            $table->string('assessmentUse', 55)->nullable();
            $table->string('painAssessment', 15)->nullable();
            $table->integer('Location_1')->nullable();
            $table->integer('Location_2')->nullable();
            $table->integer('Location_3')->nullable();
            $table->integer('Present_1')->nullable();
            $table->integer('Present_2')->nullable();
            $table->integer('Present_3')->nullable();
            $table->integer('pain_1')->nullable();
            $table->integer('pain_2')->nullable();
            $table->integer('pain_3')->nullable();
            $table->integer('Best_1')->nullable();
            $table->integer('Best_2')->nullable();
            $table->integer('Best_3')->nullable();
            $table->integer('aching_1')->nullable();
            $table->integer('aching_2')->nullable();
            $table->integer('aching_3')->nullable();

            // Pain Assessment IN Advanced Dementia - PAINAD
            $table->integer('Independent')->nullable();
            $table->integer('Negative')->nullable();
            $table->integer('Expression')->nullable();
            $table->integer('Language')->nullable();
            $table->integer('Consolability')->nullable();
            $table->integer('TOTAL')->nullable();
            $table->boolean('functionalCognition')->nullable();
            $table->boolean('functionalTransfers')->nullable();
            $table->boolean('Hygiene')->nullable();
            $table->boolean('functionalAmbulation')->nullable();
            $table->boolean('Dressing')->nullable();
            $table->boolean('upper')->nullable();
            $table->boolean('Undressing')->nullable();
            $table->boolean('upper')->nullable();
            $table->boolean('lower')->nullable();
            $table->boolean('Stairs')->nullable();
            $table->boolean('ascend')->nullable();
            $table->boolean('descend')->nullable();
            $table->boolean('Eating')->nullable();
            $table->boolean('Toileting')->nullable();
            $table->boolean('Appetite')->nullable();
            $table->boolean('Positional')->nullable();
            $table->boolean('positionalOther')->nullable();
            $table->string('positionalOther_1', 55)->nullable();
            $table->string('painImpact', 5)->nullable();
            $table->text('abilityExplain')->nullable();
            $table->boolean('Movement')->nullable();
            $table->boolean('Ambulation')->nullable();
            $table->boolean('Immobility')->nullable();
            $table->boolean('immobilityOther')->nullable();
            $table->string('immobilityOther_1', 55)->nullable();
            $table->string('patternPain', 5)->nullable();
            $table->text('patternExplain')->nullable();
            $table->boolean('Heat')->nullable();
            $table->boolean('Ice')->nullable();
            $table->boolean('Massage')->nullable();
            $table->boolean('Repositioning')->nullable();
            $table->boolean('Rest')->nullable();
            $table->boolean('Relaxation')->nullable();
            $table->boolean('Medication')->nullable();
            $table->boolean('Diversion')->nullable();
            $table->boolean('diversionOther')->nullable();
            $table->string('diversionOther_1', 55)->nullable();
            $table->string('breakthroughMedication', 15)->nullable();
            $table->string('painRadiate', 15)->nullable();
            $table->string('medicationsAdequate', 5)->nullable();
            $table->boolean('Analgesics')->nullable();
            $table->boolean('Corticosteroid')->nullable();
            $table->boolean('Antianxiety')->nullable();
            $table->boolean('DMARD')->nullable();
            $table->boolean('Anticonvulsant')->nullable();
            $table->boolean('Localanesthetics')->nullable();
            $table->boolean('Antidepressant')->nullable();
            $table->boolean('Narcotic')->nullable();
            $table->boolean('Antimigraine')->nullable();
            $table->boolean('NSAIDs')->nullable();
            $table->boolean('Biologic')->nullable();
            $table->boolean('Salicylate')->nullable();
            $table->text('pharmacologicalComments')->nullable();

            // CARDIOPULMONARY
            $table->boolean('heartProblem')->nullable();
            $table->text('respiratorySystem')->nullable();
            $table->text('breathSounds')->nullable();
            $table->string('rightAnterior', 55)->nullable();
            $table->string('leftAnterior', 55)->nullable();
            $table->string('posteriorRight', 55)->nullable();
            $table->string('posteriorLeft', 55)->nullable();
            $table->string('posteriorLower_right', 55)->nullable();
            $table->string('posteriorLower_left', 55)->nullable();
            $table->boolean('LaboredBbreathing')->nullable();
            $table->string('patientSmoked', 15)->nullable();
            $table->string('patientSmoked', 5)->nullable();
            $table->date('lastSmoked')->nullable();
            $table->string('SmokerFrequency', 20)->nullable();
            $table->string('vaporized', 55)->nullable();
            $table->boolean('IfOxygen')->nullable();
            $table->string('Oxygen', 20)->nullable();
            $table->boolean('IfVentilator')->nullable();
            $table->string('Ventilator', 15)->nullable();
            $table->boolean('positiveAirway')->nullable();
            $table->boolean('continuousAirway')->nullable();
            $table->boolean('bi_level')->nullable();
            $table->string('bi_level_1', 55)->nullable();
            $table->boolean('cannula')->nullable();
            $table->boolean('mask')->nullable();
            $table->boolean('trach')->nullable();
            $table->string('saturation', 55)->nullable();
            $table->string('trachSize', 55)->nullable();
            $table->boolean('managesPatient')->nullable();
            $table->boolean('managesRN')->nullable();
            $table->boolean('managesCaregiver')->nullable();
            $table->boolean('managesFamily')->nullable();
            $table->string('IntermittentTreatments', 5)->nullable();
            $table->text('treatmentsExplain')->nullable();
            $table->boolean('IfCough')->nullable();
            $table->string('Cough', 20)->nullable();
            $table->string('coughExplain', 55)->nullable();
            $table->string('breathing', 5)->nullable();
            $table->string('breathingExplain', 55)->nullable();
            $table->string('heartSounds', 15)->nullable();
            $table->boolean('IfPacemaker')->nullable();
            $table->date('heartSounds_date')->nullable();
            $table->date('heartSounds_lasetchecked')->nullable();
            $table->string('colorNailbeds', 55)->nullable();
            $table->boolean('xxtremityCramp')->nullable();
            $table->boolean('painRest')->nullable();
            $table->boolean('painDependent')->nullable();
            $table->boolean('edemaPedal')->nullable();
            $table->boolean('edemaPedal_right')->nullable();
            $table->string('edemaPedal_right', 5)->nullable();
            $table->string('CapillaryRefill_right', 10)->nullable();
            $table->boolean('EdemaPedal')->nullable();
            $table->boolean('Pedalleft')->nullable();
            $table->string('edemaPedal_left', 5)->nullable();
            $table->string('CapillaryRefill_left', 10)->nullable();
            $table->boolean('edema_1')->nullable();
            $table->boolean('edem')->nullable();
            $table->string('edemaPedal_1', 5)->nullable();
            $table->string('CapillaryRefill_1', 10)->nullable();
            $table->boolean('edema_3')->nullable();
            $table->boolean('edema_4')->nullable();
            $table->string('edemaPedal_2', 5)->nullable();
            $table->string('CapillaryRefill_2', 10)->nullable();
            $table->boolean('Pitting_1')->nullable();
            $table->boolean('Pitting_2')->nullable();
            $table->string('edemaPedal_3', 5)->nullable();
            $table->string('CapillaryRefill_3', 10)->nullable();
            $table->string('sob', 15)->nullable();
            $table->text('Respiratory')->nullable();
            $table->string('respiratoryStatus', 10)->nullable();
            $table->text('dizzyExplain')->nullable();
            $table->boolean('IfdiseaseExplain')->nullable();
            $table->text('diseaseExplain')->nullable();

            // VITAL SIGNS
            $table->string('Temperature', 55)->nullable();
            $table->string('otrat', 20)->nullable();
            $table->boolean('IfApical')->nullable();
            $table->string('Apical', 55)->nullable();
            $table->boolean('IfBrachial')->nullable();
            $table->string('Brachial', 55)->nullable();
            $table->string('PulseRI', 15)->nullable();
            $table->boolean('IfRadial')->nullable();
            $table->string('Radial', 55)->nullable();
            $table->boolean('IfCarotid')->nullable();
            $table->string('Carotid', 55)->nullable();
            $table->string('pulseOximetry', 55)->nullable();
            $table->string('afterActivity', 55)->nullable();
            $table->string('specifyActivity', 55)->nullable();
            $table->string('atRest', 55)->nullable();
            $table->string('atRest_1', 55)->nullable();
            $table->string('atRest_2', 55)->nullable();
            $table->string('atRest_3', 55)->nullable();
            $table->string('withActivity', 55)->nullable();
            $table->string('withActivity_1', 55)->nullable();
            $table->string('withActivity_2', 55)->nullable();
            $table->string('withActivity_3', 55)->nullable();
            $table->string('postActivity', 55)->nullable();
            $table->string('postActivity_1', 55)->nullable();
            $table->string('postActivity_2', 55)->nullable();
            $table->string('postActivity_3', 55)->nullable();
            $table->string('Respirations_1', 55)->nullable();
            $table->string('RespirationsRI', 15)->nullable();
            $table->boolean('apneaPeriods')->nullable();
            $table->string('apneaPeriods_sec', 55)->nullable();
            $table->string('RespirationsOR', 15)->nullable();

            // HEIGHT AND WEIGHT
            $table->string('HeightA', 55)->nullable();
            $table->string('HeightAR', 15)->nullable();
            $table->string('Weight', 55)->nullable();
            $table->string('WeightAN', 15)->nullable();
            $table->string('WeightA', 55)->nullable();
            $table->boolean('weightChange')->nullable();
            $table->string('WeightChangeGL', 10)->nullable();
            $table->string('weightChange_lb', 55)->nullable();
            $table->string('weightChange_x', 55)->nullable();
            $table->string('WeightChangeWMY', 15)->nullable();

            // NUTRITIONAL STATUS
            $table->boolean('nutritionalStatus')->nullable();
            $table->boolean('General')->nullable();
            $table->boolean('NAS')->nullable();
            $table->boolean('NPO')->nullable();
            $table->boolean('Controlled')->nullable();
            $table->boolean('Renal')->nullable();
            $table->boolean('renalOther')->nullable();
            $table->string('otherNutritional', 55)->nullable();
            $table->string('nutritionalDiet', 55)->nullable();
            $table->string('IfFluids', 15)->nullable();
            $table->string('increaseFluids', 55)->nullable();
            $table->string('restrictFluids', 55)->nullable();
            $table->string('Appetite', 10)->nullable();
            $table->boolean('Nausea')->nullable();
            $table->boolean('Vomiting')->nullable();
            $table->string('frequencyAppetite', 55)->nullable();
            $table->string('appetiteAmount', 55)->nullable();
            $table->boolean('Heartburn')->nullable();
            $table->boolean('Heartburn_1')->nullable();
            $table->string('heartburnOther', 55)->nullable();
            $table->string('FoodAllergies', 15)->nullable();
            $table->string('otherAllergies', 55)->nullable();
            $table->string('AlcoholUse', 20)->nullable();
            $table->string('dailyAmount', 55)->nullable();
            $table->boolean('Parenteral')->nullable();
            $table->boolean('feedingTube')->nullable();
            $table->boolean('Mechanically')->nullable();
            $table->boolean('Mechanically_1')->nullable();
            $table->boolean('illness')->nullable();
            $table->boolean('mealsperDay')->nullable();
            $table->boolean('milkProducts')->nullable();
            $table->boolean('liquor')->nullable();
            $table->boolean('mouthProblems')->nullable();
            $table->boolean('foodNeeded')->nullable();
            $table->boolean('eatsAlone')->nullable();
            $table->boolean('drugs')->nullable();
            $table->boolean('gained')->nullable();
            $table->boolean('notAlways')->nullable();
            $table->boolean('IfRiskinterventionExplain')->nullable();
            $table->text('riskinterventionExplain')->nullable();
            $table->boolean('IfSafetyriskExplain')->nullable();
            $table->text('safetyriskExplain')->nullable();
            $table->boolean('independentlyPlan')->nullable();
            $table->boolean('cognitively')->nullable();
            $table->boolean('prepareLight')->nullable();
            $table->boolean('unablePrepare')->nullable();

            // Section M: Skin Conditions
            $table->boolean('NAwoundCare')->nullable();
            $table->string('WoundCare', 5)->nullable();
            $table->string('woundCare_location', 55)->nullable();
            $table->boolean('IfSoiledDressing')->nullable();
            $table->string('SoiledDressing', 15)->nullable();
            $table->string('WCCaregiverName', 55)->nullable();
            $table->string('otherWoundcare', 55)->nullable();
            $table->string('Technique', 15)->nullable();
            $table->boolean('Hands_washed')->nullable();
            $table->boolean('before')->nullable();
            $table->boolean('after_dressing')->nullable();
            $table->boolean('woundCleaned')->nullable();
            $table->string('woundCleaned_Other', 55)->nullable();
            $table->boolean('wounddressingApplied')->nullable();
            $table->string('other_wounddressingApplied', 55)->nullable();
            $table->boolean('woundIrrigated')->nullable();
            $table->string('other_woundIrrigated', 55)->nullable();
            $table->boolean('dressingSecured')->nullable();
            $table->string('other_dressingSecured', 55)->nullable();
            $table->boolean('woundPacked')->nullable();
            $table->string('other_woundPacked', 55)->nullable();
            $table->boolean('dressedproperly')->nullable();
            $table->string('PatientTolerated', 5)->nullable();
            $table->text('woundComments')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('oasis_e_recertifications');
    }
};
