<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('oasis_e_recertification_section_m_s', function (Blueprint $table) {
            $table->id();

            // Section M: Skin Conditions
            $table->boolean('NAwoundCare')->nullable();
            $table->text('WoundCare', 5)->nullable();
            $table->text('woundCare_location', 55)->nullable();
            $table->boolean('IfSoiledDressing')->nullable();
            $table->text('SoiledDressing', 15)->nullable();
            $table->text('WCCaregiverName', 55)->nullable();
            $table->text('otherWoundcare', 55)->nullable();
            $table->text('Technique', 15)->nullable();
            $table->boolean('Hands_washed')->nullable();
            $table->boolean('before')->nullable();
            $table->boolean('after_dressing')->nullable();
            $table->boolean('woundCleaned')->nullable();
            $table->text('woundCleaned_Other', 55)->nullable();
            $table->boolean('wounddressingApplied')->nullable();
            $table->text('other_wounddressingApplied', 55)->nullable();
            $table->boolean('woundIrrigated')->nullable();
            $table->text('other_woundIrrigated', 55)->nullable();
            $table->boolean('dressingSecured')->nullable();
            $table->text('other_dressingSecured', 55)->nullable();
            $table->boolean('woundPacked')->nullable();
            $table->text('other_woundPacked', 55)->nullable();
            $table->boolean('dressedproperly')->nullable();
            $table->text('PatientTolerated', 5)->nullable();
            $table->text('woundComments')->nullable();
            $table->text('FrequencyOfDiabetic', 15)->nullable();
            $table->text('FrequencyOfDiabetic_1', 55)->nullable();
            $table->text('DoneBy', 15)->nullable();
            $table->text('DoneByCaregiver', 55)->nullable();
            $table->text('otherDoneBy', 55)->nullable();
            $table->text('ExamByClinician', 5)->nullable();
            $table->text('findingsExplain')->nullable();
            $table->text('PedalPulsesPresent', 15)->nullable();
            $table->text('PedalPulsesAbsent', 15)->nullable();
            $table->text('comment_PedalPulsesAbsent', 55)->nullable();
            $table->text('LossOfSenseWarm', 15)->nullable();
            $table->text('LossOfSenseCold', 15)->nullable();
            $table->text('otherCold', 55)->nullable();
            $table->text('Numbness', 10)->nullable();
            $table->text('NumbnessTingling', 10)->nullable();
            $table->text('NumbnessBurning', 10)->nullable();
            $table->text('LegHairPresent', 10)->nullable();
            $table->text('LegHairAbsent', 10)->nullable();
            $table->text('AbsentComment')->nullable();
            $table->text('integumentaryStatus', 10)->nullable();
            $table->text('woundinfectionExplain')->nullable();
            $table->text('patientAppear', 10)->nullable();
            $table->text('patientAppear_1')->nullable();
            $table->text('patientUnhealedPressureUlcer', 5)->nullable();
            $table->text('woundLesion_1', 55)->nullable();
            $table->text('woundLesion_2', 55)->nullable();
            $table->text('woundLesion_3', 55)->nullable();
            $table->text('woundLesion_4', 55)->nullable();
            $table->text('woundLesion_5', 55)->nullable();
            $table->text('Type1', 20)->nullable();
            $table->text('OtherType1')->nullable();
            $table->text('Type2', 20)->nullable();
            $table->text('OtherType2')->nullable();
            $table->text('Type3', 20)->nullable();
            $table->text('OtherType3')->nullable();
            $table->text('Type4', 20)->nullable();
            $table->text('OtherType4')->nullable();
            $table->text('Type5', 20)->nullable();
            $table->text('OtherType5')->nullable();
            $table->text('sinusTract_length', 55)->nullable();
            $table->text('sinusTract_cm', 55)->nullable();
            $table->text('sinusTractlength', 55)->nullable();
            $table->text('sinusTractcm', 55)->nullable();
            $table->text('sinusTractcm_1', 55)->nullable();
            $table->text('sinusTractcm_2', 55)->nullable();
            $table->text('sinusTractcm_3', 55)->nullable();
            $table->text('sinusTractcm_4', 55)->nullable();
            $table->text('sinusTractcm_5', 55)->nullable();
            $table->text('sinusTractcm_6', 55)->nullable();
            $table->text('Undermining', 55)->nullable();
            $table->text('Undermining_1', 55)->nullable();
            $table->text('Undermining_2', 55)->nullable();
            $table->text('Undermining_3', 55)->nullable();
            $table->text('Undermining_4', 55)->nullable();
            $table->text('Undermining_5', 55)->nullable();
            $table->text('Undermining_6', 55)->nullable();
            $table->text('Undermining_7', 55)->nullable();
            $table->text('Undermining_8', 55)->nullable();
            $table->text('Undermining_9', 55)->nullable();
            $table->text('Undermining_10', 55)->nullable();
            $table->text('Undermining_11', 55)->nullable();
            $table->text('Undermining_12', 55)->nullable();
            $table->text('Undermining_13', 55)->nullable();
            $table->text('Undermining_14', 55)->nullable();
            $table->text('Stage_1', 55)->nullable();
            $table->text('Stage1', 15)->nullable();
            $table->text('Stage_2', 55)->nullable();
            $table->text('Stage2', 15)->nullable();
            $table->text('Stage_3', 55)->nullable();
            $table->text('Stage3', 15)->nullable();
            $table->text('Stage_4', 55)->nullable();
            $table->text('Stage4', 15)->nullable();
            $table->text('Stage_5', 55)->nullable();
            $table->text('Stage5', 15)->nullable();
            $table->boolean('Skin_only')->nullable();
            $table->boolean('Fatty_tissue')->nullable();
            $table->boolean('Muscle')->nullable();
            $table->boolean('Bone')->nullable();
            $table->boolean('MuscleNecrosis')->nullable();
            $table->boolean('Bone_necrosis')->nullable();
            $table->boolean('necrosisOther')->nullable();
            $table->text('necrosisOther1')->nullable();
            $table->boolean('Skin')->nullable();
            $table->boolean('Fatty_tissue_1')->nullable();
            $table->boolean('Muscle_1')->nullable();
            $table->boolean('Bone_1')->nullable();
            $table->boolean('MuscleNecrosis_1')->nullable();
            $table->boolean('Bone_necrosis_1')->nullable();
            $table->boolean('necrosisOther_1')->nullable();
            $table->text('necrosisOther2', 55)->nullable();
            $table->boolean('Skin_1')->nullable();
            $table->boolean('Fatty_tissue_2')->nullable();
            $table->boolean('Muscle_2')->nullable();
            $table->boolean('Bone_2')->nullable();
            $table->boolean('MuscleNecrosis_2')->nullable();
            $table->boolean('Bone_necrosis_2')->nullable();
            $table->boolean('necrosisOther_2')->nullable();
            $table->text('necrosisOther5', 55)->nullable();
            $table->boolean('Skin_2')->nullable();
            $table->boolean('Fatty_tissue_3')->nullable();
            $table->boolean('Muscle_3')->nullable();
            $table->boolean('Bone_3')->nullable();
            $table->boolean('MuscleNecrosis_3')->nullable();
            $table->boolean('Bone_necrosis_3')->nullable();
            $table->boolean('necrosisOther_3')->nullable();
            $table->text('necrosisOther3', 55)->nullable();
            $table->boolean('Skin_3')->nullable();
            $table->boolean('Fatty_tissue_4')->nullable();
            $table->boolean('Muscle_4')->nullable();
            $table->boolean('Bone_4')->nullable();
            $table->boolean('MuscleNecrosis_4')->nullable();
            $table->boolean('Bone_necrosis_4')->nullable();
            $table->boolean('necrosisOther_4')->nullable();
            $table->text('necrosisOther4', 55)->nullable();
            $table->text('Odor1', 5)->nullable();
            $table->text('Odor2', 5)->nullable();
            $table->text('Odor3', 5)->nullable();
            $table->text('Odor4', 5)->nullable();
            $table->text('Odor5', 5)->nullable();
            $table->boolean('Erythema')->nullable();
            $table->boolean('Induration')->nullable();
            $table->boolean('Maceration')->nullable();
            $table->boolean('Normal')->nullable();
            $table->boolean('surroundingOther')->nullable();
            $table->text('surroundingOther1', 55)->nullable();
            $table->boolean('Erythema_1')->nullable();
            $table->boolean('Induration_1')->nullable();
            $table->boolean('Maceration_1')->nullable();
            $table->boolean('Normal_1')->nullable();
            $table->boolean('surroundingOther_1')->nullable();
            $table->text('surroundingOther2', 55)->nullable();
            $table->boolean('Erythema_2')->nullable();
            $table->boolean('Induration_2')->nullable();
            $table->boolean('Maceration_2')->nullable();
            $table->boolean('Normal_2')->nullable();
            $table->boolean('surroundingOther_2')->nullable();
            $table->text('surroundingOther3', 55)->nullable();
            $table->boolean('Erythema_3')->nullable();
            $table->boolean('Induration_3')->nullable();
            $table->boolean('Maceration_3')->nullable();
            $table->boolean('Normal_3')->nullable();
            $table->boolean('surroundingOther_5')->nullable();
            $table->text('surroundingOther6', 55)->nullable();
            $table->boolean('Erythema_6')->nullable();
            $table->boolean('Induration_6')->nullable();
            $table->boolean('Maceration_6')->nullable();
            $table->boolean('Normal_6')->nullable();
            $table->boolean('surroundingOther_3')->nullable();
            $table->text('surroundingOther4', 55)->nullable();
            $table->boolean('Erythema_4')->nullable();
            $table->boolean('Induration_4')->nullable();
            $table->boolean('Maceration_4')->nullable();
            $table->boolean('Normal_4')->nullable();
            $table->boolean('surroundingOther_4')->nullable();
            $table->text('surroundingOther5', 55)->nullable();
            $table->boolean('Slough')->nullable();
            $table->text('appearanceSlough', 55)->nullable();
            $table->boolean('Eschar')->nullable();
            $table->text('appearanceEschar', 55)->nullable();
            $table->boolean('Granulation')->nullable();
            $table->text('appearanceGranulation', 55)->nullable();
            $table->boolean('appearanceSlough11')->nullable();
            $table->text('appearanceEschar11', 55)->nullable();
            $table->boolean('IfAppearanceEschar_11')->nullable();
            $table->text('appearanceEschar_11', 55)->nullable();
            $table->boolean('appearanceGranulation11')->nullable();
            $table->text('appearanceGranulation_11', 55)->nullable();
            $table->boolean('appearanceSlough22')->nullable();
            $table->text('appearanceSlough_22', 55)->nullable();
            $table->boolean('appearanceEschar22')->nullable();
            $table->text('appearanceEschar_22', 55)->nullable();
            $table->boolean('appearanceGranulation33')->nullable();
            $table->text('appearanceGranulation_33', 55)->nullable();
            $table->boolean('appearanceSlough4')->nullable();
            $table->text('appearanceSlough_4', 55)->nullable();
            $table->boolean('appearanceEschar44')->nullable();
            $table->text('appearanceEschar_44', 55)->nullable();
            $table->boolean('appearanceGranulation44')->nullable();
            $table->text('appearanceGranulation_44', 55)->nullable();
            $table->boolean('appearanceSlough55')->nullable();
            $table->text('appearanceSlough_55', 55)->nullable();
            $table->boolean('appearanceEschar5')->nullable();
            $table->text('appearanceEschar_5', 55)->nullable();
            $table->boolean('appearanceGranulation55')->nullable();
            $table->text('appearanceGranulation_5', 55)->nullable();
            $table->text('Drainage1', 15)->nullable();
            $table->text('Drainage2', 15)->nullable();
            $table->text('Drainage3', 15)->nullable();
            $table->text('Drainage4', 15)->nullable();
            $table->text('Drainage5', 15)->nullable();
            $table->text('Color1', 20)->nullable();
            $table->text('Color2', 20)->nullable();
            $table->text('Color3', 20)->nullable();
            $table->text('Color4', 20)->nullable();
            $table->text('Color5', 20)->nullable();
            $table->text('Consistency1', 10)->nullable();
            $table->text('Consistency2', 10)->nullable();
            $table->text('Consistency3', 10)->nullable();
            $table->text('Consistency4', 10)->nullable();
            $table->text('Consistency5', 10)->nullable();
            $table->text('IncisionStatus1', 10)->nullable();
            $table->text('IncisionStatus2', 10)->nullable();
            $table->text('IncisionStatus3', 10)->nullable();
            $table->text('IncisionStatus4', 10)->nullable();
            $table->text('IncisionStatus5', 10)->nullable();
            $table->text('DialysisAccess1', 15)->nullable();
            $table->text('dialysisAccess', 55)->nullable();
            $table->text('DialysisAccess2', 15)->nullable();
            $table->text('DialysisAccess_site', 55)->nullable();
            $table->text('DialysisAccess3', 15)->nullable();
            $table->text('DialysisAccess3_site', 55)->nullable();
            $table->text('DialysisAccess4', 15)->nullable();
            $table->text('DialysisAccess4_site', 55)->nullable();
            $table->text('DialysisAccess5', 15)->nullable();
            $table->text('DialysisAccess5_site', 55)->nullable();
            $table->text('IV1', 15)->nullable();
            $table->text('IV_1', 55)->nullable();
            $table->text('lumens', 55)->nullable();
            $table->text('IV2', 15)->nullable();
            $table->text('IV2_1', 55)->nullable();
            $table->text('oflumens', 55)->nullable();
            $table->text('IV3', 15)->nullable();
            $table->text('IV3_1', 55)->nullable();
            $table->text('oflumens_1', 55)->nullable();
            $table->text('IV4', 15)->nullable();
            $table->text('IV4_1', 55)->nullable();
            $table->text('oflumens_2', 55)->nullable();
            $table->text('IV5', 15)->nullable();
            $table->text('IV5_1', 55)->nullable();
            $table->text('oflumens_3', 55)->nullable();
            $table->text('healedComments')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('oasis_e_recertification_section_m_s');
    }
};
