<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('oasis_e_recertifications', function (Blueprint $table) {
            $table->id();

            // Section A: Administrative Information
            $table->string('dopca', 30)->nullable();
            $table->string('monthAssessment', 55)->nullable();
            $table->string('dayAssessment', 55)->nullable();
            $table->string('yearAssessment', 55)->nullable();
            $table->string('TypeOfVisit', 55)->nullable();
            $table->string('OtherTypeOfVisit', 55)->nullable();
            $table->boolean('Recertification')->nullable();
            $table->boolean('Other_follow-up')->nullable();
            $table->text('M0100_explain')->nullable();
            $table->string('EpisodeTiming', 30)->nullable();

            // PATIENT CONTACTS/CAREGIVERS
            $table->boolean('Patient')->nullable();
            $table->boolean('Caregiver')->nullable();
            $table->boolean('Family_member')->nullable();
            $table->boolean('Representative')->nullable();
            $table->boolean('familyCaregiver')->nullable();
            $table->boolean('caregiver_other')->nullable();
            $table->string('caregiver_other_1', 55)->nullable();
            $table->string('patientRepresentative', 20)->nullable();
            $table->string('representativePerson', 30)->nullable();
            $table->string('representativePerson_1', 55)->nullable();
            $table->string('relationship', 30)->nullable();
            $table->string('relationship_other_1', 55)->nullable();
            $table->string('address')->nullable();
            $table->string('city', 30)->nullable();
            $table->string('state', 30)->nullable();
            $table->string('zip', 30)->nullable();
            $table->string('phone', 30)->nullable();
            $table->string('email', 55)->nullable();
            $table->string('patient_1', 55)->nullable();
            $table->string('patientrepresentative_1', 55)->nullable();
            $table->string('caregiverName', 55)->nullable();
            $table->string('relationship_1', 30)->nullable();
            $table->string('caregiverName_1', 55)->nullable();
            $table->text('address_1')->nullable();
            $table->string('city_1', 30)->nullable();
            $table->string('state_1', 30)->nullable();
            $table->string('zip_1', 30)->nullable();
            $table->string('phone_1', 30)->nullable();
            $table->string('email_1', 55)->nullable();
            $table->string('PaidService', 10)->nullable();
            $table->string('companyName', 55)->nullable();
            $table->string('phoneNumber', 20)->nullable();
            $table->string('contactName', 55)->nullable();
            $table->string('PRIORITY', 55)->nullable();
            $table->string('EmergencyContact', 30)->nullable();
            $table->string('EmergencyContact_1', 55)->nullable();
            $table->string('relationship_2', 20)->nullable();
            $table->string('relationship_2_other', 55)->nullable();
            $table->text('address_2')->nullable();
            $table->string('city_2', 30)->nullable();
            $table->string('state_2', 30)->nullable();
            $table->string('zip_2', 30)->nullable();
            $table->string('phone_2', 30)->nullable();
            $table->string('email_2', 55)->nullable();
            $table->string('caregiver_2', 55)->nullable();
            $table->string('relationship_3', 20)->nullable();
            $table->string('relationship_3_other', 55)->nullable();
            $table->text('address_3')->nullable();
            $table->string('city_3', 30)->nullable();
            $table->string('state_3', 30)->nullable();
            $table->string('zip_3', 30)->nullable();
            $table->string('phone_3', 30)->nullable();
            $table->string('email_3', 30)->nullable();
            $table->string('criticalSituation', 10)->nullable();
            $table->string('name_4', 55)->nullable();
            $table->string('phoneNumber_4', 20)->nullable();
            $table->string('patientLast', 30)->nullable();
            $table->string('patientFirst', 30)->nullable();
            $table->string('patientInitial', 30)->nullable();
            $table->string('pid', 30)->nullable();
            $table->string('patientName_5', 55)->nullable();
            $table->string('patientID', 30)->nullable();

            // SUPPORTIVE ASSISTANCE/CARE PREFERENCES SUMMARY
            $table->boolean('OASISassessment')->nullable();
            $table->string('IADLs', 10)->nullable();
            $table->string('IADLsIfYes', 55)->nullable();
            $table->boolean('No_assistance')->nullable();
            $table->boolean('Meals')->nullable();
            $table->boolean('ADLs_ADLs')->nullable();
            $table->boolean('Transportation')->nullable();
            $table->boolean('SupervisionSupport')->nullable();
            $table->boolean('Medications')->nullable();
            $table->boolean('Home_maintenance')->nullable();
            $table->boolean('OtherAssistance')->nullable();
            $table->string('Home_maintenance_1', 55)->nullable();
            $table->string('WillingToAssist', 15)->nullable();
            $table->text('unknowntextarea')->nullable();
            $table->string('AssistThePatient', 15)->nullable();
            $table->text('unknowntextarea_1')->nullable();
            $table->boolean('noAssistance')->nullable();
            $table->string('sundayAm', 15)->nullable();
            $table->string('mondayAm', 15)->nullable();
            $table->string('tuesdayAM', 15)->nullable();
            $table->string('wednesdayAM', 15)->nullable();
            $table->string('thursdayAM', 15)->nullable();
            $table->string('fridayAM', 15)->nullable();
            $table->string('saturdayAM', 15)->nullable();
            $table->string('sundayPm', 15)->nullable();
            $table->string('mondayPm', 15)->nullable();
            $table->string('tuesdayPm', 15)->nullable();
            $table->string('wednesdayPm', 15)->nullable();
            $table->string('thursdayPm', 15)->nullable();
            $table->string('fridayPm', 15)->nullable();
            $table->string('saturdayPm', 15)->nullable();
            $table->string('sundayNights', 15)->nullable();
            $table->string('mondayNights', 15)->nullable();
            $table->string('tuesdayNights', 15)->nullable();
            $table->string('wednesdayNights', 15)->nullable();
            $table->string('thursdayNights', 15)->nullable();
            $table->string('fridayNights', 15)->nullable();
            $table->string('saturdayNights', 15)->nullable();

            // ADVANCE DIRECTIVES
            $table->string('DirectivesOrder', 15)->nullable();
            $table->integer('OASISassessment_2', 15)->nullable();
            $table->boolean('advanceDirectives')->nullable();
            $table->boolean('livingWill')->nullable();
            $table->boolean('doCardiopulmonary')->nullable();
            $table->boolean('donotResuscitate')->nullable();
            $table->boolean('donotIntubate')->nullable();
            $table->boolean('noArtificial')->nullable();
            $table->boolean('powerofAttorney')->nullable();
            $table->string('powerofAttorney_1', 55)->nullable();
            $table->string('powerPhone', 20)->nullable();
            $table->boolean('FinancialPower')->nullable();
            $table->string('financialPowerName', 55)->nullable();
            $table->string('phonefinancialPower', 20)->nullable();
            $table->boolean('stateSpecificform')->nullable();
            $table->string('stateSpecificform_1', 55)->nullable();
            $table->boolean('copiesonFile')->nullable();
            $table->boolean('pcp')->nullable();
            $table->boolean('copiesonFile_other')->nullable();
            $table->string('copiesonFile_other_1', 55)->nullable();
            $table->text('Comments')->nullable();

            // SENSORY STATUS
            $table->boolean('patientWears')->nullable();
            $table->boolean('Contacts')->nullable();
            $table->boolean('Contacts_1')->nullable();
            $table->boolean('prosthesis_R')->nullable();
            $table->boolean('prosthesis_L')->nullable();
            $table->boolean('hearingaid_R')->nullable();
            $table->boolean('hearingaid_L')->nullable();
            $table->text('hearingaid_Other', 55)->nullable();
            $table->boolean('Eyes')->nullable();
            $table->boolean('Ears')->nullable();
            $table->boolean('Nose')->nullable();
            $table->boolean('Mouth')->nullable();
            $table->boolean('Throat')->nullable();
            $table->boolean('Sight')->nullable();
            $table->boolean('Hearing')->nullable();
            $table->boolean('Smell')->nullable();
            $table->boolean('Taste')->nullable();
            $table->boolean('Throat_2')->nullable();
            $table->text('activityLimitation')->nullable();
            $table->text('therapist')->nullable();

            // NEUROLOGICAL STATUS
            $table->boolean('Problem')->nullable();
            $table->text('neurologicalSystem')->nullable();
            $table->boolean('traumaticBrain')->nullable();
            $table->date('dateofInjury')->nullable();
            $table->string('type', 30)->nullable();
            $table->boolean('headaches')->nullable();
            $table->date('Lastheadaches')->nullable();
            $table->string('lastHeadachestype', 30)->nullable();
            $table->boolean('seizures')->nullable();
            $table->date('lastSeizure')->nullable();
            $table->string('lastSeizuretype', 30)->nullable();
            $table->boolean('Aphasic')->nullable();
            $table->boolean('Receptive')->nullable();
            $table->boolean('Expressive')->nullable();
            $table->boolean('Tremors')->nullable();
            $table->boolean('atRest')->nullable();
            $table->boolean('voluntaryMovement')->nullable();
            $table->boolean('Continuous')->nullable();
            $table->boolean('Spasms')->nullable();
            $table->string('Spasm', 55)->nullable();
            $table->string('dominant_side', 10)->nullable();
            $table->boolean('sideHemiplegia')->nullable();
            $table->string('Hemiplegia', 10)->nullable();
            $table->boolean('Paraplegia')->nullable();
            $table->boolean('Quadriplegia')->nullable();
            $table->string('pcafa', 10)->nullable();
            $table->text('conditionAffect')->nullable();

            // COGNITIVE STATUS
            $table->string('PatientCognitive', 25)->nullable();
            $table->string('PatientConfused', 25)->nullable();
            $table->string('PatienAnxious', 25)->nullable();
            $table->string('PatientHas', 20)->nullable();
            $table->string('psychiatricNursing', 10)->nullable();

            // PSYCHOSOCIAL
            $table->string('patientCommunicate', 10)->nullable();
            $table->string('ifnoExplain', 55)->nullable();
            $table->string('signLanguage', 55)->nullable();
            $table->text('improveCommunication')->nullable();
            $table->string('supportPatient', 10)->nullable();
            $table->text('relationship_4')->nullable();
            $table->string('spiritualResource', 55)->nullable();
            $table->string('phoneResource', 20)->nullable();
            $table->boolean('change')->nullable();
            $table->boolean('changeSince')->nullable();
            $table->boolean('Angry')->nullable();
            $table->boolean('Fear')->nullable();
            $table->boolean('Sadness')->nullable();
            $table->boolean('Discouraged')->nullable();
            $table->boolean('Lonely')->nullable();
            $table->boolean('Depressed')->nullable();
            $table->boolean('Helpless')->nullable();
            $table->boolean('Content')->nullable();
            $table->boolean('Happy')->nullable();
            $table->boolean('Hopeful')->nullable();
            $table->boolean('Motivated')->nullable();
            $table->boolean('contentOther')->nullable();
            $table->string('contentOther_1', 55)->nullable();
            $table->boolean('nothingReported')->nullable();
            $table->string('Sleep', 20)->nullable();
            $table->string('Rest', 20)->nullable();
            $table->string('frequencyNap', 55)->nullable();
            $table->string('hoursSlept', 10)->nullable();
            $table->string('sleptExplain', 55)->nullable();
            $table->boolean('Caregiver_3')->nullable();
            $table->boolean('Clinician')->nullable();
            $table->boolean('Representative_2')->nullable();
            $table->boolean('behaviorstoward_Others')->nullable();
            $table->string('behaviorstoward_Others_1', 55)->nullable();
            $table->string('Rest_2', 15)->nullable();
            $table->text('describeInappropriate')->nullable();
            $table->boolean('lackofMotivation')->nullable();
            $table->boolean('inabilitytoRecognize')->nullable();
            $table->boolean('Unrealistic')->nullable();
            $table->boolean('Denial')->nullable();
            $table->boolean('Abuse')->nullable();
            $table->boolean('Neglect')->nullable();
            $table->boolean('Exploitation')->nullable();
            $table->boolean('Verbal')->nullable();
            $table->boolean('Emotional')->nullable();
            $table->boolean('Physical')->nullable();
            $table->boolean('Financial')->nullable();
            $table->string('PotentialActual', 15)->nullable();
            $table->string('MSWreferral', 10)->nullable();
            $table->text('Otherintervention')->nullable();
            $table->string('affectFunctionalAbility', 10)->nullable();
            $table->text('psychosocialExplain')->nullable();

            // CARE PREFERENCES/PATIENT’S PERSONAL GOALS
            $table->boolean('patient_2')->nullable();
            $table->boolean('representative_3')->nullable();
            $table->string('didOther', 55)->nullable();
            $table->string('ccptihhsp', 10)->nullable();
            $table->text('preferences')->nullable();
            $table->boolean('communicationPatient')->nullable();
            $table->boolean('communicationRepresentative')->nullable();
            $table->boolean('communicationOther', 55)->nullable();
            $table->string('communicationStatus', 10)->nullable();
            $table->boolean('thePatient')->nullable();
            $table->boolean('theRepresentative')->nullable();
            $table->string('otherRepresentative', 55)->nullable();
            $table->boolean('personalGoal')->nullable();
            $table->boolean('workingOn')->nullable();
            $table->string('otherWorking', 55)->nullable();
            $table->boolean('personalGoalPatient')->nullable();
            $table->boolean('personalGoalRepresentative')->nullable();
            $table->string('otherDiscussed_1', 55)->nullable();
            $table->string('agreementStatus', 20)->nullable();
            $table->boolean('The')->nullable();
            $table->boolean('ThePatient_2')->nullable();
            $table->boolean('Representative_4')->nullable();
            $table->string('otherGoalWritten', 55)->nullable();
            $table->boolean('thestakeholders')->nullable();
            $table->boolean('patientstakeholders')->nullable();
            $table->boolean('representativestakeholders')->nullable();
            $table->string('otherGoalAgreement', 55)->nullable();
            $table->text('documentGoals')->nullable();

            // STRENGTHS/LIMITATIONS
            $table->text('involvedFamily')->nullable();
            $table->text('structuralImpairment')->nullable();
            $table->text('functionalImpairment')->nullable();
            $table->text('patientActivities')->nullable();
            $table->string('nurseSkill', 10)->nullable();
            $table->text('specificStructural')->nullable();
            $table->string('changes', 10)->nullable();
            $table->text('limitations')->nullable();

            // SAFETY MEASURES
            $table->boolean('Bleeding')->nullable();
            $table->boolean('siderailsUp')->nullable();
            $table->boolean('infectionControl')->nullable();
            $table->boolean('precautions')->nullable();
            $table->boolean('elevateHead')->nullable();
            $table->boolean('walker')->nullable();
            $table->boolean('seizurePrecautions')->nullable();
            $table->boolean('supervision')->nullable();
            $table->boolean('fallPrecautions')->nullable();
            $table->boolean('clearpathways')->nullable();
            $table->boolean('Aspiration')->nullable();
            $table->boolean('transfers')->nullable();
            $table->string('transfersOther', 55)->nullable();
            $table->string('changesPreparedness', 10)->nullable();
            $table->text('preparednessExplain')->nullable();

            // Primary Diagnosis & Other Diagnoses
            $table->string('primaryDiagnosis', 55)->nullable();
            $table->string('notAllowed', 55)->nullable();
            $table->string('otherDiagnoses', 55)->nullable();
            $table->string('allowedDiagnoses', 55)->nullable();
            $table->string('allowedDiagnoses_b', 55)->nullable();
            $table->string('allowedDiagnoses_c', 55)->nullable();
            $table->string('allowedDiagnoses_d', 55)->nullable();
            $table->string('allowedDiagnosesd', 55)->nullable();
            $table->string('allowedDiagnoses_e', 55)->nullable();
            $table->string('allowedDiagnoses_ee', 55)->nullable();
            $table->string('allowedDiagnoses_f', 55)->nullable();
            $table->string('allowedDiagnoses_ff', 55)->nullable();
            $table->string('Complete', 55)->nullable();
            $table->string('Complete_g', 55)->nullable();
            $table->string('Completeh', 55)->nullable();
            $table->string('Complete_h', 55)->nullable();
            $table->string('Completei', 55)->nullable();
            $table->string('Complete_i', 55)->nullable();
            $table->string('Completej', 55)->nullable();
            $table->string('Complete_j', 55)->nullable();
            $table->string('Completek', 55)->nullable();
            $table->string('Complete_k', 55)->nullable();
            $table->string('Completei_2', 55)->nullable();
            $table->string('Complete_i_2', 55)->nullable();
            $table->string('Completem', 55)->nullable();
            $table->string('Complete_m', 55)->nullable();
            $table->string('Completen', 55)->nullable();
            $table->string('Complete_n', 55)->nullable();
            $table->string('Completeo', 55)->nullable();
            $table->string('Complete_o', 55)->nullable();
            $table->string('Completep', 55)->nullable();
            $table->string('Complete_p', 55)->nullable();
            $table->string('Completeq', 55)->nullable();
            $table->string('Complete_q', 55)->nullable();
            $table->string('Completer', 55)->nullable();
            $table->string('Complete_r', 55)->nullable();
            $table->string('Completes', 55)->nullable();
            $table->string('Complete_s', 55)->nullable();
            $table->string('Completet', 55)->nullable();
            $table->string('Complete_t', 55)->nullable();
            $table->string('Completeu', 55)->nullable();
            $table->string('Complete_u', 55)->nullable();
            $table->string('Completv', 55)->nullable();
            $table->string('Complete_vhm', 55)->nullable();

            // Section G: Functional Status
            $table->integer('Grooming')->nullable();
            $table->integer('catdub')->nullable();
            $table->integer('Groom')->nullable();
            $table->integer('Bathing')->nullable();
            $table->integer('ToiletTransferring')->nullable();
            $table->integer('Transferring')->nullable();
            $table->integer('Ambulation')->nullable();
            $table->string('ifhha', 15)->nullable();
            $table->text('reasonforNeed')->nullable();
            $table->string('OccupationalTherapy', 15)->nullable();
            $table->string('OccupationalTherapyO', 5)->nullable();
            $table->text('Indications')->nullable();

            // ACTIVITIES PERMITTED
            $table->boolean('No_Restrictions')->nullable();
            $table->boolean('Complete_bedrest')->nullable();
            $table->boolean('Bathroomprivileges')->nullable();
            $table->boolean('tolerated')->nullable();
            $table->boolean('transfer_bedchair')->nullable();
            $table->boolean('exercisespPprescribed')->nullable();
            $table->boolean('partialWeight')->nullable();
            $table->boolean('Independent')->nullable();
            $table->boolean('Crutches')->nullable();
            $table->boolean('Cane')->nullable();
            $table->boolean('Wheelchair')->nullable();
            $table->boolean('Walker_2')->nullable();
            $table->text('activities_1')->nullable();
            $table->text('activities_2')->nullable();
            $table->text('commentsRegarding')->nullable();

            // FUNCTIONAL LIMITATIONS
            $table->boolean('Amputation')->nullable();
            $table->boolean('Paralysis')->nullable();
            $table->boolean('legallyBlind')->nullable();
            $table->boolean('Bowel')->nullable();
            $table->boolean('Endurance')->nullable();
            $table->boolean('Dyspnea')->nullable();
            $table->boolean('Contracture')->nullable();
            $table->boolean('Ambulation_2')->nullable();
            $table->string('limitationOther', 55)->nullable();
            $table->boolean('Hearing_2')->nullable();
            $table->boolean('Speech')->nullable();
            $table->string('hearingOther', 55)->nullable();

            // Section GG: Functional Abilities and Goals
            $table->integer('SelfCare')->nullable();
            $table->integer('code_reason')->nullable();
            $table->boolean('Eating')->nullable();
            $table->boolean('oralHygiene')->nullable();
            $table->boolean('toiletingHygiene')->nullable();

            // ADDITIONAL COMMENTS
            $table->text('additionalComment')->nullable();
            $table->integer('Mobility')->nullable();
            $table->integer('Mobility_CS')->nullable();
            $table->boolean('rollLeft')->nullable();
            $table->boolean('sitLying')->nullable();
            $table->boolean('Lying')->nullable();
            $table->boolean('Sit')->nullable();
            $table->boolean('Chair')->nullable();
            $table->boolean('Toilet')->nullable();
            $table->boolean('Walk')->nullable();
            $table->boolean('WalkFeet')->nullable();
            $table->boolean('WalkOnce')->nullable();
            $table->boolean('WalkUneven')->nullable();
            $table->boolean('Walkstep')->nullable();
            $table->boolean('WalkAbility')->nullable();
            $table->string('dpuws', 10)->nullable();
            $table->boolean('wheelTurns')->nullable();

            // MUSCULOSKELETAL
            $table->boolean('musculoskeletal_np')->nullable();
            $table->text('musculoskeletalSystem')->nullable();
            $table->boolean('FractureLocation')->nullable();
            $table->string('Fracture', 55)->nullable();
            $table->boolean('spj')->nullable();
            $table->string('Swollen', 55)->nullable();
            $table->string('Contracture_2', 55)->nullable();
            $table->string('contractureLocation', 55)->nullable();
            $table->string('Hand_grips', 15)->nullable();
            $table->boolean('strongL')->nullable();
            $table->boolean('strongR')->nullable();
            $table->boolean('weakR')->nullable();
            $table->boolean('weakL')->nullable();
            $table->boolean('motorChanges')->nullable();
            $table->boolean('Fine')->nullable();
            $table->boolean('Gross')->nullable();
            $table->string('Gross_1', 55)->nullable();
            $table->boolean('Weakness')->nullable();
            $table->boolean('UE')->nullable();
            $table->boolean('LE')->nullable();
            $table->string('WeaknessOther', 55)->nullable();
            $table->boolean('AtrophyYes')->nullable();
            $table->string('Atrophy', 55)->nullable();
            $table->boolean('DecreasedYes')->nullable();
            $table->string('decreasedROM', 55)->nullable();
            $table->boolean('Shuffling')->nullable();
            $table->boolean('Widebased')->nullable();
            $table->boolean('Amputations')->nullable();
            $table->boolean('BK')->nullable();
            $table->boolean('AK')->nullable();
            $table->boolean('UE_2')->nullable();
            $table->boolean('R')->nullable();
            $table->boolean('L')->nullable();
            $table->string('shufflingOther', 55)->nullable();
            $table->boolean('shufflingOther_yes')->nullable();
            $table->string('shufflingOther_1', 55)->nullable();
            $table->string('PatientFunctionalAbility', 10)->nullable();
            $table->text('PatientFunctionalAbilityExplain')->nullable();

            // FALL RISK ASSESSMENT
            $table->string('fallsReported', 10)->nullable();
            $table->text('describeFall')->nullable();
            $table->string('fallsReported_2', 10)->nullable();
            $table->text('describeFactors')->nullable();
            $table->integer('age')->nullable();
            $table->integer('diagnosisMore')->nullable();
            $table->integer('priorHistory')->nullable();
            $table->integer('Incontinence')->nullable();
            $table->integer('visualImpairment')->nullable();
            $table->integer('impairedFunctional')->nullable();
            $table->integer('Environmental')->nullable();
            $table->integer('polyPharmacy')->nullable();
            $table->integer('polyAffecting')->nullable();
            $table->integer('cognitiveImpairment')->nullable();
            $table->integer('missouriAlliance')->nullable();
            $table->text('commentsFallrisk')->nullable();

            // URINARY ELIMINATION
            $table->boolean('noUEProblem')->nullable();
            $table->text('diagnosedDisorder')->nullable();
            $table->boolean('Observed')->nullable();
            $table->boolean('Reported')->nullable();
            $table->boolean('Urgency')->nullable();
            $table->boolean('Frequency')->nullable();
            $table->boolean('Burning')->nullable();
            $table->boolean('Hesitancy')->nullable();
            $table->boolean('increasedUrination')->nullable();
            $table->boolean('decreasedUrination')->nullable();
            $table->string('UColor', 15)->nullable();
            $table->string('colorOther', 20)->nullable();
            $table->boolean('Clear')->nullable();
            $table->boolean('Cloudy')->nullable();
            $table->boolean('Sediment')->nullable();
            $table->boolean('Mucous')->nullable();
            $table->string('UOdor', 10)->nullable();
            $table->string('phiwuio', 15)->nullable();
            $table->text('otherIncontinence')->nullable();
            $table->boolean('urinaryCatheter')->nullable();
            $table->string('urinaryCatheterType', 30)->nullable();
            $table->date('dateLastChanged')->nullable();
            $table->boolean('indwellingCatheter')->nullable();
            $table->string('indwellingChange_size', 20)->nullable();
            $table->boolean('indwellingCatheter_1')->nullable();
            $table->string('indwellingInserted_size', 20)->nullable();
            $table->string('balloon', 15)->nullable();
            $table->boolean('balloonInflated')->nullable();
            $table->string('singleAnchor_ml', 20)->nullable();
            $table->boolean('balloon_2')->nullable();
            $table->string('secondTip_ml', 20)->nullable();
            $table->string('difficulty', 15)->nullable();
            $table->text('withdifficultyExplain')->nullable();
            $table->string('irrigationSolution', 30)->nullable();
            $table->string('Amount_ml', 30)->nullable();
            $table->string('irrigationFrequency', 30)->nullable();
            $table->string('returnsFrequency', 30)->nullable();
            $table->string('ptpw', 5)->nullable();
            $table->boolean('suprapubic')->nullable();
            $table->boolean('Urostomy')->nullable();
            $table->text('urostomyDescribe')->nullable();
            $table->boolean('OstomyPatient')->nullable();
            $table->boolean('OstomyCaregiver')->nullable();
            $table->boolean('OstomyFamily')->nullable();
            $table->boolean('OstomyNurse')->nullable();

            // BOWEL ELIMINATION
            $table->boolean('bowelElimination')->nullable();
            $table->text('GIsystem')->nullable();
            $table->boolean('Constipation')->nullable();
            $table->boolean('Diarrhea')->nullable();
            $table->boolean('Hemorrhoids')->nullable();
            $table->boolean('lasBM')->nullable();
            $table->string('lasBM_1', 30)->nullable();
            $table->boolean('bowelSounds')->nullable();
            $table->string('active', 30)->nullable();
            $table->string('absent', 30)->nullable();
            $table->string('hypoactive', 30)->nullable();
            $table->string('hyperactive', 30)->nullable();
            $table->boolean('noProblem')->nullable();
            $table->boolean('Tenderness')->nullable();
            $table->boolean('Pain')->nullable();
            $table->boolean('Distention')->nullable();
            $table->string('HardSoft', 10)->nullable();
            $table->boolean('abdominalGirth')->nullable();
            $table->string('abdominalGirth_1', 30)->nullable();
            $table->boolean('abdominalOther')->nullable();
            $table->string('abdominalOther_1', 30)->nullable();
            $table->boolean('girthOther')->nullable();
            $table->text('bowelRregimen')->nullable();
            $table->boolean('Laxative')->nullable();
            $table->boolean('Enema')->nullable();
            $table->string('enemauseFrequency', 30)->nullable();
            $table->boolean('ifInvoluntaryIncontinence')->nullable();
            $table->text('involuntaryIncontinence')->nullable();
            $table->boolean('ifIncontinenceProducts')->nullable();
            $table->text('incontinenceProducts')->nullable();
            $table->boolean('Ileostomy')->nullable();
            $table->boolean('colostomySite')->nullable();
            $table->text('Colostomy_site')->nullable();
            $table->boolean('managedPatient')->nullable();
            $table->boolean('managedCaregiver')->nullable();
            $table->boolean('managedFamily')->nullable();
            $table->boolean('managedNurse')->nullable();
            $table->boolean('ifOstomy_other')->nullable();
            $table->string('Ostomy_other', 55)->nullable();
            $table->boolean('bowelElimination_3')->nullable();
            $table->boolean('bladderElimination_4')->nullable();
            $table->string('eliminationNoYes', 5)->nullable();
            $table->text('theElimination')->nullable();

            // GENITALIA
            $table->boolean('genitalia')->nullable();
            $table->boolean('notAssessed')->nullable();
            $table->boolean('dischargeDrainage')->nullable();
            $table->string('Otherdischargedrainage', 55)->nullable();
            $table->boolean('Lesions')->nullable();
            $table->boolean('Blisters')->nullable();
            $table->boolean('Masses')->nullable();
            $table->boolean('Cysts')->nullable();
            $table->boolean('Inflammation')->nullable();
            $table->boolean('surgicalAlteration')->nullable();
            $table->string('MaleFemale', 10)->nullable();
            $table->boolean('surgicalalterationOther')->nullable();
            $table->string('surgicalalterationOther_1', 55)->nullable();
            $table->boolean('prostateProblem')->nullable();
            $table->boolean('BPH')->nullable();
            $table->boolean('TURP')->nullable();
            $table->boolean('TURP_1')->nullable();
            $table->date('prostateProblem_date')->nullable();
            $table->boolean('SelfTesticular')->nullable();
            $table->string('selftesticularFrequency', 55)->nullable();
            $table->date('lastExam')->nullable();
            $table->boolean('Menopause')->nullable();
            $table->boolean('Hysterectomy')->nullable();
            $table->date('HysterectomyDate')->nullable();
            $table->date('datelastPAP')->nullable();
            $table->string('Result', 55)->nullable();
            $table->boolean('BreastselfExam')->nullable();
            $table->string('BreastselfExam_Frequency', 55)->nullable();
            $table->date('BreastselfExam_date')->nullable();
            $table->boolean('nippleDischarge')->nullable();
            $table->boolean('nippleDischarge_R')->nullable();
            $table->date('nippleDischarge_R_date')->nullable();
            $table->boolean('nippleDischarge_L')->nullable();
            $table->date('nippleDischarge_L_date')->nullable();

            // ENDOCRINE
            $table->boolean('endocrineNoproblem')->nullable();
            $table->boolean('endocrineDiabetes')->nullable();
            $table->string('DiabetesType', 20)->nullable();
            $table->string('Otherdiabetes', 55)->nullable();
            $table->string('dateOnset', 55)->nullable();
            $table->boolean('diabeticDiet')->nullable();
            $table->boolean('oralMedication')->nullable();
            $table->boolean('injectableMedication')->nullable();
            $table->string('diabeticMedicatio', 5)->nullable();
            $table->string('diabeticMedication', 30)->nullable();
            $table->boolean('patientAdministered')->nullable();
            $table->boolean('caregiverAdministered')->nullable();
            $table->boolean('nurseAdministered')->nullable();
            $table->boolean('familyAdministered')->nullable();
            $table->boolean('Otheradministered')->nullable();
            $table->string('OtheradministeredBy', 55)->nullable();
            $table->string('ReportsSymptoms', 20)->nullable();
            $table->boolean('increasedUrination_2')->nullable();
            $table->boolean('increasedThirst')->nullable();
            $table->boolean('Sweats')->nullable();
            $table->boolean('increasedHunger')->nullable();
            $table->boolean('Weak')->nullable();
            $table->boolean('Faint')->nullable();
            $table->boolean('Stupor')->nullable();
            $table->string('A1C', 55)->nullable();
            $table->boolean('patientReported')->nullable();
            $table->boolean('labSlip')->nullable();
            $table->date('labSlip_date')->nullable();
            $table->string('BS', 55)->nullable();
            $table->date('BS_date')->nullable();
            $table->string('BS_time', 15)->nullable();
            $table->boolean('FBS')->nullable();
            $table->boolean('beforeMeal')->nullable();
            $table->boolean('afterMeal')->nullable();
            $table->boolean('Random')->nullable();
            $table->boolean('HS')->nullable();
            $table->boolean('bloodSugar')->nullable();
            $table->string('bloodsugarRanges', 55)->nullable();
            $table->boolean('Patient_reported')->nullable();
            $table->boolean('Caregiver_reported')->nullable();
            $table->boolean('Family_reported')->nullable();
            $table->boolean('patientMonitor')->nullable();
            $table->boolean('caregiverMonitor')->nullable();
            $table->boolean('familyMonitor')->nullable();
            $table->boolean('nurseMonitor')->nullable();
            $table->boolean('othernurseMonitor')->nullable();
            $table->string('otherMonitor', 55)->nullable();
            $table->boolean('frequencyofMmonitoring')->nullable();
            $table->string('frequencyofMmonitoring_1', 55)->nullable();
            $table->boolean('Competency')->nullable();
            $table->string('competencyGlucometer', 55)->nullable();
            $table->boolean('diseaseManagement')->nullable();
            $table->text('diseaseManagementExplain')->nullable();
            $table->boolean('diseaseEndocrine')->nullable();
            $table->text('diseaseHematology')->nullable();

            // Section J: Health Conditions
            $table->boolean('historyof_falls')->nullable();
            $table->boolean('Unintentional')->nullable();
            $table->boolean('Multiple')->nullable();
            $table->boolean('multipleEmergency')->nullable();
            $table->boolean('declineMental')->nullable();
            $table->boolean('observedHistory')->nullable();
            $table->boolean('currentlyTaking')->nullable();
            $table->boolean('reportsExhaustion')->nullable();
            $table->boolean('currentlyReports')->nullable();
            $table->boolean('noneAbove')->nullable();

            // RISK FACTORS/HOSPITAL ADMISSION/EMERGENCY ROOM
            $table->boolean('visits')->nullable();
            $table->boolean('Discussion')->nullable();
            $table->boolean('Education')->nullable();
            $table->boolean('Training')->nullable();
            $table->boolean('literaturePatient')->nullable();
            $table->boolean('literatureRepresentative')->nullable();
            $table->boolean('literatureCaregiver')->nullable();
            $table->boolean('literaturefamilyMember')->nullable();
            $table->boolean('literatureOther')->nullable();
            $table->string('literatureOther_1', 55)->nullable();
            $table->text('factorsUnplanned')->nullable();

            // PAIN
            $table->string('patient_experiencing', 10)->nullable();
            $table->boolean('Diaphoresis')->nullable();
            $table->boolean('Grimacing')->nullable();
            $table->boolean('Guarding')->nullable();
            $table->boolean('Moaning')->nullable();
            $table->boolean('Crying')->nullable();
            $table->boolean('Irritability')->nullable();
            $table->boolean('Anger')->nullable();
            $table->boolean('Tense')->nullable();
            $table->boolean('Restlessness')->nullable();
            $table->boolean('changeSigns')->nullable();
            $table->boolean('demonstratedOther')->nullable();
            $table->string('demonstratedOther_1', 55)->nullable();
            $table->boolean('self_assessment')->nullable();
            $table->boolean('implications')->nullable();
            $table->string('implicationsOther', 55)->nullable();
            $table->string('pplicableScore', 55)->nullable();
            $table->string('assessmentUse', 55)->nullable();
            $table->string('painAssessment', 15)->nullable();
            $table->integer('Location_1')->nullable();
            $table->integer('Location_2')->nullable();
            $table->integer('Location_3')->nullable();
            $table->integer('Present_1')->nullable();
            $table->integer('Present_2')->nullable();
            $table->integer('Present_3')->nullable();
            $table->integer('pain_1')->nullable();
            $table->integer('pain_2')->nullable();
            $table->integer('pain_3')->nullable();
            $table->integer('Best_1')->nullable();
            $table->integer('Best_2')->nullable();
            $table->integer('Best_3')->nullable();
            $table->integer('aching_1')->nullable();
            $table->integer('aching_2')->nullable();
            $table->integer('aching_3')->nullable();

            // Pain Assessment IN Advanced Dementia - PAINAD
            $table->integer('Independent_2')->nullable();
            $table->integer('Negative')->nullable();
            $table->integer('Expression')->nullable();
            $table->integer('Language')->nullable();
            $table->integer('Consolability')->nullable();
            $table->integer('TOTAL')->nullable();
            $table->boolean('functionalCognition')->nullable();
            $table->boolean('functionalTransfers')->nullable();
            $table->boolean('Hygiene')->nullable();
            $table->boolean('functionalAmbulation')->nullable();
            $table->boolean('Dressing')->nullable();
            $table->boolean('upper')->nullable();
            $table->boolean('Undressing')->nullable();
            $table->boolean('upper_2')->nullable();
            $table->boolean('lower')->nullable();
            $table->boolean('Stairs')->nullable();
            $table->boolean('ascend')->nullable();
            $table->boolean('descend')->nullable();
            $table->boolean('Eating_2')->nullable();
            $table->boolean('Toileting')->nullable();
            $table->boolean('Appetite')->nullable();
            $table->boolean('Positional')->nullable();
            $table->boolean('positionalOther')->nullable();
            $table->string('positionalOther_1', 55)->nullable();
            $table->string('painImpact', 5)->nullable();
            $table->text('abilityExplain')->nullable();
            $table->boolean('Movement')->nullable();
            $table->boolean('Ambulation_3')->nullable();
            $table->boolean('Immobility')->nullable();
            $table->boolean('immobilityOther')->nullable();
            $table->string('immobilityOther_1', 55)->nullable();
            $table->string('patternPain', 5)->nullable();
            $table->text('patternExplain')->nullable();
            $table->boolean('Heat')->nullable();
            $table->boolean('Ice')->nullable();
            $table->boolean('Massage')->nullable();
            $table->boolean('Repositioning')->nullable();
            $table->boolean('Rest_3')->nullable();
            $table->boolean('Relaxation')->nullable();
            $table->boolean('Medication')->nullable();
            $table->boolean('Diversion')->nullable();
            $table->boolean('diversionOther')->nullable();
            $table->string('diversionOther_1', 55)->nullable();
            $table->string('breakthroughMedication', 15)->nullable();
            $table->string('painRadiate', 15)->nullable();
            $table->string('medicationsAdequate', 5)->nullable();
            $table->boolean('Analgesics')->nullable();
            $table->boolean('Corticosteroid')->nullable();
            $table->boolean('Antianxiety')->nullable();
            $table->boolean('DMARD')->nullable();
            $table->boolean('Anticonvulsant')->nullable();
            $table->boolean('Localanesthetics')->nullable();
            $table->boolean('Antidepressant')->nullable();
            $table->boolean('Narcotic')->nullable();
            $table->boolean('Antimigraine')->nullable();
            $table->boolean('NSAIDs')->nullable();
            $table->boolean('Biologic')->nullable();
            $table->boolean('Salicylate')->nullable();
            $table->text('pharmacologicalComments')->nullable();

            // CARDIOPULMONARY
            $table->boolean('heartProblem')->nullable();
            $table->text('respiratorySystem')->nullable();
            $table->text('breathSounds')->nullable();
            $table->string('rightAnterior', 55)->nullable();
            $table->string('leftAnterior', 55)->nullable();
            $table->string('posteriorRight', 55)->nullable();
            $table->string('posteriorLeft', 55)->nullable();
            $table->string('posteriorLower_right', 55)->nullable();
            $table->string('posteriorLower_left', 55)->nullable();
            $table->boolean('LaboredBbreathing')->nullable();
            $table->string('patientSmoked', 15)->nullable();
            $table->date('lastSmoked')->nullable();
            $table->string('SmokerFrequency', 20)->nullable();
            $table->string('vaporized', 55)->nullable();
            $table->boolean('IfOxygen')->nullable();
            $table->string('Oxygen', 20)->nullable();
            $table->boolean('IfVentilator')->nullable();
            $table->string('Ventilator', 15)->nullable();
            $table->boolean('positiveAirway')->nullable();
            $table->boolean('continuousAirway')->nullable();
            $table->boolean('bi_level')->nullable();
            $table->string('bi_level_1', 55)->nullable();
            $table->boolean('cannula')->nullable();
            $table->boolean('mask')->nullable();
            $table->boolean('trach')->nullable();
            $table->string('saturation', 55)->nullable();
            $table->string('trachSize', 55)->nullable();
            $table->boolean('managesPatient')->nullable();
            $table->boolean('managesRN')->nullable();
            $table->boolean('managesCaregiver')->nullable();
            $table->boolean('managesFamily')->nullable();
            $table->string('IntermittentTreatments', 5)->nullable();
            $table->text('treatmentsExplain')->nullable();
            $table->boolean('IfCough')->nullable();
            $table->string('Cough', 20)->nullable();
            $table->string('coughExplain', 55)->nullable();
            $table->string('breathing', 5)->nullable();
            $table->string('breathingExplain', 55)->nullable();
            $table->string('heartSounds', 15)->nullable();
            $table->boolean('IfPacemaker')->nullable();
            $table->date('heartSounds_date')->nullable();
            $table->date('heartSounds_lasetchecked')->nullable();
            $table->string('colorNailbeds', 55)->nullable();
            $table->boolean('xxtremityCramp')->nullable();
            $table->boolean('painRest')->nullable();
            $table->boolean('painDependent')->nullable();
            $table->boolean('edemaPedal')->nullable();
            $table->boolean('edemaPedal_right_2')->nullable();
            $table->string('edemaPedal_right', 5)->nullable();
            $table->string('CapillaryRefill_right', 10)->nullable();
            $table->boolean('EdemaPedal_4')->nullable();
            $table->boolean('Pedalleft')->nullable();
            $table->string('edemaPedal_left', 5)->nullable();
            $table->string('CapillaryRefill_left', 10)->nullable();
            $table->boolean('edema_1')->nullable();
            $table->boolean('edem')->nullable();
            $table->string('edemaPedal_1', 5)->nullable();
            $table->string('CapillaryRefill_1', 10)->nullable();
            $table->boolean('edema_3')->nullable();
            $table->boolean('edema_4')->nullable();
            $table->string('edemaPedal_2', 5)->nullable();
            $table->string('CapillaryRefill_2', 10)->nullable();
            $table->boolean('Pitting_1')->nullable();
            $table->boolean('Pitting_2')->nullable();
            $table->string('edemaPedal_3', 5)->nullable();
            $table->string('CapillaryRefill_3', 10)->nullable();
            $table->string('sob', 15)->nullable();
            $table->text('Respiratory')->nullable();
            $table->string('respiratoryStatus', 10)->nullable();
            $table->text('dizzyExplain')->nullable();
            $table->boolean('IfdiseaseExplain')->nullable();
            $table->text('diseaseExplain')->nullable();

            // VITAL SIGNS
            $table->string('Temperature', 55)->nullable();
            $table->string('otrat', 20)->nullable();
            $table->boolean('IfApical')->nullable();
            $table->string('Apical', 55)->nullable();
            $table->boolean('IfBrachial')->nullable();
            $table->string('Brachial', 55)->nullable();
            $table->string('PulseRI', 15)->nullable();
            $table->boolean('IfRadial')->nullable();
            $table->string('Radial', 55)->nullable();
            $table->boolean('IfCarotid')->nullable();
            $table->string('Carotid', 55)->nullable();
            $table->string('pulseOximetry', 55)->nullable();
            $table->string('afterActivity', 55)->nullable();
            $table->string('specifyActivity', 55)->nullable();
            $table->string('atRest_5', 55)->nullable();
            $table->string('atRest_1', 55)->nullable();
            $table->string('atRest_2', 55)->nullable();
            $table->string('atRest_3', 55)->nullable();
            $table->string('withActivity', 55)->nullable();
            $table->string('withActivity_1', 55)->nullable();
            $table->string('withActivity_2', 55)->nullable();
            $table->string('withActivity_3', 55)->nullable();
            $table->string('postActivity', 55)->nullable();
            $table->string('postActivity_1', 55)->nullable();
            $table->string('postActivity_2', 55)->nullable();
            $table->string('postActivity_3', 55)->nullable();
            $table->string('Respirations_1', 55)->nullable();
            $table->string('RespirationsRI', 15)->nullable();
            $table->boolean('apneaPeriods')->nullable();
            $table->string('apneaPeriods_sec', 55)->nullable();
            $table->string('RespirationsOR', 15)->nullable();

            // HEIGHT AND WEIGHT
            $table->string('HeightA', 55)->nullable();
            $table->string('HeightAR', 15)->nullable();
            $table->string('Weight', 55)->nullable();
            $table->string('WeightAN', 15)->nullable();
            $table->string('WeightA', 55)->nullable();
            $table->boolean('weightChange')->nullable();
            $table->string('WeightChangeGL', 10)->nullable();
            $table->string('weightChange_lb', 55)->nullable();
            $table->string('weightChange_x', 55)->nullable();
            $table->string('WeightChangeWMY', 15)->nullable();

            // NUTRITIONAL STATUS
            $table->boolean('nutritionalStatus')->nullable();
            $table->boolean('General')->nullable();
            $table->boolean('NAS')->nullable();
            $table->boolean('NPO')->nullable();
            $table->boolean('Controlled')->nullable();
            $table->boolean('Renal')->nullable();
            $table->boolean('renalOther')->nullable();
            $table->string('otherNutritional', 55)->nullable();
            $table->string('nutritionalDiet', 55)->nullable();
            $table->string('IfFluids', 15)->nullable();
            $table->string('increaseFluids', 55)->nullable();
            $table->string('restrictFluids', 55)->nullable();
            $table->string('Appetite_2', 10)->nullable();
            $table->boolean('Nausea')->nullable();
            $table->boolean('Vomiting')->nullable();
            $table->string('frequencyAppetite', 55)->nullable();
            $table->string('appetiteAmount', 55)->nullable();
            $table->boolean('Heartburn')->nullable();
            $table->boolean('Heartburn_1')->nullable();
            $table->string('heartburnOther', 55)->nullable();
            $table->string('FoodAllergies', 15)->nullable();
            $table->string('otherAllergies', 55)->nullable();
            $table->string('AlcoholUse', 20)->nullable();
            $table->string('dailyAmount', 55)->nullable();
            $table->boolean('Parenteral')->nullable();
            $table->boolean('feedingTube')->nullable();
            $table->boolean('Mechanically')->nullable();
            $table->boolean('Mechanically_1')->nullable();
            $table->boolean('illness')->nullable();
            $table->boolean('mealsperDay')->nullable();
            $table->boolean('milkProducts')->nullable();
            $table->boolean('liquor')->nullable();
            $table->boolean('mouthProblems')->nullable();
            $table->boolean('foodNeeded')->nullable();
            $table->boolean('eatsAlone')->nullable();
            $table->boolean('drugs')->nullable();
            $table->boolean('gained')->nullable();
            $table->boolean('notAlways')->nullable();
            $table->boolean('IfRiskinterventionExplain')->nullable();
            $table->text('riskinterventionExplain')->nullable();
            $table->boolean('IfSafetyriskExplain')->nullable();
            $table->text('safetyriskExplain')->nullable();
            $table->boolean('independentlyPlan')->nullable();
            $table->boolean('cognitively')->nullable();
            $table->boolean('prepareLight')->nullable();
            $table->boolean('unablePrepare')->nullable();

            // Section M: Skin Conditions
            $table->boolean('NAwoundCare')->nullable();
            $table->string('WoundCare', 5)->nullable();
            $table->string('woundCare_location', 55)->nullable();
            $table->boolean('IfSoiledDressing')->nullable();
            $table->string('SoiledDressing', 15)->nullable();
            $table->string('WCCaregiverName', 55)->nullable();
            $table->string('otherWoundcare', 55)->nullable();
            $table->string('Technique', 15)->nullable();
            $table->boolean('Hands_washed')->nullable();
            $table->boolean('before')->nullable();
            $table->boolean('after_dressing')->nullable();
            $table->boolean('woundCleaned')->nullable();
            $table->string('woundCleaned_Other', 55)->nullable();
            $table->boolean('wounddressingApplied')->nullable();
            $table->string('other_wounddressingApplied', 55)->nullable();
            $table->boolean('woundIrrigated')->nullable();
            $table->string('other_woundIrrigated', 55)->nullable();
            $table->boolean('dressingSecured')->nullable();
            $table->string('other_dressingSecured', 55)->nullable();
            $table->boolean('woundPacked')->nullable();
            $table->string('other_woundPacked', 55)->nullable();
            $table->boolean('dressedproperly')->nullable();
            $table->string('PatientTolerated', 5)->nullable();
            $table->text('woundComments')->nullable();
            $table->string('FrequencyOfDiabetic', 15)->nullable();
            $table->string('FrequencyOfDiabetic_1', 55)->nullable();
            $table->string('DoneBy', 15)->nullable();
            $table->string('DoneByCaregiver', 55)->nullable();
            $table->string('otherDoneBy', 55)->nullable();
            $table->string('ExamByClinician', 5)->nullable();
            $table->text('findingsExplain')->nullable();
            $table->string('PedalPulsesPresent', 15)->nullable();
            $table->string('PedalPulsesAbsent', 15)->nullable();
            $table->string('comment_PedalPulsesAbsent', 55)->nullable();
            $table->string('LossOfSenseWarm', 15)->nullable();
            $table->string('LossOfSenseCold', 15)->nullable();
            $table->string('otherCold', 55)->nullable();
            $table->string('Numbness', 10)->nullable();
            $table->string('NumbnessTingling', 10)->nullable();
            $table->string('NumbnessBurning', 10)->nullable();
            $table->string('LegHairPresent', 10)->nullable();
            $table->string('LegHairAbsent', 10)->nullable();
            $table->text('AbsentComment')->nullable();
            $table->string('integumentaryStatus', 10)->nullable();
            $table->text('woundinfectionExplain')->nullable();
            $table->string('patientAppear', 10)->nullable();
            $table->text('patientAppear_1')->nullable();
            $table->string('patientUnhealedPressureUlcer', 5)->nullable();
            $table->string('woundLesion_1', 55)->nullable();
            $table->string('woundLesion_2', 55)->nullable();
            $table->string('woundLesion_3', 55)->nullable();
            $table->string('woundLesion_4', 55)->nullable();
            $table->string('woundLesion_5', 55)->nullable();
            $table->string('Type1', 20)->nullable();
            $table->text('OtherType1')->nullable();
            $table->string('Type2', 20)->nullable();
            $table->text('OtherType2')->nullable();
            $table->string('Type3', 20)->nullable();
            $table->text('OtherType3')->nullable();
            $table->string('Type4', 20)->nullable();
            $table->text('OtherType4')->nullable();
            $table->string('Type5', 20)->nullable();
            $table->text('OtherType5')->nullable();
            $table->string('sinusTract_length', 55)->nullable();
            $table->string('sinusTract_cm', 55)->nullable();
            $table->string('sinusTractlength', 55)->nullable();
            $table->string('sinusTractcm', 55)->nullable();
            $table->string('sinusTractcm_1', 55)->nullable();
            $table->string('sinusTractcm_2', 55)->nullable();
            $table->string('sinusTractcm_3', 55)->nullable();
            $table->string('sinusTractcm_4', 55)->nullable();
            $table->string('sinusTractcm_5', 55)->nullable();
            $table->string('sinusTractcm_6', 55)->nullable();
            $table->string('Undermining', 55)->nullable();
            $table->string('Undermining_1', 55)->nullable();
            $table->string('Undermining_2', 55)->nullable();
            $table->string('Undermining_3', 55)->nullable();
            $table->string('Undermining_4', 55)->nullable();
            $table->string('Undermining_5', 55)->nullable();
            $table->string('Undermining_6', 55)->nullable();
            $table->string('Undermining_7', 55)->nullable();
            $table->string('Undermining_8', 55)->nullable();
            $table->string('Undermining_9', 55)->nullable();
            $table->string('Undermining_10', 55)->nullable();
            $table->string('Undermining_11', 55)->nullable();
            $table->string('Undermining_12', 55)->nullable();
            $table->string('Undermining_13', 55)->nullable();
            $table->string('Undermining_14', 55)->nullable();
            $table->string('Stage_1', 55)->nullable();
            $table->string('Stage1', 15)->nullable();
            $table->string('Stage_2', 55)->nullable();
            $table->string('Stage2', 15)->nullable();
            $table->string('Stage_3', 55)->nullable();
            $table->string('Stage3', 15)->nullable();
            $table->string('Stage_4', 55)->nullable();
            $table->string('Stage4', 15)->nullable();
            $table->string('Stage_5', 55)->nullable();
            $table->string('Stage5', 15)->nullable();
            $table->boolean('Skin_only')->nullable();
            $table->boolean('Fatty_tissue')->nullable();
            $table->boolean('Muscle')->nullable();
            $table->boolean('Bone')->nullable();
            $table->boolean('MuscleNecrosis')->nullable();
            $table->boolean('Bone_necrosis')->nullable();
            $table->boolean('necrosisOther')->nullable();
            $table->boolean('necrosisOther1')->nullable();
            $table->boolean('Skin')->nullable();
            $table->boolean('Fatty_tissue_1')->nullable();
            $table->boolean('Muscle_1')->nullable();
            $table->boolean('Bone_1')->nullable();
            $table->boolean('MuscleNecrosis_1')->nullable();
            $table->boolean('Bone_necrosis_1')->nullable();
            $table->boolean('necrosisOther_1')->nullable();
            $table->string('necrosisOther2', 55)->nullable();
            $table->boolean('Skin_1')->nullable();
            $table->boolean('Fatty_tissue_2')->nullable();
            $table->boolean('Muscle_2')->nullable();
            $table->boolean('Bone_2')->nullable();
            $table->boolean('MuscleNecrosis_2')->nullable();
            $table->boolean('Bone_necrosis_2')->nullable();
            $table->boolean('necrosisOther_2')->nullable();
            $table->string('necrosisOther5', 55)->nullable();
            $table->boolean('Skin_2')->nullable();
            $table->boolean('Fatty_tissue_3')->nullable();
            $table->boolean('Muscle_3')->nullable();
            $table->boolean('Bone_3')->nullable();
            $table->boolean('MuscleNecrosis_3')->nullable();
            $table->boolean('Bone_necrosis_3')->nullable();
            $table->boolean('necrosisOther_3')->nullable();
            $table->string('necrosisOther3', 55)->nullable();
            $table->boolean('Skin_3')->nullable();
            $table->boolean('Fatty_tissue_4')->nullable();
            $table->boolean('Muscle_4')->nullable();
            $table->boolean('Bone_4')->nullable();
            $table->boolean('MuscleNecrosis_4')->nullable();
            $table->boolean('Bone_necrosis_4')->nullable();
            $table->boolean('necrosisOther_4')->nullable();
            $table->string('necrosisOther4', 55)->nullable();
            $table->string('Odor1', 5)->nullable();
            $table->string('Odor2', 5)->nullable();
            $table->string('Odor3', 5)->nullable();
            $table->string('Odor4', 5)->nullable();
            $table->string('Odor5', 5)->nullable();
            $table->boolean('Erythema')->nullable();
            $table->boolean('Induration')->nullable();
            $table->boolean('Maceration')->nullable();
            $table->boolean('Normal')->nullable();
            $table->boolean('surroundingOther')->nullable();
            $table->string('surroundingOther1', 55)->nullable();
            $table->boolean('Erythema_1')->nullable();
            $table->boolean('Induration_1')->nullable();
            $table->boolean('Maceration_1')->nullable();
            $table->boolean('Normal_1')->nullable();
            $table->boolean('surroundingOther_1')->nullable();
            $table->string('surroundingOther2', 55)->nullable();
            $table->boolean('Erythema_2')->nullable();
            $table->boolean('Induration_2')->nullable();
            $table->boolean('Maceration_2')->nullable();
            $table->boolean('Normal_2')->nullable();
            $table->boolean('surroundingOther_2')->nullable();
            $table->string('surroundingOther3', 55)->nullable();
            $table->boolean('Erythema_3')->nullable();
            $table->boolean('Induration_3')->nullable();
            $table->boolean('Maceration_3')->nullable();
            $table->boolean('Normal_3')->nullable();
            $table->boolean('surroundingOther_5')->nullable();
            $table->string('surroundingOther6', 55)->nullable();
            $table->boolean('Erythema_3')->nullable();
            $table->boolean('Induration_3')->nullable();
            $table->boolean('Maceration_3')->nullable();
            $table->boolean('Normal_3')->nullable();
            $table->boolean('surroundingOther_3')->nullable();
            $table->string('surroundingOther4', 55)->nullable();
            $table->boolean('Erythema_4')->nullable();
            $table->boolean('Induration_4')->nullable();
            $table->boolean('Maceration_4')->nullable();
            $table->boolean('Normal_4')->nullable();
            $table->boolean('surroundingOther_4')->nullable();
            $table->string('surroundingOther5', 55)->nullable();
            $table->boolean('Slough')->nullable();
            $table->string('appearanceSlough', 55)->nullable();
            $table->boolean('Eschar')->nullable();
            $table->string('appearanceEschar', 55)->nullable();
            $table->boolean('Granulation')->nullable();
            $table->string('appearanceGranulation', 55)->nullable();
            $table->boolean('appearanceSlough11')->nullable();
            $table->string('appearanceEschar11', 55)->nullable();
            $table->boolean('IfAppearanceEschar_11')->nullable();
            $table->string('appearanceEschar_11', 55)->nullable();
            $table->boolean('appearanceGranulation11')->nullable();
            $table->string('appearanceGranulation_11', 55)->nullable();
            $table->boolean('appearanceSlough22')->nullable();
            $table->string('appearanceSlough_22', 55)->nullable();
            $table->boolean('appearanceEschar22')->nullable();
            $table->string('appearanceEschar_22', 55)->nullable();
            $table->boolean('appearanceGranulation33')->nullable();
            $table->string('appearanceGranulation_33', 55)->nullable();
            $table->boolean('appearanceSlough4')->nullable();
            $table->string('appearanceSlough_4', 55)->nullable();
            $table->boolean('appearanceEschar44')->nullable();
            $table->string('appearanceEschar_44', 55)->nullable();
            $table->boolean('appearanceGranulation44')->nullable();
            $table->string('appearanceGranulation_44', 55)->nullable();
            $table->boolean('appearanceSlough55')->nullable();
            $table->string('appearanceSlough_55', 55)->nullable();
            $table->boolean('appearanceEschar5')->nullable();
            $table->string('appearanceEschar_5', 55)->nullable();
            $table->boolean('appearanceGranulation55')->nullable();
            $table->string('appearanceGranulation_5', 55)->nullable();
            $table->string('Drainage1', 15)->nullable();
            $table->string('Drainage2', 15)->nullable();
            $table->string('Drainage3', 15)->nullable();
            $table->string('Drainage4', 15)->nullable();
            $table->string('Drainage5', 15)->nullable();
            $table->string('Color1', 20)->nullable();
            $table->string('Color2', 20)->nullable();
            $table->string('Color3', 20)->nullable();
            $table->string('Color4', 20)->nullable();
            $table->string('Color5', 20)->nullable();
            $table->string('Consistency1', 10)->nullable();
            $table->string('Consistency2', 10)->nullable();
            $table->string('Consistency3', 10)->nullable();
            $table->string('Consistency4', 10)->nullable();
            $table->string('Consistency5', 10)->nullable();
            $table->string('IncisionStatus1', 10)->nullable();
            $table->string('IncisionStatus2', 10)->nullable();
            $table->string('IncisionStatus3', 10)->nullable();
            $table->string('IncisionStatus4', 10)->nullable();
            $table->string('IncisionStatus5', 10)->nullable();
            $table->string('DialysisAccess1', 15)->nullable();
            $table->string('dialysisAccess', 55)->nullable();
            $table->string('DialysisAccess2', 15)->nullable();
            $table->string('DialysisAccess_site', 55)->nullable();
            $table->string('DialysisAccess3', 15)->nullable();
            $table->string('DialysisAccess3_site', 55)->nullable();
            $table->string('DialysisAccess4', 15)->nullable();
            $table->string('DialysisAccess4_site', 55)->nullable();
            $table->string('DialysisAccess5', 15)->nullable();
            $table->string('DialysisAccess5_site', 55)->nullable();
            $table->string('IV1', 15)->nullable();
            $table->string('IV_1', 55)->nullable();
            $table->string('lumens', 55)->nullable();
            $table->string('IV2', 15)->nullable();
            $table->string('IV2_1', 55)->nullable();
            $table->string('oflumens', 55)->nullable();
            $table->string('IV3', 15)->nullable();
            $table->string('IV3_1', 55)->nullable();
            $table->string('oflumens_1', 55)->nullable();
            $table->string('IV4', 15)->nullable();
            $table->string('IV4_1', 55)->nullable();
            $table->string('oflumens_2', 55)->nullable();
            $table->string('IV5', 15)->nullable();
            $table->string('IV5_1', 55)->nullable();
            $table->string('oflumens_3', 55)->nullable();
            $table->text('healedComments')->nullable();

            // MEDICATIONS
            $table->boolean('drugRegimen')->nullable();
            $table->date('drugRegimenDate')->nullable();
            $table->string('DrugRegimen', 20)->nullable();
            $table->boolean('Potential')->nullable();
            $table->boolean('drugReactions')->nullable();
            $table->boolean('Ineffective')->nullable();
            $table->boolean('Significant')->nullable();
            $table->boolean('significantDrug')->nullable();
            $table->boolean('Duplicate')->nullable();
            $table->boolean('Non-compliance')->nullable();
            $table->boolean('highRisk')->nullable();
            $table->text('highriskcomment')->nullable();
            $table->boolean('medicationAllergies')->nullable();
            $table->boolean('Aspirin')->nullable();
            $table->boolean('Penicillin')->nullable();
            $table->boolean('Sulfa')->nullable();
            $table->boolean('medicationallergiesOther')->nullable();
            $table->string('medicationallergiesOther_1', 55)->nullable();
            $table->string('Psychotropic', 5)->nullable();
            $table->string('FinancialAbility', 5)->nullable();
            $table->boolean('FinancialAbility_1')->nullable();
            $table->string('MSWreferral', 5)->nullable();
            $table->text('MSWreferralComment')->nullable();
            $table->string('problemsAdministering', 5)->nullable();
            $table->text('administeringComments')->nullable();

            // INFUSION
            $table->boolean('infusion')->nullable();
            $table->string('patientIV', 5)->nullable();
            $table->string('patient_IV', 55)->nullable();
            $table->string('numberSite', 55)->nullable();
            $table->string('siteLocations', 55)->nullable();
            $table->integer('lumen', 55)->nullable();
            $table->date('insertionDate')->nullable();
            $table->string('flushSolution', 55)->nullable();
            $table->string('LumenPatent', 5)->nullable();
            $table->string('LumenpatentComments', 55)->nullable();
            $table->boolean('notFlushed')->nullable();
            $table->string('injectionCap', 55)->nullable();
            $table->string('DressingChange', 5)->nullable();
            $table->string('changeFrequency', 55)->nullable();
            $table->boolean('flushed')->nullable();
            $table->boolean('Sterile')->nullable();
            $table->boolean('Clean')->nullable();
            $table->boolean('performedPatient')->nullable();
            $table->boolean('performedNurse')->nullable();
            $table->boolean('performedCaregiver')->nullable();
            $table->boolean('performedFamily')->nullable();
            $table->boolean('performedOther')->nullable();
            $table->string('performedOther_1', 55)->nullable();
            $table->string('skinCondition', 55)->nullable();
            $table->string('infusionSolution', 55)->nullable();
            $table->boolean('pumpType')->nullable();
            $table->string('pumpType_1', 55)->nullable();
            $table->boolean('administeredbyPatient')->nullable();
            $table->boolean('administeredbyNurse')->nullable();
            $table->boolean('administeredbyCaregiver')->nullable();
            $table->boolean('administeredbyFamily')->nullable();
            $table->boolean('administeredbyOther')->nullable();
            $table->string('administeredby_Other', 55)->nullable();
            $table->string('intravenous', 55)->nullable();
            $table->string('InfusionProvided', 5)->nullable();
            $table->string('infusion_Provided', 55)->nullable();

            // IMMUNIZATIONS
            $table->boolean('InfluenzaFlu')->nullable();
            $table->string('Influenza', 5)->nullable();
            $table->boolean('accordingPneumonia')->nullable();
            $table->boolean('accordingTetanus')->nullable();
            $table->boolean('accordingShingles')->nullable();
            $table->boolean('accordingHepatitis')->nullable();
            $table->boolean('otherHepatitis')->nullable();
            $table->string('immunizationGuidelines', 55)->nullable();
            $table->string('Needs', 55)->nullable();
            $table->boolean('Vaccination')->nullable();
            $table->boolean('Vaccination_1')->nullable();
            $table->string('vaccination_booster', 5)->nullable();
            $table->text('personalPreferences')->nullable();

            // REFUSED CARES
            $table->boolean('refusedPatient')->nullable();
            $table->boolean('refusedRepresentative')->nullable();
            $table->boolean('refusedOther')->nullable();
            $table->string('refusedOther1', 55)->nullable();
            $table->boolean('refuseCare')->nullable();
            $table->boolean('refuseService')->nullable();
            $table->string('ServiceYesNo', 5)->nullable();
            $table->text('serviceExplain')->nullable();
            $table->boolean('theCare')->nullable();
            $table->boolean('theServices')->nullable();
            $table->string('ServiceYesNo_1', 5)->nullable();
            $table->text('thecareExplain')->nullable();

            // PATIENT/CAREGIVER/REPRESENTATIVE/FAMILY EDUCATION AND TRAINING FOR CARE PLANNING
            $table->string('WoundCare', 5)->nullable();
            $table->boolean('woundCarePatient')->nullable();
            $table->boolean('woundCareCaregiver')->nullable();
            $table->boolean('woundCareRepresentative')->nullable();
            $table->boolean('woundCareFamily')->nullable();
            $table->boolean('diabeticFoot')->nullable();
            $table->boolean('diabeticCare')->nullable();
            $table->string('Diabetic', 5)->nullable();
            $table->boolean('diabeticPatient')->nullable();
            $table->boolean('diabeticCaregiver')->nullable();
            $table->boolean('diabeticRepresentative')->nullable();
            $table->boolean('diabeticFamily')->nullable();
            $table->string('InsulinAdministration', 5)->nullable();
            $table->boolean('insulinPatient')->nullable();
            $table->boolean('insulinCaregiver')->nullable();
            $table->boolean('insulinRepresentative')->nullable();
            $table->boolean('insulinFamily')->nullable();
            $table->string('GlucometerUse', 5)->nullable();
            $table->boolean('glucometer')->nullable();
            $table->boolean('glucometerPatient')->nullable();
            $table->boolean('glucometerRepresentative')->nullable();
            $table->boolean('glucometerFamily')->nullable();
            $table->string('NutritionalManagement', 5)->nullable();
            $table->boolean('nutritionalPatient')->nullable();
            $table->boolean('nutritionalCaregiver')->nullable();
            $table->boolean('nutritionalRepresentative')->nullable();
            $table->boolean('nutritionalFamily')->nullable();
            $table->boolean('Oral')->nullable();
            $table->boolean('Injected')->nullable();
            $table->boolean('Infused')->nullable();
            $table->boolean('Inhaled')->nullable();
            $table->boolean('Topical')->nullable();
            $table->string('MedicationAdministration', 5)->nullable();
            $table->boolean('MedicationAdministration_Patient')->nullable();
            $table->boolean('MedicationAdministration_Caregiver')->nullable();
            $table->boolean('MedicationAdministration_Representative')->nullable();
            $table->boolean('MedicationAdministration_Family')->nullable();
            $table->string('PainManagement', 5)->nullable();
            $table->boolean('painManagement_Patient')->nullable();
            $table->boolean('painManagement_Caregiver')->nullable();
            $table->boolean('painManagement_Representative')->nullable();
            $table->boolean('painManagement_Family')->nullable();
            $table->string('OxygenUse', 5)->nullable();
            $table->boolean('oxygenPatient')->nullable();
            $table->boolean('oxygenCaregiver')->nullable();
            $table->boolean('oxygenRepresentative')->nullable();
            $table->boolean('oxygenFamily')->nullable();
            $table->string('medicalDevices', 5)->nullable();
            $table->boolean('medicalPatient')->nullable();
            $table->boolean('medicalCaregiver')->nullable();
            $table->boolean('medicalRepresentative')->nullable();
            $table->boolean('medicalFamily')->nullable();
            $table->string('PressureReduction', 5)->nullable();
            $table->boolean('pressurePatient')->nullable();
            $table->boolean('pressureCaregiver')->nullable();
            $table->boolean('pressureRepresentative')->nullable();
            $table->boolean('pressureFamily')->nullable();
            $table->string('CatheterCare', 5)->nullable();
            $table->boolean('catheterPatient')->nullable();
            $table->boolean('catheterCaregiver')->nullable();
            $table->boolean('catheterRepresentative')->nullable();
            $table->boolean('catheterFamily')->nullable();
            $table->string('TrachCare', 5)->nullable();
            $table->boolean('trachPatient')->nullable();
            $table->boolean('trachCaregiver')->nullable();
            $table->boolean('trachRepresentative')->nullable();
            $table->boolean('trachFamily')->nullable();
            $table->string('OstomyCare', 5)->nullable();
            $table->boolean('ostomyPatient')->nullable();
            $table->boolean('ostomyCaregiver')->nullable();
            $table->boolean('ostomyRepresentative')->nullable();
            $table->boolean('ostomyFamily')->nullable();
            $table->string('PreparednessPlan', 5)->nullable();
            $table->boolean('emergencyPatient')->nullable();
            $table->boolean('emergencyCaregiver')->nullable();
            $table->boolean('emergencyRepresentative')->nullable();
            $table->boolean('emergencyFamily')->nullable();
            $table->string('InfectionControl', 5)->nullable();
            $table->boolean('infectioncontrolPatient')->nullable();
            $table->boolean('infectioncontrolCaregiver')->nullable();
            $table->boolean('infectioncontrolRepresentative')->nullable();
            $table->boolean('infectioncontrolFamily')->nullable();
            $table->string('ReportToAgency', 5)->nullable();
            $table->boolean('agencyPatient')->nullable();
            $table->boolean('agencyCaregiver')->nullable();
            $table->boolean('agencyRepresentative')->nullable();
            $table->boolean('agencyFamily')->nullable();
            $table->string('PatientRights', 5)->nullable();
            $table->boolean('rightsPatient')->nullable();
            $table->boolean('rightsCaregiver')->nullable();
            $table->boolean('rightsRepresentative')->nullable();
            $table->boolean('rightsFamily')->nullable();
            $table->text('rightsComments')->nullable();
            $table->boolean('methodEducate')->nullable();
            $table->boolean('methodTrain')->nullable();
            $table->boolean('methodPatient')->nullable();
            $table->boolean('methodCaregiver')->nullable();
            $table->boolean('methodRepresentative')->nullable();
            $table->boolean('methodFamily')->nullable();
            $table->boolean('methodusedPatient')->nullable();
            $table->boolean('methodusedCaregiver')->nullable();
            $table->boolean('methodusedRepresentative')->nullable();
            $table->boolean('methodusedFamilyeducated')->nullable();
            $table->string('methodusedFamilyeducated_other', 55)->nullable();
            $table->boolean('teachPatient')->nullable();
            $table->boolean('teachCaregiver')->nullable();
            $table->boolean('teachRepresentative')->nullable();
            $table->boolean('teachFamily')->nullable();
            $table->boolean('teachEducation')->nullable();
            $table->boolean('teachTraining')->nullable();
            $table->boolean('usedteachPatient')->nullable();
            $table->boolean('usedteachCaregiver')->nullable();
            $table->boolean('usedteachRepresentative')->nullable();
            $table->boolean('usedteachFamily')->nullable();
            $table->string('actionPlan', 5)->nullable();

            // NURSING INTERVENTIONS/INSTRUCTIONS
            $table->boolean('skilledObservation')->nullable();
            $table->boolean('foleyCare')->nullable();
            $table->boolean('Wound_care')->nullable();
            $table->boolean('Wound_dressing')->nullable();
            $table->boolean('Pressure_ulcer')->nullable();
            $table->boolean('Venipuncture')->nullable();
            $table->boolean('ngchange')->nullable();
            $table->boolean('NG_tube')->nullable();
            $table->boolean('G_tube')->nullable();
            $table->boolean('Adminofvitamin')->nullable();
            $table->boolean('Prep')->nullable();
            $table->boolean('adminInsulin')->nullable();
            $table->boolean('Teach_admin')->nullable();
            $table->boolean('admin_teach')->nullable();
            $table->boolean('ivs')->nullable();
            $table->boolean('Clysis')->nullable();
            $table->boolean('Teach_ostomy')->nullable();
            $table->boolean('conduit_care')->nullable();
            $table->boolean('Teaching')->nullable();
            $table->boolean('tube_feedings')->nullable();
            $table->boolean('teaching_1')->nullable();
            $table->boolean('careofTrach')->nullable();
            $table->boolean('terminally')->nullable();
            $table->boolean('IM_injection')->nullable();
            $table->boolean('SQ_injection')->nullable();
            $table->boolean('Psych_intervention')->nullable();
            $table->boolean('SS_infection')->nullable();
            $table->boolean('Diabetic_observation')->nullable();
            $table->boolean('diabetic_care')->nullable();
            $table->boolean('Observe')->nullable();
            $table->boolean('Teach_medication')->nullable();
            $table->boolean('effects')->nullable();
            $table->boolean('side_effects')->nullable();
            $table->boolean('Physiology_Disease')->nullable();
            $table->boolean('Diet_teaching')->nullable();
            $table->boolean('Safety_factors')->nullable();
            $table->boolean('Prenatal_assessment')->nullable();
            $table->boolean('Post_partum')->nullable();
            $table->boolean('Teachcareof')->nullable();
            $table->boolean('infant')->nullable();
            $table->boolean('child')->nullable();
            $table->boolean('Pain_management')->nullable();
            $table->boolean('Fall_safety')->nullable();
            $table->boolean('Fall_safetyOther')->nullable();
            $table->text('Fall_safetyOtherExplain')->nullable();
            $table->string('SUPERVISORY_VISIT', 5)->nullable();
            $table->string('SUPERVISORY_VISIT_SU', 5)->nullable();
            $table->string('CARE_PLAN_UPDATED', 5)->nullable();
            $table->string('CARE_PLAN_FOLLOWED', 5)->nullable();
            $table->text('CARE_PLAN_FOLLOWED_1')->nullable();
            $table->string('STAFF', 15)->nullable();
            $table->boolean('AIDE')->nullable();
            $table->boolean('LPN_LVN')->nullable();
            $table->string('nextScheduled', 55)->nullable();
            $table->string('PFR_SATISFIED', 20)->nullable();
            $table->text('IScomment')->nullable();
            $table->text('OBSERVATIONcomment')->nullable();
            $table->text('EDUCATIONcomment')->nullable();

            // RECERTIFICATION SUMMARY
            $table->string('CONFINED_TO_HOME', 5)->nullable();
            $table->boolean('adaptiveDevice')->nullable();
            $table->boolean('crutches')->nullable();
            $table->boolean('canes')->nullable();
            $table->boolean('walker_3')->nullable();
            $table->boolean('wheelchair')->nullable();
            $table->boolean('manual')->nullable();
            $table->boolean('motorized')->nullable();
            $table->boolean('prosthetic')->nullable();
            $table->boolean('scooter')->nullable();
            $table->boolean('helper')->nullable();
            $table->boolean('injuryOther')->nullable();
            $table->string('injuryOther_1', 55)->nullable();
            $table->boolean('specialTransportation')->nullable();
            $table->string('special_Transportation', 55)->nullable();
            $table->boolean('hysicalAssist')->nullable();
            $table->string('hysicalAssist_1', 55)->nullable();
            $table->boolean('medicallyContraindicated')->nullable();
            $table->string('edicallyContraindicated_other', 55)->nullable();
            $table->boolean('normalInability')->nullable();
            $table->text('ormalInabilityComment')->nullable();
            $table->boolean('leavingHome')->nullable();
            $table->text('leavingHomeComment')->nullable();
            $table->boolean('desiredFunctional')->nullable();
            $table->text('desiredFunctionalComment')->nullable();
            $table->boolean('functionaltaks')->nullable();
            $table->text('functionaltaksComment')->nullable();
            $table->boolean('expresses')->nullable();
            $table->text('expressesComment')->nullable();

            // SUMMARY CHECKLIST
            $table->integer('CarePlan')->nullable();
            $table->boolean('CareRevised')->nullable();
            $table->boolean('Care')->nullable();
            $table->boolean('CarePatient')->nullable();
            $table->boolean('CareCaregiver')->nullable();
            $table->boolean('Medication_regimen')->nullable();
            $table->text('Medication_regimenComments')->nullable();
            $table->boolean('certifyingPhysician')->nullable();
            $table->boolean('certifyingSN')->nullable();
            $table->boolean('certifyingPT')->nullable();
            $table->boolean('certifyingOT')->nullable();
            $table->boolean('certifyingSLP')->nullable();
            $table->boolean('certifyingMSW')->nullable();
            $table->boolean('certifyingAide')->nullable();
            $table->boolean('certifyingOther')->nullable();
            $table->string('certifyingOther_1', 55)->nullable();
            $table->boolean('communityResources')->nullable();
            $table->boolean('livingWill')->nullable();
            $table->boolean('counselingNeeds')->nullable();
            $table->boolean('unsafeEnvironment')->nullable();
            $table->boolean('unsafeEnvironment_1')->nullable();
            $table->string('unsafeEnvironment_com', 55)->nullable();
            $table->string('unsafeEnvironment_date', 55)->nullable();
            $table->string('CarePlan', 10)->nullable();
            $table->text('unsafeEnvironmentComments')->nullable();
            $table->string('REFERRAL', 55)->nullable();
            $table->text('reasonforReferral')->nullable();
            $table->date('reasonforReferral_date')->nullable();
            $table->string('planforNextvisit', 55)->nullable();
            $table->string('recertification', 5)->nullable();
            $table->text('necessityComments')->nullable();
            $table->string('VerbalOrder', 5)->nullable();
            $table->date('specify_date')->nullable();

            // REHABILITATION POTENTIAL FOR ANTICIPATED DISCHARGE PLANNING
            $table->boolean('independentLevel')->nullable();
            $table->boolean('residenceAssistance')->nullable();
            $table->boolean('primaryCaregiver')->nullable();
            $table->boolean('communitysupport')->nullable();
            $table->boolean('Restorative')->nullable();
            $table->boolean('dischargePlan')->nullable();
            $table->boolean('dischargePlanPatient')->nullable();
            $table->boolean('dischargePlanRepresentative')->nullable();
            $table->boolean('dischargePlanRepresentative_other')->nullable();
            $table->string('dischargePlanRepresentative_1', 55)->nullable();
            $table->text('lastassessmentComments')->nullable();
            $table->text('dischargestatusComments')->nullable();

            // CURRENT DME/MEDICAL SUPPLIES/HCBS
            $table->string('DMECompany', 55)->nullable();
            $table->string('DMECompany_Phone', 55)->nullable();
            $table->string('OxygenCompany', 55)->nullable();
            $table->string('OxygenCompany_Phone', 55)->nullable();
            $table->boolean('CommunityOrganizations')->nullable();
            $table->boolean('CommunityServices')->nullable();
            $table->text('CommunityComments')->nullable();
            $table->string('CommunityContact', 55)->nullable();
            $table->string('CommunityPhone', 55)->nullable();
            $table->text('CommunityComment')->nullable();
            $table->boolean('wound_1')->nullable();
            $table->boolean('wound_2')->nullable();
            $table->boolean('wound_3')->nullable();
            $table->boolean('wound_4')->nullable();
            $table->boolean('wound_5')->nullable();
            $table->boolean('wound_6')->nullable();
            $table->boolean('wound_7')->nullable();
            $table->boolean('wound_8')->nullable();
            $table->string('KerlixSize', 55)->nullable();
            $table->boolean('wound_9')->nullable();
            $table->boolean('wound_10')->nullable();
            $table->boolean('wound_11')->nullable();
            $table->boolean('wound_12')->nullable();
            $table->boolean('wound_13')->nullable();
            $table->boolean('wound_14')->nullable();
            $table->boolean('wound_15')->nullable();
            $table->text('woundcomment')->nullable();
            $table->boolean('alcoholSwabs')->nullable();
            $table->boolean('Angiocatheter')->nullable();
            $table->string('AngiocatheterValue', 55)->nullable();
            $table->boolean('Batteries')->nullable();
            $table->string('BatteriesValue', 55)->nullable();
            $table->boolean('Central')->nullable();
            $table->boolean('Extension')->nullable();
            $table->boolean('Infusion_pump')->nullable();
            $table->boolean('Injection_caps')->nullable();
            $table->boolean('IV_pole')->nullable();
            $table->boolean('IV_start')->nullable();
            $table->boolean('IV_tubing')->nullable();
            $table->boolean('Syringes')->nullable();
            $table->string('SyringesValue', 55)->nullable();
            $table->boolean('Tape')->nullable();
            $table->boolean('TapeOther')->nullable();
            $table->text('TapeComments')->nullable();
            $table->boolean('External_catheters')->nullable();
            $table->boolean('ostomyPouch')->nullable();
            $table->string('ostomyPouchValue', 55)->nullable();
            $table->boolean('ostomyWafer')->nullable();
            $table->string('ostomyWaferValue', 55)->nullable();
            $table->boolean('protectant')->nullable();
            $table->boolean('Stoma')->nullable();
            $table->boolean('Underpads')->nullable();
            $table->boolean('Urinary')->nullable();
            $table->boolean('Pouch')->nullable();
            $table->boolean('pouchOther')->nullable();
            $table->text('pouchComments')->nullable();
            $table->boolean('Aceticacid')->nullable();
            $table->boolean('catheterKit')->nullable();
            $table->string('catheterKitValue', 55)->nullable();
            $table->boolean('irrigationTray')->nullable();
            $table->boolean('catheterSaline')->nullable();
            $table->boolean('straightCatheter')->nullable();
            $table->boolean('straightCatheter_1')->nullable();
            $table->text('straightCatheterComments')->nullable();
            $table->boolean('diabeticchemstrips')->nullable();
            $table->boolean('diabeticSyringes')->nullable();
            $table->boolean('diabeticSyringes_1')->nullable();
            $table->text('diabeticSyringesComments')->nullable();
            $table->boolean('EnemaSupplies')->nullable();
            $table->boolean('Feeding_tube')->nullable();
            $table->string('feedingtubeType', 55)->nullable();
            $table->string('feedingtubeSize', 55)->nullable();
            $table->boolean('Gloves')->nullable();
            $table->boolean('Sterile_1')->nullable();
            $table->boolean('sterile')->nullable();
            $table->boolean('medBox')->nullable();
            $table->boolean('stapleremovalKit')->nullable();
            $table->boolean('steriStrips')->nullable();
            $table->boolean('sutureremovalKit')->nullable();
            $table->boolean('sutureremovalKit_other')->nullable();
            $table->text('sutureremovalKitcomments')->nullable();
            $table->boolean('alternative')->nullable();
            $table->text('alternativeComments')->nullable();
            $table->boolean('bathBench')->nullable();
            $table->boolean('Brace')->nullable();
            $table->boolean('Orthotics')->nullable();
            $table->text('suppliesComments')->nullable();
            $table->boolean('Cane_1')->nullable();
            $table->boolean('Commode')->nullable();
            $table->boolean('dressingAid')->nullable();
            $table->boolean('Eggcrate')->nullable();
            $table->boolean('enteralFeeding')->nullable();
            $table->boolean('grabBars')->nullable();
            $table->text('grabBarsComments')->nullable();
            $table->boolean('handheldShower')->nullable();
            $table->boolean('hospitalBed')->nullable();
            $table->boolean('semiElectric')->nullable();
            $table->boolean('hoyerLift')->nullable();
            $table->boolean('kneeScooter')->nullable();
            $table->boolean('medicalAlert')->nullable();
            $table->boolean('Nebulizer')->nullable();
            $table->boolean('oxygenConcentrator')->nullable();
            $table->boolean('relievingDevice')->nullable();
            $table->string('relievingDeviceValue', 55)->nullable();
            $table->boolean('Prosthesis')->nullable();
            $table->boolean('prosthesisRUE')->nullable();
            $table->boolean('prosthesisRLE')->nullable();
            $table->boolean('prosthesisLUE')->nullable();
            $table->boolean('prosthesisLLE')->nullable();
            $table->boolean('prosthesisOther')->nullable();
            $table->text('prosthesisComments')->nullable();
            $table->boolean('raiseToilet')->nullable();
            $table->boolean('Reacher')->nullable();
            $table->boolean('mattressOverlay')->nullable();
            $table->string('mattressOverlayValue', 55)->nullable();
            $table->boolean('suctionMachine')->nullable();
            $table->boolean('TENSunit')->nullable();
            $table->boolean('transferEquipment')->nullable();
            $table->boolean('Board')->nullable();
            $table->boolean('Lift')->nullable();
            $table->boolean('Ventilator')->nullable();
            $table->boolean('Walker_2')->nullable();
            $table->boolean('Wheelchair_2')->nullable();
            $table->boolean('OtherSupplies')->nullable();
            $table->text('OtherSuppliesComments')->nullable();

            // PHYSICIAN VERBAL ORDER
            $table->boolean('IfphysicainName')->nullable();
            $table->string('physicainName', 55)->nullable();
            $table->boolean('verbalOrder')->nullable();
            $table->string('Signature', 55)->nullable();
            $table->date('signatureDate')->nullable();
            $table->string('signatureTime', 15)->nullable();
            $table->string('physicianSignature', 55)->nullable();
            $table->date('physicianDate')->nullable();
            $table->string('physicianTime', 15)->nullable();

            // SIGNATURES/DATES
            $table->string('pfcr', 55)->nullable();
            $table->date('pfcr_date')->nullable();
            $table->string('pfcr_time', 15)->nullable();
            $table->string('pcf_signature', 55)->nullable();
            $table->date('pcf_date')->nullable();
            $table->string('pcf_time', 15)->nullable();
            $table->string('AgencyName', 55)->nullable();
            $table->string('AgencyPhone', 55)->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('oasis_e_recertifications');
    }
};
