<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('oasis_e_recertification_section_m_s', function (Blueprint $table) {
            $table->id();

            // Section M: Skin Conditions
            $table->boolean('NAwoundCare')->nullable();
            $table->text('WoundCare', 5)->nullable();
            $table->text('woundCare_location', 55)->nullable();
            $table->boolean('IfSoiledDressing')->nullable();
            $table->text('SoiledDressing', 15)->nullable();
            $table->text('WCCaregiverName', 55)->nullable();
            $table->text('otherWoundcare', 55)->nullable();
            $table->text('Technique', 15)->nullable();
            $table->boolean('Hands_washed')->nullable();
            $table->boolean('before')->nullable();
            $table->boolean('after_dressing')->nullable();
            $table->boolean('woundCleaned')->nullable();
            $table->text('woundCleaned_Other', 55)->nullable();
            $table->boolean('wounddressingApplied')->nullable();
            $table->text('other_wounddressingApplied', 55)->nullable();
            $table->boolean('woundIrrigated')->nullable();
            $table->text('other_woundIrrigated', 55)->nullable();
            $table->boolean('dressingSecured')->nullable();
            $table->text('other_dressingSecured', 55)->nullable();
            $table->boolean('woundPacked')->nullable();
            $table->text('other_woundPacked', 55)->nullable();
            $table->boolean('dressedproperly')->nullable();
            $table->text('PatientTolerated', 5)->nullable();
            $table->text('woundComments')->nullable();
            $table->text('FrequencyOfDiabetic', 15)->nullable();
            $table->text('FrequencyOfDiabetic_1', 55)->nullable();
            $table->text('DoneBy', 15)->nullable();
            $table->text('DoneByCaregiver', 55)->nullable();
            $table->text('otherDoneBy', 55)->nullable();
            $table->text('ExamByClinician', 5)->nullable();
            $table->text('findingsExplain')->nullable();
            $table->text('PedalPulsesPresent', 15)->nullable();
            $table->text('PedalPulsesAbsent', 15)->nullable();
            $table->text('comment_PedalPulsesAbsent', 55)->nullable();
            $table->text('LossOfSenseWarm', 15)->nullable();
            $table->text('LossOfSenseCold', 15)->nullable();
            $table->text('otherCold', 55)->nullable();
            $table->text('Numbness', 10)->nullable();
            $table->text('NumbnessTingling', 10)->nullable();
            $table->text('NumbnessBurning', 10)->nullable();
            $table->text('LegHairPresent', 10)->nullable();
            $table->text('LegHairAbsent', 10)->nullable();
            $table->text('AbsentComment')->nullable();
            $table->text('integumentaryStatus', 10)->nullable();
            $table->text('woundinfectionExplain')->nullable();
            $table->text('patientAppear', 10)->nullable();
            $table->text('patientAppear_1')->nullable();
            $table->text('patientUnhealedPressureUlcer', 5)->nullable();
            $table->text('woundLesion_1', 55)->nullable();
            $table->text('woundLesion_2', 55)->nullable();
            $table->text('woundLesion_3', 55)->nullable();
            $table->text('woundLesion_4', 55)->nullable();
            $table->text('woundLesion_5', 55)->nullable();
            $table->text('Type1', 20)->nullable();
            $table->text('OtherType1')->nullable();
            $table->text('Type2', 20)->nullable();
            $table->text('OtherType2')->nullable();
            $table->text('Type3', 20)->nullable();
            $table->text('OtherType3')->nullable();
            $table->text('Type4', 20)->nullable();
            $table->text('OtherType4')->nullable();
            $table->text('Type5', 20)->nullable();
            $table->text('OtherType5')->nullable();
            $table->text('sinusTract_length', 55)->nullable();
            $table->text('sinusTract_cm', 55)->nullable();
            $table->text('sinusTractlength', 55)->nullable();
            $table->text('sinusTractcm', 55)->nullable();
            $table->text('sinusTractcm_1', 55)->nullable();
            $table->text('sinusTractcm_2', 55)->nullable();
            $table->text('sinusTractcm_3', 55)->nullable();
            $table->text('sinusTractcm_4', 55)->nullable();
            $table->text('sinusTractcm_5', 55)->nullable();
            $table->text('sinusTractcm_6', 55)->nullable();
            $table->text('Undermining', 55)->nullable();
            $table->text('Undermining_1', 55)->nullable();
            $table->text('Undermining_2', 55)->nullable();
            $table->text('Undermining_3', 55)->nullable();
            $table->text('Undermining_4', 55)->nullable();
            $table->text('Undermining_5', 55)->nullable();
            $table->text('Undermining_6', 55)->nullable();
            $table->text('Undermining_7', 55)->nullable();
            $table->text('Undermining_8', 55)->nullable();
            $table->text('Undermining_9', 55)->nullable();
            $table->text('Undermining_10', 55)->nullable();
            $table->text('Undermining_11', 55)->nullable();
            $table->text('Undermining_12', 55)->nullable();
            $table->text('Undermining_13', 55)->nullable();
            $table->text('Undermining_14', 55)->nullable();
            $table->text('Stage_1', 55)->nullable();
            $table->text('Stage1', 15)->nullable();
            $table->text('Stage_2', 55)->nullable();
            $table->text('Stage2', 15)->nullable();
            $table->text('Stage_3', 55)->nullable();
            $table->text('Stage3', 15)->nullable();
            $table->text('Stage_4', 55)->nullable();
            $table->text('Stage4', 15)->nullable();
            $table->text('Stage_5', 55)->nullable();
            $table->text('Stage5', 15)->nullable();
            $table->boolean('Skin_only')->nullable();
            $table->boolean('Fatty_tissue')->nullable();
            $table->boolean('Muscle')->nullable();
            $table->boolean('Bone')->nullable();
            $table->boolean('MuscleNecrosis')->nullable();
            $table->boolean('Bone_necrosis')->nullable();
            $table->boolean('necrosisOther')->nullable();
            $table->text('necrosisOther1')->nullable();
            $table->boolean('Skin')->nullable();
            $table->boolean('Fatty_tissue_1')->nullable();
            $table->boolean('Muscle_1')->nullable();
            $table->boolean('Bone_1')->nullable();
            $table->boolean('MuscleNecrosis_1')->nullable();
            $table->boolean('Bone_necrosis_1')->nullable();
            $table->boolean('necrosisOther_1')->nullable();
            $table->text('necrosisOther2', 55)->nullable();
            $table->boolean('Skin_1')->nullable();
            $table->boolean('Fatty_tissue_2')->nullable();
            $table->boolean('Muscle_2')->nullable();
            $table->boolean('Bone_2')->nullable();
            $table->boolean('MuscleNecrosis_2')->nullable();
            $table->boolean('Bone_necrosis_2')->nullable();
            $table->boolean('necrosisOther_2')->nullable();
            $table->text('necrosisOther5', 55)->nullable();
            $table->boolean('Skin_2')->nullable();
            $table->boolean('Fatty_tissue_3')->nullable();
            $table->boolean('Muscle_3')->nullable();
            $table->boolean('Bone_3')->nullable();
            $table->boolean('MuscleNecrosis_3')->nullable();
            $table->boolean('Bone_necrosis_3')->nullable();
            $table->boolean('necrosisOther_3')->nullable();
            $table->text('necrosisOther3', 55)->nullable();
            $table->boolean('Skin_3')->nullable();
            $table->boolean('Fatty_tissue_4')->nullable();
            $table->boolean('Muscle_4')->nullable();
            $table->boolean('Bone_4')->nullable();
            $table->boolean('MuscleNecrosis_4')->nullable();
            $table->boolean('Bone_necrosis_4')->nullable();
            $table->boolean('necrosisOther_4')->nullable();
            $table->text('necrosisOther4', 55)->nullable();
            $table->text('Odor1', 5)->nullable();
            $table->text('Odor2', 5)->nullable();
            $table->text('Odor3', 5)->nullable();
            $table->text('Odor4', 5)->nullable();
            $table->text('Odor5', 5)->nullable();
            $table->boolean('Erythema')->nullable();
            $table->boolean('Induration')->nullable();
            $table->boolean('Maceration')->nullable();
            $table->boolean('Normal')->nullable();
            $table->boolean('surroundingOther')->nullable();
            $table->text('surroundingOther1', 55)->nullable();
            $table->boolean('Erythema_1')->nullable();
            $table->boolean('Induration_1')->nullable();
            $table->boolean('Maceration_1')->nullable();
            $table->boolean('Normal_1')->nullable();
            $table->boolean('surroundingOther_1')->nullable();
            $table->text('surroundingOther2', 55)->nullable();
            $table->boolean('Erythema_2')->nullable();
            $table->boolean('Induration_2')->nullable();
            $table->boolean('Maceration_2')->nullable();
            $table->boolean('Normal_2')->nullable();
            $table->boolean('surroundingOther_2')->nullable();
            $table->text('surroundingOther3', 55)->nullable();
            $table->boolean('Erythema_3')->nullable();
            $table->boolean('Induration_3')->nullable();
            $table->boolean('Maceration_3')->nullable();
            $table->boolean('Normal_3')->nullable();
            $table->boolean('surroundingOther_5')->nullable();
            $table->text('surroundingOther6', 55)->nullable();
            $table->boolean('Erythema_6')->nullable();
            $table->boolean('Induration_6')->nullable();
            $table->boolean('Maceration_6')->nullable();
            $table->boolean('Normal_6')->nullable();
            $table->boolean('surroundingOther_3')->nullable();
            $table->text('surroundingOther4', 55)->nullable();
            $table->boolean('Erythema_4')->nullable();
            $table->boolean('Induration_4')->nullable();
            $table->boolean('Maceration_4')->nullable();
            $table->boolean('Normal_4')->nullable();
            $table->boolean('surroundingOther_4')->nullable();
            $table->text('surroundingOther5', 55)->nullable();
            $table->boolean('Slough')->nullable();
            $table->text('appearanceSlough', 55)->nullable();
            $table->boolean('Eschar')->nullable();
            $table->text('appearanceEschar', 55)->nullable();
            $table->boolean('Granulation')->nullable();
            $table->text('appearanceGranulation', 55)->nullable();
            $table->boolean('appearanceSlough11')->nullable();
            $table->text('appearanceEschar11', 55)->nullable();
            $table->boolean('IfAppearanceEschar_11')->nullable();
            $table->text('appearanceEschar_11', 55)->nullable();
            $table->boolean('appearanceGranulation11')->nullable();
            $table->text('appearanceGranulation_11', 55)->nullable();
            $table->boolean('appearanceSlough22')->nullable();
            $table->text('appearanceSlough_22', 55)->nullable();
            $table->boolean('appearanceEschar22')->nullable();
            $table->text('appearanceEschar_22', 55)->nullable();
            $table->boolean('appearanceGranulation33')->nullable();
            $table->text('appearanceGranulation_33', 55)->nullable();
            $table->boolean('appearanceSlough4')->nullable();
            $table->text('appearanceSlough_4', 55)->nullable();
            $table->boolean('appearanceEschar44')->nullable();
            $table->text('appearanceEschar_44', 55)->nullable();
            $table->boolean('appearanceGranulation44')->nullable();
            $table->text('appearanceGranulation_44', 55)->nullable();
            $table->boolean('appearanceSlough55')->nullable();
            $table->text('appearanceSlough_55', 55)->nullable();
            $table->boolean('appearanceEschar5')->nullable();
            $table->text('appearanceEschar_5', 55)->nullable();
            $table->boolean('appearanceGranulation55')->nullable();
            $table->text('appearanceGranulation_5', 55)->nullable();
            $table->text('Drainage1', 15)->nullable();
            $table->text('Drainage2', 15)->nullable();
            $table->text('Drainage3', 15)->nullable();
            $table->text('Drainage4', 15)->nullable();
            $table->text('Drainage5', 15)->nullable();
            $table->text('Color1', 20)->nullable();
            $table->text('Color2', 20)->nullable();
            $table->text('Color3', 20)->nullable();
            $table->text('Color4', 20)->nullable();
            $table->text('Color5', 20)->nullable();
            $table->text('Consistency1', 10)->nullable();
            $table->text('Consistency2', 10)->nullable();
            $table->text('Consistency3', 10)->nullable();
            $table->text('Consistency4', 10)->nullable();
            $table->text('Consistency5', 10)->nullable();
            $table->text('IncisionStatus1', 10)->nullable();
            $table->text('IncisionStatus2', 10)->nullable();
            $table->text('IncisionStatus3', 10)->nullable();
            $table->text('IncisionStatus4', 10)->nullable();
            $table->text('IncisionStatus5', 10)->nullable();
            $table->text('DialysisAccess1', 15)->nullable();
            $table->text('dialysisAccess', 55)->nullable();
            $table->text('DialysisAccess2', 15)->nullable();
            $table->text('DialysisAccess_site', 55)->nullable();
            $table->text('DialysisAccess3', 15)->nullable();
            $table->text('DialysisAccess3_site', 55)->nullable();
            $table->text('DialysisAccess4', 15)->nullable();
            $table->text('DialysisAccess4_site', 55)->nullable();
            $table->text('DialysisAccess5', 15)->nullable();
            $table->text('DialysisAccess5_site', 55)->nullable();
            $table->text('IV1', 15)->nullable();
            $table->text('IV_1', 55)->nullable();
            $table->text('lumens', 55)->nullable();
            $table->text('IV2', 15)->nullable();
            $table->text('IV2_1', 55)->nullable();
            $table->text('oflumens', 55)->nullable();
            $table->text('IV3', 15)->nullable();
            $table->text('IV3_1', 55)->nullable();
            $table->text('oflumens_1', 55)->nullable();
            $table->text('IV4', 15)->nullable();
            $table->text('IV4_1', 55)->nullable();
            $table->text('oflumens_2', 55)->nullable();
            $table->text('IV5', 15)->nullable();
            $table->text('IV5_1', 55)->nullable();
            $table->text('oflumens_3', 55)->nullable();
            $table->text('healedComments')->nullable();

            // MEDICATIONS
            $table->boolean('drugRegimen')->nullable();
            $table->date('drugRegimenDate')->nullable();
            $table->text('DrugRegimen_2', 20)->nullable();
            $table->boolean('Potential')->nullable();
            $table->boolean('drugReactions')->nullable();
            $table->boolean('Ineffective')->nullable();
            $table->boolean('Significant')->nullable();
            $table->boolean('significantDrug')->nullable();
            $table->boolean('Duplicate')->nullable();
            $table->boolean('NonCompliance')->nullable();
            $table->boolean('highRisk')->nullable();
            $table->text('highriskcomment')->nullable();
            $table->boolean('medicationAllergies')->nullable();
            $table->boolean('Aspirin')->nullable();
            $table->boolean('Penicillin')->nullable();
            $table->boolean('Sulfa')->nullable();
            $table->boolean('medicationallergiesOther')->nullable();
            $table->text('medicationallergiesOther_1', 55)->nullable();
            $table->text('Psychotropic', 5)->nullable();
            $table->text('FinancialAbility', 5)->nullable();
            $table->boolean('FinancialAbility_1')->nullable();
            $table->text('MSWreferral', 5)->nullable();
            $table->text('MSWreferralComment')->nullable();
            $table->text('problemsAdministering', 5)->nullable();
            $table->text('administeringComments')->nullable();

            // INFUSION
            $table->boolean('infusion')->nullable();
            $table->text('patientIV', 5)->nullable();
            $table->text('patient_IV', 55)->nullable();
            $table->text('numberSite', 55)->nullable();
            $table->text('siteLocations', 55)->nullable();
            $table->integer('lumen')->nullable();
            $table->date('insertionDate')->nullable();
            $table->text('flushSolution', 55)->nullable();
            $table->text('LumenPatent', 5)->nullable();
            $table->text('LumenpatentComments', 55)->nullable();
            $table->boolean('notFlushed')->nullable();
            $table->text('injectionCap', 55)->nullable();
            $table->text('DressingChange', 5)->nullable();
            $table->text('changeFrequency', 55)->nullable();
            $table->boolean('flushed')->nullable();
            $table->boolean('Sterile')->nullable();
            $table->boolean('Clean')->nullable();
            $table->boolean('performedPatient')->nullable();
            $table->boolean('performedNurse')->nullable();
            $table->boolean('performedCaregiver')->nullable();
            $table->boolean('performedFamily')->nullable();
            $table->boolean('performedOther')->nullable();
            $table->text('performedOther_1', 55)->nullable();
            $table->text('skinCondition', 55)->nullable();
            $table->text('infusionSolution', 55)->nullable();
            $table->boolean('pumpType')->nullable();
            $table->text('pumpType_1', 55)->nullable();
            $table->boolean('administeredbyPatient')->nullable();
            $table->boolean('administeredbyNurse')->nullable();
            $table->boolean('administeredbyCaregiver')->nullable();
            $table->boolean('administeredbyFamily')->nullable();
            $table->boolean('administeredbyOther')->nullable();
            $table->text('administeredby_Other', 55)->nullable();
            $table->text('intravenous', 55)->nullable();
            $table->text('InfusionProvided', 5)->nullable();
            $table->text('infusion_Provided', 55)->nullable();

            // IMMUNIZATIONS
            $table->boolean('InfluenzaFlu')->nullable();
            $table->text('Influenza', 5)->nullable();
            $table->boolean('accordingPneumonia')->nullable();
            $table->boolean('accordingTetanus')->nullable();
            $table->boolean('accordingShingles')->nullable();
            $table->boolean('accordingHepatitis')->nullable();
            $table->boolean('otherHepatitis')->nullable();
            $table->text('immunizationGuidelines', 55)->nullable();
            $table->text('Needs', 55)->nullable();
            $table->boolean('Vaccination')->nullable();
            $table->boolean('Vaccination_1')->nullable();
            $table->text('vaccination_booster', 5)->nullable();
            $table->text('personalPreferences')->nullable();

            // REFUSED CARES
            $table->boolean('refusedPatient')->nullable();
            $table->boolean('refusedRepresentative')->nullable();
            $table->boolean('refusedOther')->nullable();
            $table->text('refusedOther1', 55)->nullable();
            $table->boolean('refuseCare')->nullable();
            $table->boolean('refuseService')->nullable();
            $table->text('ServiceYesNo', 5)->nullable();
            $table->text('serviceExplain')->nullable();
            $table->boolean('theCare')->nullable();
            $table->boolean('theServices')->nullable();
            $table->text('ServiceYesNo_1', 5)->nullable();
            $table->text('thecareExplain')->nullable();

            // PATIENT/CAREGIVER/REPRESENTATIVE/FAMILY EDUCATION AND TRAINING FOR CARE PLANNING
            $table->text('WoundCare_2', 5)->nullable();
            $table->boolean('woundCarePatient')->nullable();
            $table->boolean('woundCareCaregiver')->nullable();
            $table->boolean('woundCareRepresentative')->nullable();
            $table->boolean('woundCareFamily')->nullable();
            $table->boolean('diabeticFoot')->nullable();
            $table->boolean('diabeticCare')->nullable();
            $table->text('Diabetic', 5)->nullable();
            $table->boolean('diabeticPatient')->nullable();
            $table->boolean('diabeticCaregiver')->nullable();
            $table->boolean('diabeticRepresentative')->nullable();
            $table->boolean('diabeticFamily')->nullable();
            $table->text('InsulinAdministration', 5)->nullable();
            $table->boolean('insulinPatient')->nullable();
            $table->boolean('insulinCaregiver')->nullable();
            $table->boolean('insulinRepresentative')->nullable();
            $table->boolean('insulinFamily')->nullable();
            $table->text('GlucometerUse', 5)->nullable();
            $table->boolean('glucometer')->nullable();
            $table->boolean('glucometerPatient')->nullable();
            $table->boolean('glucometerRepresentative')->nullable();
            $table->boolean('glucometerFamily')->nullable();
            $table->text('NutritionalManagement', 5)->nullable();
            $table->boolean('nutritionalPatient')->nullable();
            $table->boolean('nutritionalCaregiver')->nullable();
            $table->boolean('nutritionalRepresentative')->nullable();
            $table->boolean('nutritionalFamily')->nullable();
            $table->boolean('Oral')->nullable();
            $table->boolean('Injected')->nullable();
            $table->boolean('Infused')->nullable();
            $table->boolean('Inhaled')->nullable();
            $table->boolean('Topical')->nullable();
            $table->text('MedicationAdministration', 5)->nullable();
            $table->boolean('MedicationAdministration_Patient')->nullable();
            $table->boolean('MedicationAdministration_Caregiver')->nullable();
            $table->boolean('MedicationAdministration_Representative')->nullable();
            $table->boolean('MedicationAdministration_Family')->nullable();
            $table->text('PainManagement', 5)->nullable();
            $table->boolean('painManagement_Patient')->nullable();
            $table->boolean('painManagement_Caregiver')->nullable();
            $table->boolean('painManagement_Representative')->nullable();
            $table->boolean('painManagement_Family')->nullable();
            $table->text('OxygenUse', 5)->nullable();
            $table->boolean('oxygenPatient')->nullable();
            $table->boolean('oxygenCaregiver')->nullable();
            $table->boolean('oxygenRepresentative')->nullable();
            $table->boolean('oxygenFamily')->nullable();
            $table->text('medicalDevices', 5)->nullable();
            $table->boolean('medicalPatient')->nullable();
            $table->boolean('medicalCaregiver')->nullable();
            $table->boolean('medicalRepresentative')->nullable();
            $table->boolean('medicalFamily')->nullable();
            $table->text('PressureReduction', 5)->nullable();
            $table->boolean('pressurePatient')->nullable();
            $table->boolean('pressureCaregiver')->nullable();
            $table->boolean('pressureRepresentative')->nullable();
            $table->boolean('pressureFamily')->nullable();
            $table->text('CatheterCare', 5)->nullable();
            $table->boolean('catheterPatient')->nullable();
            $table->boolean('catheterCaregiver')->nullable();
            $table->boolean('catheterRepresentative')->nullable();
            $table->boolean('catheterFamily')->nullable();
            $table->text('TrachCare', 5)->nullable();
            $table->boolean('trachPatient')->nullable();
            $table->boolean('trachCaregiver')->nullable();
            $table->boolean('trachRepresentative')->nullable();
            $table->boolean('trachFamily')->nullable();
            $table->text('OstomyCare', 5)->nullable();
            $table->boolean('ostomyPatient')->nullable();
            $table->boolean('ostomyCaregiver')->nullable();
            $table->boolean('ostomyRepresentative')->nullable();
            $table->boolean('ostomyFamily')->nullable();
            $table->text('PreparednessPlan', 5)->nullable();
            $table->boolean('emergencyPatient')->nullable();
            $table->boolean('emergencyCaregiver')->nullable();
            $table->boolean('emergencyRepresentative')->nullable();
            $table->boolean('emergencyFamily')->nullable();
            $table->text('InfectionControl', 5)->nullable();
            $table->boolean('infectioncontrolPatient')->nullable();
            $table->boolean('infectioncontrolCaregiver')->nullable();
            $table->boolean('infectioncontrolRepresentative')->nullable();
            $table->boolean('infectioncontrolFamily')->nullable();
            $table->text('ReportToAgency', 5)->nullable();
            $table->boolean('agencyPatient')->nullable();
            $table->boolean('agencyCaregiver')->nullable();
            $table->boolean('agencyRepresentative')->nullable();
            $table->boolean('agencyFamily')->nullable();
            $table->text('PatientRights', 5)->nullable();
            $table->boolean('rightsPatient')->nullable();
            $table->boolean('rightsCaregiver')->nullable();
            $table->boolean('rightsRepresentative')->nullable();
            $table->boolean('rightsFamily')->nullable();
            $table->text('rightsComments')->nullable();
            $table->boolean('methodEducate')->nullable();
            $table->boolean('methodTrain')->nullable();
            $table->boolean('methodPatient')->nullable();
            $table->boolean('methodCaregiver')->nullable();
            $table->boolean('methodRepresentative')->nullable();
            $table->boolean('methodFamily')->nullable();
            $table->boolean('methodusedPatient')->nullable();
            $table->boolean('methodusedCaregiver')->nullable();
            $table->boolean('methodusedRepresentative')->nullable();
            $table->boolean('methodusedFamilyeducated')->nullable();
            $table->text('methodusedFamilyeducated_other', 55)->nullable();
            $table->boolean('teachPatient')->nullable();
            $table->boolean('teachCaregiver')->nullable();
            $table->boolean('teachRepresentative')->nullable();
            $table->boolean('teachFamily')->nullable();
            $table->boolean('teachEducation')->nullable();
            $table->boolean('teachTraining')->nullable();
            $table->boolean('usedteachPatient')->nullable();
            $table->boolean('usedteachCaregiver')->nullable();
            $table->boolean('usedteachRepresentative')->nullable();
            $table->boolean('usedteachFamily')->nullable();
            $table->text('actionPlan', 5)->nullable();

            // NURSING INTERVENTIONS/INSTRUCTIONS
            $table->boolean('skilledObservation')->nullable();
            $table->boolean('foleyCare')->nullable();
            $table->boolean('Wound_care')->nullable();
            $table->boolean('Wound_dressing')->nullable();
            $table->boolean('Pressure_ulcer')->nullable();
            $table->boolean('Venipuncture')->nullable();
            $table->boolean('ngchange')->nullable();
            $table->boolean('NG_tube')->nullable();
            $table->boolean('G_tube')->nullable();
            $table->boolean('Adminofvitamin')->nullable();
            $table->boolean('Prep')->nullable();
            $table->boolean('adminInsulin')->nullable();
            $table->boolean('Teach_admin')->nullable();
            $table->boolean('admin_teach')->nullable();
            $table->boolean('ivs')->nullable();
            $table->boolean('Clysis')->nullable();
            $table->boolean('Teach_ostomy')->nullable();
            $table->boolean('conduit_care')->nullable();
            $table->boolean('Teaching')->nullable();
            $table->boolean('tube_feedings')->nullable();
            $table->boolean('teaching_1')->nullable();
            $table->boolean('careofTrach')->nullable();
            $table->boolean('terminally')->nullable();
            $table->boolean('IM_injection')->nullable();
            $table->boolean('SQ_injection')->nullable();
            $table->boolean('Psych_intervention')->nullable();
            $table->boolean('SS_infection')->nullable();
            $table->boolean('Diabetic_observation')->nullable();
            $table->boolean('diabetic_care')->nullable();
            $table->boolean('Observe')->nullable();
            $table->boolean('Teach_medication')->nullable();
            $table->boolean('effects')->nullable();
            $table->boolean('side_effects')->nullable();
            $table->boolean('Physiology_Disease')->nullable();
            $table->boolean('Diet_teaching')->nullable();
            $table->boolean('Safety_factors')->nullable();
            $table->boolean('Prenatal_assessment')->nullable();
            $table->boolean('Post_partum')->nullable();
            $table->boolean('Teachcareof')->nullable();
            $table->boolean('infant')->nullable();
            $table->boolean('child')->nullable();
            $table->boolean('Pain_management')->nullable();
            $table->boolean('Fall_safety')->nullable();
            $table->boolean('Fall_safetyOther')->nullable();
            $table->text('Fall_safetyOtherExplain')->nullable();
            $table->text('SUPERVISORY_VISIT', 5)->nullable();
            $table->text('SUPERVISORY_VISIT_SU', 5)->nullable();
            $table->text('CARE_PLAN_UPDATED', 5)->nullable();
            $table->text('CARE_PLAN_FOLLOWED', 5)->nullable();
            $table->text('CARE_PLAN_FOLLOWED_1')->nullable();
            $table->text('STAFF', 15)->nullable();
            $table->boolean('AIDE')->nullable();
            $table->boolean('LPN_LVN')->nullable();
            $table->text('nextScheduled', 55)->nullable();
            $table->text('PFR_SATISFIED', 20)->nullable();
            $table->text('IScomment')->nullable();
            $table->text('OBSERVATIONcomment')->nullable();
            $table->text('EDUCATIONcomment')->nullable();

            // RECERTIFICATION SUMMARY
            $table->text('CONFINED_TO_HOME', 5)->nullable();
            $table->boolean('adaptiveDevice')->nullable();
            $table->boolean('crutches')->nullable();
            $table->boolean('canes')->nullable();
            $table->boolean('walker_3')->nullable();
            $table->boolean('wheelchair')->nullable();
            $table->boolean('manual')->nullable();
            $table->boolean('motorized')->nullable();
            $table->boolean('prosthetic')->nullable();
            $table->boolean('scooter')->nullable();
            $table->boolean('helper')->nullable();
            $table->boolean('injuryOther')->nullable();
            $table->text('injuryOther_1', 55)->nullable();
            $table->boolean('specialTransportation')->nullable();
            $table->text('special_Transportation', 55)->nullable();
            $table->boolean('hysicalAssist')->nullable();
            $table->text('hysicalAssist_1', 55)->nullable();
            $table->boolean('medicallyContraindicated')->nullable();
            $table->text('edicallyContraindicated_other', 55)->nullable();
            $table->boolean('normalInability')->nullable();
            $table->text('ormalInabilityComment')->nullable();
            $table->boolean('leavingHome')->nullable();
            $table->text('leavingHomeComment')->nullable();
            $table->boolean('desiredFunctional')->nullable();
            $table->text('desiredFunctionalComment')->nullable();
            $table->boolean('functionaltaks')->nullable();
            $table->text('functionaltaksComment')->nullable();
            $table->boolean('expresses')->nullable();
            $table->text('expressesComment')->nullable();

            // SUMMARY CHECKLIST
            $table->integer('CarePlan')->nullable();
            $table->boolean('CareRevised')->nullable();
            $table->boolean('Care')->nullable();
            $table->boolean('CarePatient')->nullable();
            $table->boolean('CareCaregiver')->nullable();
            $table->boolean('Medication_regimen')->nullable();
            $table->text('Medication_regimenComments')->nullable();
            $table->boolean('certifyingPhysician')->nullable();
            $table->boolean('certifyingSN')->nullable();
            $table->boolean('certifyingPT')->nullable();
            $table->boolean('certifyingOT')->nullable();
            $table->boolean('certifyingSLP')->nullable();
            $table->boolean('certifyingMSW')->nullable();
            $table->boolean('certifyingAide')->nullable();
            $table->boolean('certifyingOther')->nullable();
            $table->text('certifyingOther_1', 55)->nullable();
            $table->boolean('communityResources')->nullable();
            $table->boolean('livingWill')->nullable();
            $table->boolean('counselingNeeds')->nullable();
            $table->boolean('unsafeEnvironment')->nullable();
            $table->boolean('unsafeEnvironment_1')->nullable();
            $table->text('unsafeEnvironment_com', 55)->nullable();
            $table->text('unsafeEnvironment_date', 55)->nullable();
            $table->text('CarePlan_2', 10)->nullable();
            $table->text('unsafeEnvironmentComments')->nullable();
            $table->text('REFERRAL', 55)->nullable();
            $table->text('reasonforReferral')->nullable();
            $table->date('reasonforReferral_date')->nullable();
            $table->text('planforNextvisit', 55)->nullable();
            $table->text('recertification', 5)->nullable();
            $table->text('necessityComments')->nullable();
            $table->text('VerbalOrder', 5)->nullable();
            $table->date('specify_date')->nullable();

            // REHABILITATION POTENTIAL FOR ANTICIPATED DISCHARGE PLANNING
            $table->boolean('independentLevel')->nullable();
            $table->boolean('residenceAssistance')->nullable();
            $table->boolean('primaryCaregiver')->nullable();
            $table->boolean('communitysupport')->nullable();
            $table->boolean('Restorative')->nullable();
            $table->boolean('dischargePlan')->nullable();
            $table->boolean('dischargePlanPatient')->nullable();
            $table->boolean('dischargePlanRepresentative')->nullable();
            $table->boolean('dischargePlanRepresentative_other')->nullable();
            $table->text('dischargePlanRepresentative_1', 55)->nullable();
            $table->text('lastassessmentComments')->nullable();
            $table->text('dischargestatusComments')->nullable();

            // CURRENT DME/MEDICAL SUPPLIES/HCBS
            $table->text('DMECompany', 55)->nullable();
            $table->text('DMECompany_Phone', 55)->nullable();
            $table->text('OxygenCompany', 55)->nullable();
            $table->text('OxygenCompany_Phone', 55)->nullable();
            $table->boolean('CommunityOrganizations')->nullable();
            $table->boolean('CommunityServices')->nullable();
            $table->text('CommunityComments')->nullable();
            $table->text('CommunityContact', 55)->nullable();
            $table->text('CommunityPhone', 55)->nullable();
            $table->text('CommunityComment')->nullable();
            $table->boolean('wound_1')->nullable();
            $table->boolean('wound_2')->nullable();
            $table->boolean('wound_3')->nullable();
            $table->boolean('wound_4')->nullable();
            $table->boolean('wound_5')->nullable();
            $table->boolean('wound_6')->nullable();
            $table->boolean('wound_7')->nullable();
            $table->boolean('wound_8')->nullable();
            $table->text('KerlixSize', 55)->nullable();
            $table->boolean('wound_9')->nullable();
            $table->boolean('wound_10')->nullable();
            $table->boolean('wound_11')->nullable();
            $table->boolean('wound_12')->nullable();
            $table->boolean('wound_13')->nullable();
            $table->boolean('wound_14')->nullable();
            $table->boolean('wound_15')->nullable();
            $table->text('woundcomment')->nullable();
            $table->boolean('alcoholSwabs')->nullable();
            $table->boolean('Angiocatheter')->nullable();
            $table->text('AngiocatheterValue', 55)->nullable();
            $table->boolean('Batteries')->nullable();
            $table->text('BatteriesValue', 55)->nullable();
            $table->boolean('Central')->nullable();
            $table->boolean('Extension')->nullable();
            $table->boolean('Infusion_pump')->nullable();
            $table->boolean('Injection_caps')->nullable();
            $table->boolean('IV_pole')->nullable();
            $table->boolean('IV_start')->nullable();
            $table->boolean('IV_tubing')->nullable();
            $table->boolean('Syringes')->nullable();
            $table->text('SyringesValue', 55)->nullable();
            $table->boolean('Tape')->nullable();
            $table->boolean('TapeOther')->nullable();
            $table->text('TapeComments')->nullable();
            $table->boolean('External_catheters')->nullable();
            $table->boolean('ostomyPouch')->nullable();
            $table->text('ostomyPouchValue', 55)->nullable();
            $table->boolean('ostomyWafer')->nullable();
            $table->text('ostomyWaferValue', 55)->nullable();
            $table->boolean('protectant')->nullable();
            $table->boolean('Stoma')->nullable();
            $table->boolean('Underpads')->nullable();
            $table->boolean('Urinary')->nullable();
            $table->boolean('Pouch')->nullable();
            $table->boolean('pouchOther')->nullable();
            $table->text('pouchComments')->nullable();
            $table->boolean('Aceticacid')->nullable();
            $table->boolean('catheterKit')->nullable();
            $table->text('catheterKitValue', 55)->nullable();
            $table->boolean('irrigationTray')->nullable();
            $table->boolean('catheterSaline')->nullable();
            $table->boolean('straightCatheter')->nullable();
            $table->boolean('straightCatheter_1')->nullable();
            $table->text('straightCatheterComments')->nullable();
            $table->boolean('diabeticchemstrips')->nullable();
            $table->boolean('diabeticSyringes')->nullable();
            $table->boolean('diabeticSyringes_1')->nullable();
            $table->text('diabeticSyringesComments')->nullable();
            $table->boolean('EnemaSupplies')->nullable();
            $table->boolean('Feeding_tube')->nullable();
            $table->text('feedingtubeType', 55)->nullable();
            $table->text('feedingtubeSize', 55)->nullable();
            $table->boolean('Gloves')->nullable();
            $table->boolean('Sterile_1')->nullable();
            $table->boolean('NonSterile')->nullable();
            $table->boolean('medBox')->nullable();
            $table->boolean('stapleremovalKit')->nullable();
            $table->boolean('steriStrips')->nullable();
            $table->boolean('sutureremovalKit')->nullable();
            $table->boolean('sutureremovalKit_other')->nullable();
            $table->text('sutureremovalKitcomments')->nullable();
            $table->boolean('alternative')->nullable();
            $table->text('alternativeComments')->nullable();
            $table->boolean('bathBench')->nullable();
            $table->boolean('Brace')->nullable();
            $table->boolean('Orthotics')->nullable();
            $table->text('suppliesComments')->nullable();
            $table->boolean('Cane_1')->nullable();
            $table->boolean('Commode')->nullable();
            $table->boolean('dressingAid')->nullable();
            $table->boolean('Eggcrate')->nullable();
            $table->boolean('enteralFeeding')->nullable();
            $table->boolean('grabBars')->nullable();
            $table->text('grabBarsComments')->nullable();
            $table->boolean('handheldShower')->nullable();
            $table->boolean('hospitalBed')->nullable();
            $table->boolean('semiElectric')->nullable();
            $table->boolean('hoyerLift')->nullable();
            $table->boolean('kneeScooter')->nullable();
            $table->boolean('medicalAlert')->nullable();
            $table->boolean('Nebulizer')->nullable();
            $table->boolean('oxygenConcentrator')->nullable();
            $table->boolean('relievingDevice')->nullable();
            $table->text('relievingDeviceValue', 55)->nullable();
            $table->boolean('Prosthesis')->nullable();
            $table->boolean('prosthesisRUE')->nullable();
            $table->boolean('prosthesisRLE')->nullable();
            $table->boolean('prosthesisLUE')->nullable();
            $table->boolean('prosthesisLLE')->nullable();
            $table->boolean('prosthesisOther')->nullable();
            $table->text('prosthesisComments')->nullable();
            $table->boolean('raiseToilet')->nullable();
            $table->boolean('Reacher')->nullable();
            $table->boolean('mattressOverlay')->nullable();
            $table->text('mattressOverlayValue', 55)->nullable();
            $table->boolean('suctionMachine')->nullable();
            $table->boolean('TENSunit')->nullable();
            $table->boolean('transferEquipment')->nullable();
            $table->boolean('Board')->nullable();
            $table->boolean('Lift')->nullable();
            $table->text('Ventilator')->nullable();
            $table->boolean('Walker_2')->nullable();
            $table->boolean('Wheelchair_2')->nullable();
            $table->boolean('OtherSupplies')->nullable();
            $table->text('OtherSuppliesComments')->nullable();

            // PHYSICIAN VERBAL ORDER
            $table->boolean('IfphysicainName')->nullable();
            $table->text('physicainName', 55)->nullable();
            $table->boolean('verbalOrder_2')->nullable();
            $table->text('Signature', 55)->nullable();
            $table->date('signatureDate')->nullable();
            $table->text('signatureTime', 15)->nullable();
            $table->text('physicianSignature', 55)->nullable();
            $table->date('physicianDate')->nullable();
            $table->text('physicianTime', 15)->nullable();

            // SIGNATURES/DATES
            $table->text('pfcr', 55)->nullable();
            $table->date('pfcr_date')->nullable();
            $table->text('pfcr_time', 15)->nullable();
            $table->text('pcf_signature', 55)->nullable();
            $table->date('pcf_date')->nullable();
            $table->text('pcf_time', 15)->nullable();
            $table->text('AgencyName', 55)->nullable();
            $table->text('AgencyPhone', 55)->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('oasis_e_recertification_section_m_s');
    }
};
